//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ArtEntity
    {
        
        private int _idx;
        
        private string _art001;
        
        private string _art002;
        
        private string _art003;
        
        private string _art004;
        
        private string _art005;
        
        private string _art006;
        
        private string _art007;
        
        private bool _art008;
        
        private DateTime _art009;
        
        private string _art010;
        
        private string _art011;
        
        private string _art012;
        
        private string _art013;
        
        private string _art014;
        
        private string _art015;
        
        private string _art016;
        
        private string _art017;
        
        private string _art018;
        
        private string _art019;
        
        private string _art020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 工艺编号
        /// </summary>

        public string ART001
        {
            get
            {
                return this._art001;
            }
            set
            {
                this._art001 = value;
            }
        }

        /// <summary>
        /// 工艺名称
        /// </summary>

        public string ART002
        {
            get
            {
                return this._art002;
            }
            set
            {
                this._art002 = value;
            }
        }

        /// <summary>
        /// 工艺说明
        /// </summary>

        public string ART003
        {
            get
            {
                return this._art003;
            }
            set
            {
                this._art003 = value;
            }
        }

        /// <summary>
        /// 工艺性质
        /// </summary>

        public string ART004
        {
            get
            {
                return this._art004;
            }
            set
            {
                this._art004 = value;
            }
        }

        /// <summary>
        /// 工时类型
        /// </summary>

        public string ART005
        {
            get
            {
                return this._art005;
            }
            set
            {
                this._art005 = value;
            }
        }

        /// <summary>
        /// 主生产者
        /// </summary>

        public string ART006
        {
            get
            {
                return this._art006;
            }
            set
            {
                this._art006 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string ART007
        {
            get
            {
                return this._art007;
            }
            set
            {
                this._art007 = value;
            }
        }
        
        /// <summary>
        /// 注销
        /// </summary>
                 
        public bool ART008
        {
            get
            {
                return this._art008;
            }
            set
            {
                this._art008 = value;
            }
        }
        
        /// <summary>
        /// 时间
        /// </summary>
                 
        public DateTime ART009
        {
            get
            {
                return this._art009;
            }
            set
            {
                this._art009 = value;
            }
        }
        
        /// <summary>
        /// 操作者
        /// </summary>
                 
        public string ART010
        {
            get
            {
                return this._art010;
            }
            set
            {
                this._art010 = value;
            }
        }
        
        /// <summary>
        /// 工资类型
        /// </summary>
                 
        public string ART011
        {
            get
            {
                return this._art011;
            }
            set
            {
                this._art011 = value;
            }
        }
        
        // 
        public string ART012
        {
            get
            {
                return this._art012;
            }
            set
            {
                this._art012 = value;
            }
        }
        
        // 
        public string ART013
        {
            get
            {
                return this._art013;
            }
            set
            {
                this._art013 = value;
            }
        }
        
        // 
        public string ART014
        {
            get
            {
                return this._art014;
            }
            set
            {
                this._art014 = value;
            }
        }
        
        // 
        public string ART015
        {
            get
            {
                return this._art015;
            }
            set
            {
                this._art015 = value;
            }
        }
        
        // 
        public string ART016
        {
            get
            {
                return this._art016;
            }
            set
            {
                this._art016 = value;
            }
        }
        
        // 
        public string ART017
        {
            get
            {
                return this._art017;
            }
            set
            {
                this._art017 = value;
            }
        }
        
        // 
        public string ART018
        {
            get
            {
                return this._art018;
            }
            set
            {
                this._art018 = value;
            }
        }
        
        // 
        public string ART019
        {
            get
            {
                return this._art019;
            }
            set
            {
                this._art019 = value;
            }
        }
        
        // 
        public string ART020
        {
            get
            {
                return this._art020;
            }
            set
            {
                this._art020 = value;
            }
        }
    }
}
