//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class AruEntity
    {
        
        private int _idx;
        
        private string _aru001;
        
        private string _aru002;
        
        private decimal _aru003;
        
        private decimal _aru004;
        
        private decimal _aru005;
        
        private string _aru006;
        
        private decimal _aru007;
        
        private decimal _aru008;
        
        private decimal _aru009;
        
        private decimal _aru010;
        
        private string _aru011;
        
        private string _aru012;
        
        private string _aru013;
        
        private string _aru014;
        
        private string _aru015;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 工艺编号
        /// </summary>

        public string ARU001
        {
            get
            {
                return this._aru001;
            }
            set
            {
                this._aru001 = value;
            }
        }

        /// <summary>
        /// 区间标准
        /// </summary>

        public string ARU002
        {
            get
            {
                return this._aru002;
            }
            set
            {
                this._aru002 = value;
            }
        }

        /// <summary>
        /// 区间头
        /// </summary>

        public decimal ARU003
        {
            get
            {
                return this._aru003;
            }
            set
            {
                this._aru003 = value;
            }
        }

        /// <summary>
        /// 区间尾
        /// </summary>

        public decimal ARU004
        {
            get
            {
                return this._aru004;
            }
            set
            {
                this._aru004 = value;
            }
        }

        /// <summary>
        /// 价格
        /// </summary>

        public decimal ARU005
        {
            get
            {
                return this._aru005;
            }
            set
            {
                this._aru005 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string ARU006
        {
            get
            {
                return this._aru006;
            }
            set
            {
                this._aru006 = value;
            }
        }

        /// <summary>
        /// 宽区间头
        /// </summary>

        public decimal ARU007
        {
            get
            {
                return this._aru007;
            }
            set
            {
                this._aru007 = value;
            }
        }

        /// <summary>
        /// 宽区间尾
        /// </summary>

        public decimal ARU008
        {
            get
            {
                return this._aru008;
            }
            set
            {
                this._aru008 = value;
            }
        }

        /// <summary>
        /// 厚区间头
        /// </summary>

        public decimal ARU009
        {
            get
            {
                return this._aru009;
            }
            set
            {
                this._aru009 = value;
            }
        }

        /// <summary>
        /// 厚区间尾
        /// </summary>

        public decimal ARU010
        {
            get
            {
                return this._aru010;
            }
            set
            {
                this._aru010 = value;
            }
        }
        
        // 
        public string ARU011
        {
            get
            {
                return this._aru011;
            }
            set
            {
                this._aru011 = value;
            }
        }
        
        // 
        public string ARU012
        {
            get
            {
                return this._aru012;
            }
            set
            {
                this._aru012 = value;
            }
        }
        
        // 
        public string ARU013
        {
            get
            {
                return this._aru013;
            }
            set
            {
                this._aru013 = value;
            }
        }
        
        // 
        public string ARU014
        {
            get
            {
                return this._aru014;
            }
            set
            {
                this._aru014 = value;
            }
        }
        
        // 
        public string ARU015
        {
            get
            {
                return this._aru015;
            }
            set
            {
                this._aru015 = value;
            }
        }
    }
}
