//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class AssembleWorkOrderAWOEntity
    {
        
        private int _idx;
        
        private string _awo001;
        
        private DateTime? _awo002;
        
        private string _awo003;
        
        private DateTime? _awo004;
        
        private bool _awo005;
        
        private bool _awo006;
        
        private string _awo007;
        
        private string _awo008;
        
        private string _awo009;
        
        private string _awo010;
        
        private string _awo011;
        
        private string _awo012;
        
        private string _awo013;
        
        private string _awo014;
        
        private string _awo015;
        
        private string _awo016;
        
        private string _awo017;
        
        private string _awo018;
        
        private string _awo019;
        
        private string _awo020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string AWO001
        {
            get
            {
                return this._awo001;
            }
            set
            {
                this._awo001 = value;
            }
        }

        /// <summary>
        /// 派工时间
        /// </summary>

        public DateTime? AWO002
        {
            get
            {
                return this._awo002;
            }
            set
            {
                this._awo002 = value;
            }
        }

        /// <summary>
        /// 经办人
        /// </summary>

        public string AWO003
        {
            get
            {
                return this._awo003;
            }
            set
            {
                this._awo003 = value;
            }
        }

        /// <summary>
        /// 完工时间
        /// </summary>

        public DateTime? AWO004
        {
            get
            {
                return this._awo004;
            }
            set
            {
                this._awo004 = value;
            }
        }
        
        /// <summary>
        /// 审核
        /// </summary>
                 
        public bool AWO005
        {
            get
            {
                return this._awo005;
            }
            set
            {
                this._awo005 = value;
            }
        }
        
        /// <summary>
        /// 注销
        /// </summary>
                 
        public bool AWO006
        {
            get
            {
                return this._awo006;
            }
            set
            {
                this._awo006 = value;
            }
        }
        
        // 
        public string AWO007
        {
            get
            {
                return this._awo007;
            }
            set
            {
                this._awo007 = value;
            }
        }
        
        // 
        public string AWO008
        {
            get
            {
                return this._awo008;
            }
            set
            {
                this._awo008 = value;
            }
        }
        
        // 
        public string AWO009
        {
            get
            {
                return this._awo009;
            }
            set
            {
                this._awo009 = value;
            }
        }
        
        // 
        public string AWO010
        {
            get
            {
                return this._awo010;
            }
            set
            {
                this._awo010 = value;
            }
        }
        
        // 
        public string AWO011
        {
            get
            {
                return this._awo011;
            }
            set
            {
                this._awo011 = value;
            }
        }
        
        // 
        public string AWO012
        {
            get
            {
                return this._awo012;
            }
            set
            {
                this._awo012 = value;
            }
        }
        
        // 
        public string AWO013
        {
            get
            {
                return this._awo013;
            }
            set
            {
                this._awo013 = value;
            }
        }
        
        // 
        public string AWO014
        {
            get
            {
                return this._awo014;
            }
            set
            {
                this._awo014 = value;
            }
        }
        
        // 
        public string AWO015
        {
            get
            {
                return this._awo015;
            }
            set
            {
                this._awo015 = value;
            }
        }
        
        // 
        public string AWO016
        {
            get
            {
                return this._awo016;
            }
            set
            {
                this._awo016 = value;
            }
        }
        
        // 
        public string AWO017
        {
            get
            {
                return this._awo017;
            }
            set
            {
                this._awo017 = value;
            }
        }
        
        // 
        public string AWO018
        {
            get
            {
                return this._awo018;
            }
            set
            {
                this._awo018 = value;
            }
        }
        
        // 
        public string AWO019
        {
            get
            {
                return this._awo019;
            }
            set
            {
                this._awo019 = value;
            }
        }
        
        // 
        public string AWO020
        {
            get
            {
                return this._awo020;
            }
            set
            {
                this._awo020 = value;
            }
        }
    }
}
