//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class AssembleWorkOrderAWQEntity
    {
        
        private int _idx;
        
        private string _awq001;
        
        private string _awq002;
        
        private string _awq003;
        
        private string _awq004;
        
        private string _awq005;
        
        private int _awq006;
        
        private decimal _awq007;
        
        private string _awq008;
        
        private string _awq009;
        
        private string _awq010;
        
        private string _awq011;
        
        private string _awq012;
        
        private string _awq013;
        
        private string _awq014;
        
        private string _awq015;
        
        private string _awq016;
        
        private string _awq017;
        
        private string _awq018;
        
        private string _awq019;
        
        private string _awq020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string AWQ001
        {
            get
            {
                return this._awq001;
            }
            set
            {
                this._awq001 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string AWQ002
        {
            get
            {
                return this._awq002;
            }
            set
            {
                this._awq002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string AWQ003
        {
            get
            {
                return this._awq003;
            }
            set
            {
                this._awq003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string AWQ004
        {
            get
            {
                return this._awq004;
            }
            set
            {
                this._awq004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string AWQ005
        {
            get
            {
                return this._awq005;
            }
            set
            {
                this._awq005 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public int AWQ006
        {
            get
            {
                return this._awq006;
            }
            set
            {
                this._awq006 = value;
            }
        }

        /// <summary>
        /// 单价
        /// </summary>

        public decimal AWQ007
        {
            get
            {
                return this._awq007;
            }
            set
            {
                this._awq007 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string AWQ008
        {
            get
            {
                return this._awq008;
            }
            set
            {
                this._awq008 = value;
            }
        }
        
        /// <summary>
        /// 人员编号
        /// </summary>
                 
        public string AWQ009
        {
            get
            {
                return this._awq009;
            }
            set
            {
                this._awq009 = value;
            }
        }
        
        /// <summary>
        /// 人员姓名
        /// </summary>
                 
        public string AWQ010
        {
            get
            {
                return this._awq010;
            }
            set
            {
                this._awq010 = value;
            }
        }
        
        // 
        public string AWQ011
        {
            get
            {
                return this._awq011;
            }
            set
            {
                this._awq011 = value;
            }
        }
        
        // 
        public string AWQ012
        {
            get
            {
                return this._awq012;
            }
            set
            {
                this._awq012 = value;
            }
        }
        
        // 
        public string AWQ013
        {
            get
            {
                return this._awq013;
            }
            set
            {
                this._awq013 = value;
            }
        }
        
        // 
        public string AWQ014
        {
            get
            {
                return this._awq014;
            }
            set
            {
                this._awq014 = value;
            }
        }
        
        // 
        public string AWQ015
        {
            get
            {
                return this._awq015;
            }
            set
            {
                this._awq015 = value;
            }
        }
        
        // 
        public string AWQ016
        {
            get
            {
                return this._awq016;
            }
            set
            {
                this._awq016 = value;
            }
        }
        
        // 
        public string AWQ017
        {
            get
            {
                return this._awq017;
            }
            set
            {
                this._awq017 = value;
            }
        }
        
        // 
        public string AWQ018
        {
            get
            {
                return this._awq018;
            }
            set
            {
                this._awq018 = value;
            }
        }
        
        // 
        public string AWQ019
        {
            get
            {
                return this._awq019;
            }
            set
            {
                this._awq019 = value;
            }
        }
        
        // 
        public string AWQ020
        {
            get
            {
                return this._awq020;
            }
            set
            {
                this._awq020 = value;
            }
        }
    }
}
