//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class BomWorkPlanWOREntity
    {
        
        private int _idx;
        
        private string _wor001;
        
        private string _wor005;
        
        private string _wor006;
        
        private string _wor007;
        
        private string _wor008;
        
        private string _wor009;
        
        private string _wor010;
        
        private string _wor011;
        
        private string _wor012;
        
        private string _wor013;
        
        private string _wor014;
        
        private string _wor015;
        
        private string _wor016;
        
        private decimal _wor017;
        
        private string _wor018;
        
        private int _wor019;
        
        private string _wor020;
        
        private string _wor021;
        
        private string _wor022;
        
        private DateTime? _wor023;
        
        private string _wor024;
        
        private string _wor025;
        
        private string _wor026;
        
        private string _wor027;
        
        private int _wor028;
        
        private int _wor029;
        
        private string _wor030;
        
        private string _wor031;
        
        private string _wor032;
        
        private string _wor033;
        
        private decimal _wor002;
        
        private DateTime _wor003;
        
        private string _wor004;

        private byte[] _wor034;

        private byte[] _wor035;

        private byte[] _wor036;

        private byte[] _wor037;

        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string WOR001
        {
            get
            {
                return this._wor001;
            }
            set
            {
                this._wor001 = value;
            }
        }

        /// <summary>
        /// 零件编号
        /// </summary>

        public string WOR005
        {
            get
            {
                return this._wor005;
            }
            set
            {
                this._wor005 = value;
            }
        }

        /// <summary>
        /// 零件名称
        /// </summary>

        public string WOR006
        {
            get
            {
                return this._wor006;
            }
            set
            {
                this._wor006 = value;
            }
        }

        /// <summary>
        /// 长
        /// </summary>

        public string WOR007
        {
            get
            {
                return this._wor007;
            }
            set
            {
                this._wor007 = value;
            }
        }

        /// <summary>
        /// 长记工按模
        /// </summary>

        public string WOR008
        {
            get
            {
                return this._wor008;
            }
            set
            {
                this._wor008 = value;
            }
        }

        /// <summary>
        /// 长属性
        /// </summary>

        public string WOR009
        {
            get
            {
                return this._wor009;
            }
            set
            {
                this._wor009 = value;
            }
        }

        /// <summary>
        /// 宽
        /// </summary>

        public string WOR010
        {
            get
            {
                return this._wor010;
            }
            set
            {
                this._wor010 = value;
            }
        }

        /// <summary>
        /// 宽记工按模
        /// </summary>

        public string WOR011
        {
            get
            {
                return this._wor011;
            }
            set
            {
                this._wor011 = value;
            }
        }

        /// <summary>
        /// 宽属性
        /// </summary>

        public string WOR012
        {
            get
            {
                return this._wor012;
            }
            set
            {
                this._wor012 = value;
            }
        }

        /// <summary>
        /// 高
        /// </summary>

        public string WOR013
        {
            get
            {
                return this._wor013;
            }
            set
            {
                this._wor013 = value;
            }
        }

        /// <summary>
        /// 高记工按模
        /// </summary>

        public string WOR014
        {
            get
            {
                return this._wor014;
            }
            set
            {
                this._wor014 = value;
            }
        }

        /// <summary>
        /// 高属性
        /// </summary>

        public string WOR015
        {
            get
            {
                return this._wor015;
            }
            set
            {
                this._wor015 = value;
            }
        }

        /// <summary>
        /// 作业类型
        /// </summary>

        public string WOR016
        {
            get
            {
                return this._wor016;
            }
            set
            {
                this._wor016 = value;
            }
        }

        /// <summary>
        /// 单量
        /// </summary>

        public decimal WOR017
        {
            get
            {
                return this._wor017;
            }
            set
            {
                this._wor017 = value;
            }
        }

        /// <summary>
        /// 材质
        /// </summary>

        public string WOR018
        {
            get
            {
                return this._wor018;
            }
            set
            {
                this._wor018 = value;
            }
        }

        /// <summary>
        /// 板厚（mm）
        /// </summary>

        public int WOR019
        {
            get
            {
                return this._wor019;
            }
            set
            {
                this._wor019 = value;
            }
        }

        /// <summary>
        /// 部件要求
        /// </summary>

        public string WOR020
        {
            get
            {
                return this._wor020;
            }
            set
            {
                this._wor020 = value;
            }
        }

        /// <summary>
        /// 材料等级
        /// </summary>

        public string WOR021
        {
            get
            {
                return this._wor021;
            }
            set
            {
                this._wor021 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string WOR022
        {
            get
            {
                return this._wor022;
            }
            set
            {
                this._wor022 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime? WOR023
        {
            get
            {
                return this._wor023;
            }
            set
            {
                this._wor023 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string WOR024
        {
            get
            {
                return this._wor024;
            }
            set
            {
                this._wor024 = value;
            }
        }

        /// <summary>
        /// 拼法
        /// </summary>

        public string WOR025
        {
            get
            {
                return this._wor025;
            }
            set
            {
                this._wor025 = value;
            }
        }

        /// <summary>
        /// 机加工要求
        /// </summary>

        public string WOR026
        {
            get
            {
                return this._wor026;
            }
            set
            {
                this._wor026 = value;
            }
        }

        /// <summary>
        /// 断料要求
        /// </summary>

        public string WOR027
        {
            get
            {
                return this._wor027;
            }
            set
            {
                this._wor027 = value;
            }
        }

        /// <summary>
        /// 拼砂光净要求(宽)
        /// </summary>

        public int WOR028
        {
            get
            {
                return this._wor028;
            }
            set
            {
                this._wor028 = value;
            }
        }

        /// <summary>
        /// 拼砂光净要求(根)
        /// </summary>

        public int WOR029
        {
            get
            {
                return this._wor029;
            }
            set
            {
                this._wor029 = value;
            }
        }
        
        /// <summary>
        /// 编号
        /// </summary>
                 
        public string WOR030
        {
            get
            {
                return this._wor030;
            }
            set
            {
                this._wor030 = value;
            }
        }
        
        // 
        public string WOR031
        {
            get
            {
                return this._wor031;
            }
            set
            {
                this._wor031 = value;
            }
        }
        
        // 
        public string WOR032
        {
            get
            {
                return this._wor032;
            }
            set
            {
                this._wor032 = value;
            }
        }
        
        // 
        public string WOR033
        {
            get
            {
                return this._wor033;
            }
            set
            {
                this._wor033 = value;
            }
        }
        
        /// <summary>
        /// 压胶
        /// </summary>
                 
        public decimal WOR002
        {
            get
            {
                return this._wor002;
            }
            set
            {
                this._wor002 = value;
            }
        }
        
        // 
        public DateTime WOR003
        {
            get
            {
                return this._wor003;
            }
            set
            {
                this._wor003 = value;
            }
        }
        
        // 
        public string WOR004
        {
            get
            {
                return this._wor004;
            }
            set
            {
                this._wor004 = value;
            }
        }

        /// <summary>
        /// 图片
        /// </summary>
        public byte [ ] WOR034
        {
            get
            {
                return _wor034;
            }

            set
            {
                _wor034 = value;
            }
        }

        /// <summary>
        /// 图片
        /// </summary>
        public byte [ ] WOR035
        {
            get
            {
                return _wor035;
            }

            set
            {
                _wor035 = value;
            }
        }

        /// <summary>
        /// 图片
        /// </summary>
        public byte [ ] WOR036
        {
            get
            {
                return _wor036;
            }

            set
            {
                _wor036 = value;
            }
        }

        /// <summary>
        /// 图片
        /// </summary>
        public byte [ ] WOR037
        {
            get
            {
                return _wor037;
            }

            set
            {
                _wor037 = value;
            }
        }

    }
}
