//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class BomWorkPlanCodeEntity
    {
                
        private int _idx;
        
        private string _wpc001;
        
        private string _wpc002;
        
        private string _wpc003;
        
        private string _wpc004;
        
        private string _wpc005;
        
        private string _wpc006;
        
        private string _wpc007;
        
        private string _wpc008;
        
        private string _wpc009;
        
        private string _wpc010;
        
        private string _wpc011;
        
        private string _wpc012;
        
        private string _wpc013;
        
        private string _wpc014;
        
        private string _wpc015;
        
        private decimal _wpc016;
        
        private string _wpc017;
        
        private int _wpc018;
        
        private string _wpc019;
        
        private string _wpc020;
        
        private string _wpc021;
        
        private DateTime? _wpc022;
        
        private string _wpc023;
        
        private string _wpc024;
        
        private string _wpc025;

        private string _wpc026;
        private int _wpc027;
        private int _wpc028;
        private string _wpc029;
        private byte[] _wpc030;
        private byte[] _wpc031;
        private byte[] _wpc032;
        private byte[] _wpc033;
        private string _wpc036;
        
        private decimal _wpc035;

        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string WPC001
        {
            get
            {
                return this._wpc001;
            }
            set
            {
                this._wpc001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string WPC002
        {
            get
            {
                return this._wpc002;
            }
            set
            {
                this._wpc002 = value;
            }
        }

        /// <summary>
        /// 零件编号
        /// </summary>

        public string WPC003
        {
            get
            {
                return this._wpc003;
            }
            set
            {
                this._wpc003 = value;
            }
        }

        /// <summary>
        /// 零件名称
        /// </summary>

        public string WPC004
        {
            get
            {
                return this._wpc004;
            }
            set
            {
                this._wpc004 = value;
            }
        }

        /// <summary>
        /// 条码
        /// </summary>

        public string WPC005
        {
            get
            {
                return this._wpc005;
            }
            set
            {
                this._wpc005 = value;
            }
        }

        /// <summary>
        /// 长
        /// </summary>

        public string WPC006
        {
            get
            {
                return this._wpc006;
            }
            set
            {
                this._wpc006 = value;
            }
        }

        /// <summary>
        /// 长记工按模
        /// </summary>

        public string WPC007
        {
            get
            {
                return this._wpc007;
            }
            set
            {
                this._wpc007 = value;
            }
        }

        /// <summary>
        /// 长属性
        /// </summary>

        public string WPC008
        {
            get
            {
                return this._wpc008;
            }
            set
            {
                this._wpc008 = value;
            }
        }

        /// <summary>
        /// 宽
        /// </summary>

        public string WPC009
        {
            get
            {
                return this._wpc009;
            }
            set
            {
                this._wpc009 = value;
            }
        }

        /// <summary>
        /// 宽记工按模
        /// </summary>

        public string WPC010
        {
            get
            {
                return this._wpc010;
            }
            set
            {
                this._wpc010 = value;
            }
        }

        /// <summary>
        /// 宽属性
        /// </summary>

        public string WPC011
        {
            get
            {
                return this._wpc011;
            }
            set
            {
                this._wpc011 = value;
            }
        }

        /// <summary>
        /// 高
        /// </summary>

        public string WPC012
        {
            get
            {
                return this._wpc012;
            }
            set
            {
                this._wpc012 = value;
            }
        }

        /// <summary>
        /// 高记工按模
        /// </summary>

        public string WPC013
        {
            get
            {
                return this._wpc013;
            }
            set
            {
                this._wpc013 = value;
            }
        }

        /// <summary>
        /// 高属性
        /// </summary>

        public string WPC014
        {
            get
            {
                return this._wpc014;
            }
            set
            {
                this._wpc014 = value;
            }
        }

        /// <summary>
        /// 作业类型
        /// </summary>

        public string WPC015
        {
            get
            {
                return this._wpc015;
            }
            set
            {
                this._wpc015 = value;
            }
        }

        /// <summary>
        /// 单量
        /// </summary>

        public decimal WPC016
        {
            get
            {
                return this._wpc016;
            }
            set
            {
                this._wpc016 = value;
            }
        }

        /// <summary>
        /// 材质
        /// </summary>

        public string WPC017
        {
            get
            {
                return this._wpc017;
            }
            set
            {
                this._wpc017 = value;
            }
        }

        /// <summary>
        /// 板厚（mm）
        /// </summary>

        public int WPC018
        {
            get
            {
                return this._wpc018;
            }
            set
            {
                this._wpc018 = value;
            }
        }

        /// <summary>
        /// 部件要求
        /// </summary>

        public string WPC019
        {
            get
            {
                return this._wpc019;
            }
            set
            {
                this._wpc019 = value;
            }
        }

        /// <summary>
        /// 材料等级
        /// </summary>

        public string WPC020
        {
            get
            {
                return this._wpc020;
            }
            set
            {
                this._wpc020 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string WPC021
        {
            get
            {
                return this._wpc021;
            }
            set
            {
                this._wpc021 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime? WPC022
        {
            get
            {
                return this._wpc022;
            }
            set
            {
                this._wpc022 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string WPC023
        {
            get
            {
                return this._wpc023;
            }
            set
            {
                this._wpc023 = value;
            }
        }

        /// <summary>
        /// 拼法
        /// </summary>

        public string WPC024
        {
            get
            {
                return this._wpc024;
            }
            set
            {
                this._wpc024 = value;
            }
        }

        /// <summary>
        /// 机加工要求
        /// </summary>

        public string WPC025
        {
            get
            {
                return this._wpc025;
            }
            set
            {
                this._wpc025 = value;
            }
        }

        /// <summary>
        /// 断料要求
        /// </summary>
        public string WPC026
        {
            get
            {
                return _wpc026;
            }

            set
            {
                _wpc026 = value;
            }
        }

        /// <summary>
        /// 拼砂光净要求(宽)
        /// </summary>
        public int WPC027
        {
            get
            {
                return _wpc027;
            }

            set
            {
                _wpc027 = value;
            }
        }

        /// <summary>
        /// 拼砂光净要求(根)
        /// </summary>
        public int WPC028
        {
            get
            {
                return _wpc028;
            }

            set
            {
                _wpc028 = value;
            }
        }

        /// <summary>
        /// 编号
        /// </summary>
        public string WPC029
        {
            get
            {
                return _wpc029;
            }

            set
            {
                _wpc029 = value;
            }
        }

        public byte [ ] WPC030
        {
            get
            {
                return _wpc030;
            }

            set
            {
                _wpc030 = value;
            }
        }

        public byte [ ] WPC031
        {
            get
            {
                return _wpc031;
            }

            set
            {
                _wpc031 = value;
            }
        }

        public byte [ ] WPC032
        {
            get
            {
                return _wpc032;
            }

            set
            {
                _wpc032 = value;
            }
        }

        public byte [ ] WPC033
        {
            get
            {
                return _wpc033;
            }

            set
            {
                _wpc033 = value;
            }
        }

        /// <summary>
        /// 压胶次数
        /// </summary>
        public decimal WPC035
        {
            get
            {
                return _wpc035;
            }

            set
            {
                _wpc035 = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>
        public string WPC036
        {
            get
            {
                return _wpc036;
            }

            set
            {
                _wpc036 = value;
            }
        }

    }
}
