//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class BomWorkPlanWOQEntity
    {
        
        private int _idx;
        
        private string _woq001;
        
        private DateTime? _woq002;
        
        private DateTime? _woq003;
        
        private string _woq004;
        
        private DateTime? _woq005;
        
        private string _woq006;
        
        private bool _woq007;
        
        private string _woq008;
        
        private string _woq009;
        
        private bool _woq010;
        
        private string _woq011;
        
        private string _woq012;
        
        private string _woq013;
        
        private string _woq014;
        
        private string _woq015;
        
        private string _woq016;
        
        private string _woq017;
        
        private string _woq018;
        
        private string _woq019;
        
        private string _woq020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string WOQ001
        {
            get
            {
                return this._woq001;
            }
            set
            {
                this._woq001 = value;
            }
        }

        /// <summary>
        /// 开始时间
        /// </summary>

        public DateTime? WOQ002
        {
            get
            {
                return this._woq002;
            }
            set
            {
                this._woq002 = value;
            }
        }

        /// <summary>
        /// 结束时间
        /// </summary>

        public DateTime? WOQ003
        {
            get
            {
                return this._woq003;
            }
            set
            {
                this._woq003 = value;
            }
        }

        /// <summary>
        /// 负责人
        /// </summary>

        public string WOQ004
        {
            get
            {
                return this._woq004;
            }
            set
            {
                this._woq004 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime? WOQ005
        {
            get
            {
                return this._woq005;
            }
            set
            {
                this._woq005 = value;
            }
        }

        /// <summary>
        /// 操作人
        /// </summary>

        public string WOQ006
        {
            get
            {
                return this._woq006;
            }
            set
            {
                this._woq006 = value;
            }
        }
        
        /// <summary>
        /// 注销
        /// </summary>
                 
        public bool WOQ007
        {
            get
            {
                return this._woq007;
            }
            set
            {
                this._woq007 = value;
            }
        }
        
        /// <summary>
        /// 品名
        /// </summary>
                 
        public string WOQ008
        {
            get
            {
                return this._woq008;
            }
            set
            {
                this._woq008 = value;
            }
        }
        
        /// <summary>
        /// 规格
        /// </summary>
                 
        public string WOQ009
        {
            get
            {
                return this._woq009;
            }
            set
            {
                this._woq009 = value;
            }
        }
        
        /// <summary>
        /// 审核
        /// </summary>
                 
        public bool WOQ010
        {
            get
            {
                return this._woq010;
            }
            set
            {
                this._woq010 = value;
            }
        }
        
        // 
        public string WOQ011
        {
            get
            {
                return this._woq011;
            }
            set
            {
                this._woq011 = value;
            }
        }
        
        // 
        public string WOQ012
        {
            get
            {
                return this._woq012;
            }
            set
            {
                this._woq012 = value;
            }
        }
        
        // 
        public string WOQ013
        {
            get
            {
                return this._woq013;
            }
            set
            {
                this._woq013 = value;
            }
        }
        
        // 
        public string WOQ014
        {
            get
            {
                return this._woq014;
            }
            set
            {
                this._woq014 = value;
            }
        }
        
        // 
        public string WOQ015
        {
            get
            {
                return this._woq015;
            }
            set
            {
                this._woq015 = value;
            }
        }
        
        // 
        public string WOQ016
        {
            get
            {
                return this._woq016;
            }
            set
            {
                this._woq016 = value;
            }
        }
        
        // 
        public string WOQ017
        {
            get
            {
                return this._woq017;
            }
            set
            {
                this._woq017 = value;
            }
        }
        
        // 
        public string WOQ018
        {
            get
            {
                return this._woq018;
            }
            set
            {
                this._woq018 = value;
            }
        }
        
        // 
        public string WOQ019
        {
            get
            {
                return this._woq019;
            }
            set
            {
                this._woq019 = value;
            }
        }
        
        // 
        public string WOQ020
        {
            get
            {
                return this._woq020;
            }
            set
            {
                this._woq020 = value;
            }
        }
    }
}
