//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class EmployeeEntity
    {
        
        private int _idx;
        
        private string _emp001;
        
        private string _emp002;
        
        private string _emp003;
        
        private string _emp004;
        
        private string _emp005;
        
        private string _emp006;
        
        private string _emp007;
        
        private bool _emp008;
        
        private string _emp009;
        
        private string _emp010;
        
        private decimal _emp011;
        
        private string _emp012;
        
        private string _emp013;
        
        private string _emp014;
        
        private string _emp015;
        
        private string _emp016;
        
        private string _emp017;
        
        private string _emp018;
        
        private string _emp019;
        
        private string _emp020;
        
        private string _emp021;
        
        private string _emp022;
        
        private string _emp023;
        
        private string _emp024;
        
        private string _emp025;
        
        private string _emp026;
        
        private string _emp027;
        
        private string _emp028;
        
        private string _emp029;
        
        private string _emp030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 用户编号
        /// </summary>

        public string EMP001
        {
            get
            {
                return this._emp001;
            }
            set
            {
                this._emp001 = value;
            }
        }

        /// <summary>
        /// 人员姓名
        /// </summary>

        public string EMP002
        {
            get
            {
                return this._emp002;
            }
            set
            {
                this._emp002 = value;
            }
        }

        /// <summary>
        /// 部门编号
        /// </summary>

        public string EMP003
        {
            get
            {
                return this._emp003;
            }
            set
            {
                this._emp003 = value;
            }
        }

        /// <summary>
        /// 电话
        /// </summary>

        public string EMP004
        {
            get
            {
                return this._emp004;
            }
            set
            {
                this._emp004 = value;
            }
        }

        /// <summary>
        /// 手机号
        /// </summary>

        public string EMP005
        {
            get
            {
                return this._emp005;
            }
            set
            {
                this._emp005 = value;
            }
        }

        /// <summary>
        /// 电子邮箱
        /// </summary>

        public string EMP006
        {
            get
            {
                return this._emp006;
            }
            set
            {
                this._emp006 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string EMP007
        {
            get
            {
                return this._emp007;
            }
            set
            {
                this._emp007 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool EMP008
        {
            get
            {
                return this._emp008;
            }
            set
            {
                this._emp008 = value;
            }
        }

        /// <summary>
        /// 密码
        /// </summary>

        public string EMP009
        {
            get
            {
                return this._emp009;
            }
            set
            {
                this._emp009 = value;
            }
        }
        
        /// <summary>
        /// 性别
        /// </summary>
                 
        public string EMP010
        {
            get
            {
                return this._emp010;
            }
            set
            {
                this._emp010 = value;
            }
        }
        
        /// <summary>
        /// 工资系数
        /// </summary>
                 
        public decimal EMP011
        {
            get
            {
                return this._emp011;
            }
            set
            {
                this._emp011 = value;
            }
        }
        
        /// <summary>
        /// 分组
        /// </summary>
                 
        public string EMP012
        {
            get
            {
                return this._emp012;
            }
            set
            {
                this._emp012 = value;
            }
        }
        
        // 
        public string EMP013
        {
            get
            {
                return this._emp013;
            }
            set
            {
                this._emp013 = value;
            }
        }
        
        // 
        public string EMP014
        {
            get
            {
                return this._emp014;
            }
            set
            {
                this._emp014 = value;
            }
        }
        
        // 
        public string EMP015
        {
            get
            {
                return this._emp015;
            }
            set
            {
                this._emp015 = value;
            }
        }
        
        // 
        public string EMP016
        {
            get
            {
                return this._emp016;
            }
            set
            {
                this._emp016 = value;
            }
        }
        
        // 
        public string EMP017
        {
            get
            {
                return this._emp017;
            }
            set
            {
                this._emp017 = value;
            }
        }
        
        // 
        public string EMP018
        {
            get
            {
                return this._emp018;
            }
            set
            {
                this._emp018 = value;
            }
        }
        
        // 
        public string EMP019
        {
            get
            {
                return this._emp019;
            }
            set
            {
                this._emp019 = value;
            }
        }
        
        // 
        public string EMP020
        {
            get
            {
                return this._emp020;
            }
            set
            {
                this._emp020 = value;
            }
        }
        
        // 
        public string EMP021
        {
            get
            {
                return this._emp021;
            }
            set
            {
                this._emp021 = value;
            }
        }
        
        // 
        public string EMP022
        {
            get
            {
                return this._emp022;
            }
            set
            {
                this._emp022 = value;
            }
        }
        
        // 
        public string EMP023
        {
            get
            {
                return this._emp023;
            }
            set
            {
                this._emp023 = value;
            }
        }
        
        // 
        public string EMP024
        {
            get
            {
                return this._emp024;
            }
            set
            {
                this._emp024 = value;
            }
        }
        
        // 
        public string EMP025
        {
            get
            {
                return this._emp025;
            }
            set
            {
                this._emp025 = value;
            }
        }
        
        // 
        public string EMP026
        {
            get
            {
                return this._emp026;
            }
            set
            {
                this._emp026 = value;
            }
        }
        
        // 
        public string EMP027
        {
            get
            {
                return this._emp027;
            }
            set
            {
                this._emp027 = value;
            }
        }
        
        // 
        public string EMP028
        {
            get
            {
                return this._emp028;
            }
            set
            {
                this._emp028 = value;
            }
        }
        
        // 
        public string EMP029
        {
            get
            {
                return this._emp029;
            }
            set
            {
                this._emp029 = value;
            }
        }
        
        // 
        public string EMP030
        {
            get
            {
                return this._emp030;
            }
            set
            {
                this._emp030 = value;
            }
        }
    }
}
