//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class EquimentEntity
    {
        
        private int _idx;
        
        private string _equ001;
        
        private string _equ002;
        
        private string _equ003;
        
        private string _equ004;
        
        private string _equ005;
        
        private string _equ006;
        
        private bool _equ007;
        
        private DateTime _equ008;
        
        private string _equ009;
        
        private string _equ010;
        
        private string _equ011;
        
        private string _equ012;
        
        private string _equ013;
        
        private string _equ014;
        
        private string _equ015;
        
        private string _equ016;
        
        private string _equ017;
        
        private string _equ018;
        
        private string _equ019;
        
        private string _equ020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 设备编码
        /// </summary>

        public string EQU001
        {
            get
            {
                return this._equ001;
            }
            set
            {
                this._equ001 = value;
            }
        }

        /// <summary>
        /// 设备名称
        /// </summary>

        public string EQU002
        {
            get
            {
                return this._equ002;
            }
            set
            {
                this._equ002 = value;
            }
        }

        /// <summary>
        /// 设备型号
        /// </summary>

        public string EQU003
        {
            get
            {
                return this._equ003;
            }
            set
            {
                this._equ003 = value;
            }
        }

        /// <summary>
        /// 设备状态
        /// </summary>

        public string EQU004
        {
            get
            {
                return this._equ004;
            }
            set
            {
                this._equ004 = value;
            }
        }

        /// <summary>
        /// 设备车间
        /// </summary>

        public string EQU005
        {
            get
            {
                return this._equ005;
            }
            set
            {
                this._equ005 = value;
            }
        }
        
        // 
        public string EQU006
        {
            get
            {
                return this._equ006;
            }
            set
            {
                this._equ006 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool EQU007
        {
            get
            {
                return this._equ007;
            }
            set
            {
                this._equ007 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime EQU008
        {
            get
            {
                return this._equ008;
            }
            set
            {
                this._equ008 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string EQU009
        {
            get
            {
                return this._equ009;
            }
            set
            {
                this._equ009 = value;
            }
        }
        
        /// <summary>
        /// 备注
        /// </summary>
                 
        public string EQU010
        {
            get
            {
                return this._equ010;
            }
            set
            {
                this._equ010 = value;
            }
        }
        
        // 
        public string EQU011
        {
            get
            {
                return this._equ011;
            }
            set
            {
                this._equ011 = value;
            }
        }
        
        // 
        public string EQU012
        {
            get
            {
                return this._equ012;
            }
            set
            {
                this._equ012 = value;
            }
        }
        
        // 
        public string EQU013
        {
            get
            {
                return this._equ013;
            }
            set
            {
                this._equ013 = value;
            }
        }
        
        // 
        public string EQU014
        {
            get
            {
                return this._equ014;
            }
            set
            {
                this._equ014 = value;
            }
        }
        
        // 
        public string EQU015
        {
            get
            {
                return this._equ015;
            }
            set
            {
                this._equ015 = value;
            }
        }
        
        // 
        public string EQU016
        {
            get
            {
                return this._equ016;
            }
            set
            {
                this._equ016 = value;
            }
        }
        
        // 
        public string EQU017
        {
            get
            {
                return this._equ017;
            }
            set
            {
                this._equ017 = value;
            }
        }
        
        // 
        public string EQU018
        {
            get
            {
                return this._equ018;
            }
            set
            {
                this._equ018 = value;
            }
        }
        
        // 
        public string EQU019
        {
            get
            {
                return this._equ019;
            }
            set
            {
                this._equ019 = value;
            }
        }
        
        // 
        public string EQU020
        {
            get
            {
                return this._equ020;
            }
            set
            {
                this._equ020 = value;
            }
        }
    }
}
