//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class MaintainTransmitMTREntity
    {
        
        private int _idx;
        
        private string _mtr001;
        
        private string _mtr002;
        
        private DateTime _mtr003;
        
        private DateTime _mtr004;
        
        private string _mtr005;
        
        private string _mtr006;
        
        private string _mtr007;
        
        private string _mtr008;
        
        private DateTime _mtr009;
        
        private string _mtr010;
        
        private string _mtr011;
        
        private string _mtr012;
        
        private string _mtr013;
        
        private string _mtr014;
        
        private string _mtr015;
        
        private string _mtr016;
        
        private string _mtr017;
        
        private string _mtr018;
        
        private string _mtr019;
        
        private string _mtr020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 联系编号
        /// </summary>

        public string MTR001
        {
            get
            {
                return this._mtr001;
            }
            set
            {
                this._mtr001 = value;
            }
        }

        /// <summary>
        /// 结束标记
        /// </summary>

        public string MTR002
        {
            get
            {
                return this._mtr002;
            }
            set
            {
                this._mtr002 = value;
            }
        }

        /// <summary>
        /// 开单日期
        /// </summary>

        public DateTime MTR003
        {
            get
            {
                return this._mtr003;
            }
            set
            {
                this._mtr003 = value;
            }
        }

        /// <summary>
        /// 开单时间
        /// </summary>

        public DateTime MTR004
        {
            get
            {
                return this._mtr004;
            }
            set
            {
                this._mtr004 = value;
            }
        }

        /// <summary>
        /// 开单人编号
        /// </summary>

        public string MTR005
        {
            get
            {
                return this._mtr005;
            }
            set
            {
                this._mtr005 = value;
            }
        }

        /// <summary>
        /// 开单人姓名
        /// </summary>

        public string MTR006
        {
            get
            {
                return this._mtr006;
            }
            set
            {
                this._mtr006 = value;
            }
        }

        /// <summary>
        /// 单据编号
        /// </summary>

        public string MTR007
        {
            get
            {
                return this._mtr007;
            }
            set
            {
                this._mtr007 = value;
            }
        }

        /// <summary>
        /// 单据类别
        /// </summary>

        public string MTR008
        {
            get
            {
                return this._mtr008;
            }
            set
            {
                this._mtr008 = value;
            }
        }

        /// <summary>
        /// 最近修改日期
        /// </summary>

        public DateTime MTR009
        {
            get
            {
                return this._mtr009;
            }
            set
            {
                this._mtr009 = value;
            }
        }

        /// <summary>
        /// 流转人员
        /// </summary>

        public string MTR010
        {
            get
            {
                return this._mtr010;
            }
            set
            {
                this._mtr010 = value;
            }
        }

        /// <summary>
        /// 项目简述
        /// </summary>

        public string MTR011
        {
            get
            {
                return this._mtr011;
            }
            set
            {
                this._mtr011 = value;
            }
        }
        
        // 
        public string MTR012
        {
            get
            {
                return this._mtr012;
            }
            set
            {
                this._mtr012 = value;
            }
        }
        
        // 
        public string MTR013
        {
            get
            {
                return this._mtr013;
            }
            set
            {
                this._mtr013 = value;
            }
        }
        
        // 
        public string MTR014
        {
            get
            {
                return this._mtr014;
            }
            set
            {
                this._mtr014 = value;
            }
        }
        
        // 
        public string MTR015
        {
            get
            {
                return this._mtr015;
            }
            set
            {
                this._mtr015 = value;
            }
        }
        
        // 
        public string MTR016
        {
            get
            {
                return this._mtr016;
            }
            set
            {
                this._mtr016 = value;
            }
        }
        
        // 
        public string MTR017
        {
            get
            {
                return this._mtr017;
            }
            set
            {
                this._mtr017 = value;
            }
        }
        
        // 
        public string MTR018
        {
            get
            {
                return this._mtr018;
            }
            set
            {
                this._mtr018 = value;
            }
        }
        
        // 
        public string MTR019
        {
            get
            {
                return this._mtr019;
            }
            set
            {
                this._mtr019 = value;
            }
        }
        
        // 
        public string MTR020
        {
            get
            {
                return this._mtr020;
            }
            set
            {
                this._mtr020 = value;
            }
        }
    }
}
