//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class MaintainTransmitMTSEntity
    {
        
        private int _idx;
        
        private string _mts001;
        
        private string _mts002;
        
        private string _mts003;
        
        private DateTime _mts004;
        
        private string _mts005;
        
        private string _mts006;
        
        private string _mts007;
        
        private string _mts008;
        
        private string _mts009;
        
        private string _mts010;
        
        private string _mts011;
        
        private string _mts012;
        
        private string _mts013;
        
        private string _mts014;
        
        private string _mts015;
        
        private string _mts016;
        
        private string _mts017;
        
        private string _mts018;
        
        private string _mts019;
        
        private string _mts020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 联系编号
        /// </summary>

        public string MTS001
        {
            get
            {
                return this._mts001;
            }
            set
            {
                this._mts001 = value;
            }
        }

        /// <summary>
        /// 联系人
        /// </summary>

        public string MTS002
        {
            get
            {
                return this._mts002;
            }
            set
            {
                this._mts002 = value;
            }
        }

        /// <summary>
        /// 联系内容
        /// </summary>

        public string MTS003
        {
            get
            {
                return this._mts003;
            }
            set
            {
                this._mts003 = value;
            }
        }

        /// <summary>
        /// 联系时间
        /// </summary>

        public DateTime MTS004
        {
            get
            {
                return this._mts004;
            }
            set
            {
                this._mts004 = value;
            }
        }
        
        // 
        public string MTS005
        {
            get
            {
                return this._mts005;
            }
            set
            {
                this._mts005 = value;
            }
        }
        
        // 
        public string MTS006
        {
            get
            {
                return this._mts006;
            }
            set
            {
                this._mts006 = value;
            }
        }
        
        // 
        public string MTS007
        {
            get
            {
                return this._mts007;
            }
            set
            {
                this._mts007 = value;
            }
        }
        
        // 
        public string MTS008
        {
            get
            {
                return this._mts008;
            }
            set
            {
                this._mts008 = value;
            }
        }
        
        // 
        public string MTS009
        {
            get
            {
                return this._mts009;
            }
            set
            {
                this._mts009 = value;
            }
        }
        
        // 
        public string MTS010
        {
            get
            {
                return this._mts010;
            }
            set
            {
                this._mts010 = value;
            }
        }
        
        // 
        public string MTS011
        {
            get
            {
                return this._mts011;
            }
            set
            {
                this._mts011 = value;
            }
        }
        
        // 
        public string MTS012
        {
            get
            {
                return this._mts012;
            }
            set
            {
                this._mts012 = value;
            }
        }
        
        // 
        public string MTS013
        {
            get
            {
                return this._mts013;
            }
            set
            {
                this._mts013 = value;
            }
        }
        
        // 
        public string MTS014
        {
            get
            {
                return this._mts014;
            }
            set
            {
                this._mts014 = value;
            }
        }
        
        // 
        public string MTS015
        {
            get
            {
                return this._mts015;
            }
            set
            {
                this._mts015 = value;
            }
        }
        
        // 
        public string MTS016
        {
            get
            {
                return this._mts016;
            }
            set
            {
                this._mts016 = value;
            }
        }
        
        // 
        public string MTS017
        {
            get
            {
                return this._mts017;
            }
            set
            {
                this._mts017 = value;
            }
        }
        
        // 
        public string MTS018
        {
            get
            {
                return this._mts018;
            }
            set
            {
                this._mts018 = value;
            }
        }
        
        // 
        public string MTS019
        {
            get
            {
                return this._mts019;
            }
            set
            {
                this._mts019 = value;
            }
        }
        
        // 
        public string MTS020
        {
            get
            {
                return this._mts020;
            }
            set
            {
                this._mts020 = value;
            }
        }
    }
}
