//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class OPIEntity
    {
        
        private int _idx;
        
        private string _opi001;
        
        private string _opi002;
        
        private string _opi003;
        
        private decimal _opi004;
        
        private string _opi005;
        
        private string _opi006;
        
        private string _opi007;
        
        private string _opi008;
        
        private string _opi009;
        
        private string _opi010;
        
        private bool _opi011;
        
        private byte[] _opi012;
        
        private string _opi013;
        
        private string _opi014;
        
        private string _opi015;
        
        private string _opi016;
        
        private string _opi017;
        
        private string _opi018;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string OPI001
        {
            get
            {
                return this._opi001;
            }
            set
            {
                this._opi001 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string OPI002
        {
            get
            {
                return this._opi002;
            }
            set
            {
                this._opi002 = value;
            }
        }

        /// <summary>
        /// 产品类别
        /// </summary>

        public string OPI003
        {
            get
            {
                return this._opi003;
            }
            set
            {
                this._opi003 = value;
            }
        }

        /// <summary>
        /// 产值
        /// </summary>

        public decimal OPI004
        {
            get
            {
                return this._opi004;
            }
            set
            {
                this._opi004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string OPI005
        {
            get
            {
                return this._opi005;
            }
            set
            {
                this._opi005 = value;
            }
        }

        /// <summary>
        /// 颜色
        /// </summary>

        public string OPI006
        {
            get
            {
                return this._opi006;
            }
            set
            {
                this._opi006 = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>

        public string OPI007
        {
            get
            {
                return this._opi007;
            }
            set
            {
                this._opi007 = value;
            }
        }

        /// <summary>
        /// 状态
        /// </summary>

        public string OPI008
        {
            get
            {
                return this._opi008;
            }
            set
            {
                this._opi008 = value;
            }
        }

        /// <summary>
        /// 属性
        /// </summary>

        public string OPI009
        {
            get
            {
                return this._opi009;
            }
            set
            {
                this._opi009 = value;
            }
        }

        /// <summary>
        /// 分类
        /// </summary>

        public string OPI010
        {
            get
            {
                return this._opi010;
            }
            set
            {
                this._opi010 = value;
            }
        }
        
        /// <summary>
        /// 注销
        /// </summary>
                 
        public bool OPI011
        {
            get
            {
                return this._opi011;
            }
            set
            {
                this._opi011 = value;
            }
        }
        
        /// <summary>
        /// 产品图片
        /// </summary>
                 
        public byte[] OPI012
        {
            get
            {
                return this._opi012;
            }
            set
            {
                this._opi012 = value;
            }
        }
        
        // 
        public string OPI013
        {
            get
            {
                return this._opi013;
            }
            set
            {
                this._opi013 = value;
            }
        }
        
        // 
        public string OPI014
        {
            get
            {
                return this._opi014;
            }
            set
            {
                this._opi014 = value;
            }
        }
        
        // 
        public string OPI015
        {
            get
            {
                return this._opi015;
            }
            set
            {
                this._opi015 = value;
            }
        }
        
        // 
        public string OPI016
        {
            get
            {
                return this._opi016;
            }
            set
            {
                this._opi016 = value;
            }
        }
        
        // 
        public string OPI017
        {
            get
            {
                return this._opi017;
            }
            set
            {
                this._opi017 = value;
            }
        }
        
        // 
        public string OPI018
        {
            get
            {
                return this._opi018;
            }
            set
            {
                this._opi018 = value;
            }
        }
    }
}
