//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PAIJEntity
    {
        
        private int _idx;
        
        private string _paj001;
        
        private string _paj002;
        
        private string _paj003;
        
        private string _paj004;
        
        private decimal _paj005;
        
        private decimal _paj006;
        
        private decimal _paj007;
        
        private decimal _paj008;
        
        private decimal _paj009;
        
        private decimal _paj010;
        
        private DateTime _paj011;
        
        private string _paj012;
        
        private bool _paj013;
        
        private string _paj014;
        
        private string _paj015;
        
        private string _paj016;
        
        private string _paj017;
        
        private string _paj018;
        
        private string _paj019;
        
        private string _paj020;
        
        private string _paj021;
        
        private string _paj022;
        
        private string _paj023;
        
        private string _paj024;
        
        private string _paj025;
        
        private string _paj026;
        
        private string _paj027;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PAJ001
        {
            get
            {
                return this._paj001;
            }
            set
            {
                this._paj001 = value;
            }
        }

        /// <summary>
        /// 序号
        /// </summary>

        public string PAJ002
        {
            get
            {
                return this._paj002;
            }
            set
            {
                this._paj002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PAJ003
        {
            get
            {
                return this._paj003;
            }
            set
            {
                this._paj003 = value;
            }
        }

        /// <summary>
        /// 油漆编号
        /// </summary>

        public string PAJ004
        {
            get
            {
                return this._paj004;
            }
            set
            {
                this._paj004 = value;
            }
        }

        /// <summary>
        /// 刮毛单价
        /// </summary>

        public decimal PAJ005
        {
            get
            {
                return this._paj005;
            }
            set
            {
                this._paj005 = value;
            }
        }

        /// <summary>
        /// 白坯单价
        /// </summary>

        public decimal PAJ006
        {
            get
            {
                return this._paj006;
            }
            set
            {
                this._paj006 = value;
            }
        }

        /// <summary>
        /// 底漆单价
        /// </summary>

        public decimal PAJ007
        {
            get
            {
                return this._paj007;
            }
            set
            {
                this._paj007 = value;
            }
        }

        /// <summary>
        /// 油磨单价
        /// </summary>

        public decimal PAJ008
        {
            get
            {
                return this._paj008;
            }
            set
            {
                this._paj008 = value;
            }
        }

        /// <summary>
        /// 修色单价
        /// </summary>

        public decimal PAJ009
        {
            get
            {
                return this._paj009;
            }
            set
            {
                this._paj009 = value;
            }
        }

        /// <summary>
        /// 面漆单价
        /// </summary>

        public decimal PAJ010
        {
            get
            {
                return this._paj010;
            }
            set
            {
                this._paj010 = value;
            }
        }

        /// <summary>
        /// 日期
        /// </summary>

        public DateTime PAJ011
        {
            get
            {
                return this._paj011;
            }
            set
            {
                this._paj011 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PAJ012
        {
            get
            {
                return this._paj012;
            }
            set
            {
                this._paj012 = value;
            }
        }
        
        /// <summary>
        /// 注销
        /// </summary>
                 
        public bool PAJ013
        {
            get
            {
                return this._paj013;
            }
            set
            {
                this._paj013 = value;
            }
        }
        
        /// <summary>
        /// 油漆名称
        /// </summary>
                 
        public string PAJ014
        {
            get
            {
                return this._paj014;
            }
            set
            {
                this._paj014 = value;
            }
        }
        
        /// <summary>
        /// 规格
        /// </summary>
                 
        public string PAJ015
        {
            get
            {
                return this._paj015;
            }
            set
            {
                this._paj015 = value;
            }
        }
        
        // 
        public string PAJ016
        {
            get
            {
                return this._paj016;
            }
            set
            {
                this._paj016 = value;
            }
        }
        
        // 
        public string PAJ017
        {
            get
            {
                return this._paj017;
            }
            set
            {
                this._paj017 = value;
            }
        }
        
        // 
        public string PAJ018
        {
            get
            {
                return this._paj018;
            }
            set
            {
                this._paj018 = value;
            }
        }
        
        // 
        public string PAJ019
        {
            get
            {
                return this._paj019;
            }
            set
            {
                this._paj019 = value;
            }
        }
        
        // 
        public string PAJ020
        {
            get
            {
                return this._paj020;
            }
            set
            {
                this._paj020 = value;
            }
        }
        
        // 
        public string PAJ021
        {
            get
            {
                return this._paj021;
            }
            set
            {
                this._paj021 = value;
            }
        }
        
        // 
        public string PAJ022
        {
            get
            {
                return this._paj022;
            }
            set
            {
                this._paj022 = value;
            }
        }
        
        // 
        public string PAJ023
        {
            get
            {
                return this._paj023;
            }
            set
            {
                this._paj023 = value;
            }
        }
        
        // 
        public string PAJ024
        {
            get
            {
                return this._paj024;
            }
            set
            {
                this._paj024 = value;
            }
        }
        
        // 
        public string PAJ025
        {
            get
            {
                return this._paj025;
            }
            set
            {
                this._paj025 = value;
            }
        }
        
        // 
        public string PAJ026
        {
            get
            {
                return this._paj026;
            }
            set
            {
                this._paj026 = value;
            }
        }
        
        // 
        public string PAJ027
        {
            get
            {
                return this._paj027;
            }
            set
            {
                this._paj027 = value;
            }
        }
    }
}
