//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PAITEntity
    {
        
        private int _idx;
        
        private string _pai001;
        
        private string _pai002;
        
        private string _pai003;
        
        private string _pai004;
        
        private string _pai005;
        
        private string _pai006;
        
        private string _pai007;
        
        private decimal _pai008;
        
        private string _pai009;
        
        private DateTime _pai010;
        
        private string _pai011;
        
        private bool _pai012;
        
        private string _pai013;
        
        private string _pai014;
        
        private string _pai015;
        
        private string _pai016;
        
        private string _pai017;
        
        private string _pai018;
        
        private string _pai019;
        
        private string _pai020;
        
        private string _pai021;
        
        private string _pai022;
        
        private string _pai023;
        
        private string _pai024;
        
        private string _pai025;
        
        private string _pai026;
        
        private string _pai027;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PAI001
        {
            get
            {
                return this._pai001;
            }
            set
            {
                this._pai001 = value;
            }
        }

        /// <summary>
        /// 序号
        /// </summary>

        public string PAI002
        {
            get
            {
                return this._pai002;
            }
            set
            {
                this._pai002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PAI003
        {
            get
            {
                return this._pai003;
            }
            set
            {
                this._pai003 = value;
            }
        }

        /// <summary>
        /// 油漆编码
        /// </summary>

        public string PAI004
        {
            get
            {
                return this._pai004;
            }
            set
            {
                this._pai004 = value;
            }
        }

        /// <summary>
        /// 油漆名称
        /// </summary>

        public string PAI005
        {
            get
            {
                return this._pai005;
            }
            set
            {
                this._pai005 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PAI006
        {
            get
            {
                return this._pai006;
            }
            set
            {
                this._pai006 = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>

        public string PAI007
        {
            get
            {
                return this._pai007;
            }
            set
            {
                this._pai007 = value;
            }
        }

        /// <summary>
        /// 用量
        /// </summary>

        public decimal PAI008
        {
            get
            {
                return this._pai008;
            }
            set
            {
                this._pai008 = value;
            }
        }

        /// <summary>
        /// 类别
        /// </summary>

        public string PAI009
        {
            get
            {
                return this._pai009;
            }
            set
            {
                this._pai009 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PAI010
        {
            get
            {
                return this._pai010;
            }
            set
            {
                this._pai010 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PAI011
        {
            get
            {
                return this._pai011;
            }
            set
            {
                this._pai011 = value;
            }
        }
        
        /// <summary>
        /// 注销
        /// </summary>
                 
        public bool PAI012
        {
            get
            {
                return this._pai012;
            }
            set
            {
                this._pai012 = value;
            }
        }
        
        // 
        public string PAI013
        {
            get
            {
                return this._pai013;
            }
            set
            {
                this._pai013 = value;
            }
        }
        
        // 
        public string PAI014
        {
            get
            {
                return this._pai014;
            }
            set
            {
                this._pai014 = value;
            }
        }
        
        // 
        public string PAI015
        {
            get
            {
                return this._pai015;
            }
            set
            {
                this._pai015 = value;
            }
        }
        
        // 
        public string PAI016
        {
            get
            {
                return this._pai016;
            }
            set
            {
                this._pai016 = value;
            }
        }
        
        // 
        public string PAI017
        {
            get
            {
                return this._pai017;
            }
            set
            {
                this._pai017 = value;
            }
        }
        
        // 
        public string PAI018
        {
            get
            {
                return this._pai018;
            }
            set
            {
                this._pai018 = value;
            }
        }
        
        // 
        public string PAI019
        {
            get
            {
                return this._pai019;
            }
            set
            {
                this._pai019 = value;
            }
        }
        
        // 
        public string PAI020
        {
            get
            {
                return this._pai020;
            }
            set
            {
                this._pai020 = value;
            }
        }
        
        // 
        public string PAI021
        {
            get
            {
                return this._pai021;
            }
            set
            {
                this._pai021 = value;
            }
        }
        
        // 
        public string PAI022
        {
            get
            {
                return this._pai022;
            }
            set
            {
                this._pai022 = value;
            }
        }
        
        // 
        public string PAI023
        {
            get
            {
                return this._pai023;
            }
            set
            {
                this._pai023 = value;
            }
        }
        
        // 
        public string PAI024
        {
            get
            {
                return this._pai024;
            }
            set
            {
                this._pai024 = value;
            }
        }
        
        // 
        public string PAI025
        {
            get
            {
                return this._pai025;
            }
            set
            {
                this._pai025 = value;
            }
        }
        
        // 
        public string PAI026
        {
            get
            {
                return this._pai026;
            }
            set
            {
                this._pai026 = value;
            }
        }
        
        // 
        public string PAI027
        {
            get
            {
                return this._pai027;
            }
            set
            {
                this._pai027 = value;
            }
        }
    }
}
