//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanAssembleDayPLDEntity
    {
        
        private int _idx;
        
        private string _pld001;
        
        private string _pld002;
        
        private DateTime _pld003;
        
        private DateTime _pld004;
        
        private bool _pld005;
        
        private bool _pld006;
        
        private DateTime _pld007;
        
        private string _pld008;
        
        private decimal _pld009;
        
        private DateTime? _pld010;
        
        private string _pld011;
        
        private string _pld012;
        
        private string _pld013;
        
        private string _pld014;
        
        private string _pld015;
        
        private string _pld016;
        
        private string _pld017;
        
        private string _pld018;
        
        private string _pld019;
        
        private string _pld020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PLD001
        {
            get
            {
                return this._pld001;
            }
            set
            {
                this._pld001 = value;
            }
        }

        /// <summary>
        /// 工段
        /// </summary>

        public string PLD002
        {
            get
            {
                return this._pld002;
            }
            set
            {
                this._pld002 = value;
            }
        }

        /// <summary>
        /// 计划日期
        /// </summary>

        public DateTime PLD003
        {
            get
            {
                return this._pld003;
            }
            set
            {
                this._pld003 = value;
            }
        }

        /// <summary>
        /// 下单日期
        /// </summary>

        public DateTime PLD004
        {
            get
            {
                return this._pld004;
            }
            set
            {
                this._pld004 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool PLD005
        {
            get
            {
                return this._pld005;
            }
            set
            {
                this._pld005 = value;
            }
        }

        /// <summary>
        /// 审核
        /// </summary>

        public bool PLD006
        {
            get
            {
                return this._pld006;
            }
            set
            {
                this._pld006 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PLD007
        {
            get
            {
                return this._pld007;
            }
            set
            {
                this._pld007 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PLD008
        {
            get
            {
                return this._pld008;
            }
            set
            {
                this._pld008 = value;
            }
        }

        /// <summary>
        /// 完成率
        /// </summary>

        public decimal PLD009
        {
            get
            {
                return this._pld009;
            }
            set
            {
                this._pld009 = value;
            }
        }

        /// <summary>
        /// 上工作日
        /// </summary>

        public DateTime? PLD010
        {
            get
            {
                return this._pld010;
            }
            set
            {
                this._pld010 = value;
            }
        }
        
        // 
        public string PLD011
        {
            get
            {
                return this._pld011;
            }
            set
            {
                this._pld011 = value;
            }
        }
        
        // 
        public string PLD012
        {
            get
            {
                return this._pld012;
            }
            set
            {
                this._pld012 = value;
            }
        }
        
        // 
        public string PLD013
        {
            get
            {
                return this._pld013;
            }
            set
            {
                this._pld013 = value;
            }
        }
        
        // 
        public string PLD014
        {
            get
            {
                return this._pld014;
            }
            set
            {
                this._pld014 = value;
            }
        }
        
        // 
        public string PLD015
        {
            get
            {
                return this._pld015;
            }
            set
            {
                this._pld015 = value;
            }
        }
        
        // 
        public string PLD016
        {
            get
            {
                return this._pld016;
            }
            set
            {
                this._pld016 = value;
            }
        }
        
        // 
        public string PLD017
        {
            get
            {
                return this._pld017;
            }
            set
            {
                this._pld017 = value;
            }
        }
        
        // 
        public string PLD018
        {
            get
            {
                return this._pld018;
            }
            set
            {
                this._pld018 = value;
            }
        }
        
        // 
        public string PLD019
        {
            get
            {
                return this._pld019;
            }
            set
            {
                this._pld019 = value;
            }
        }
        
        // 
        public string PLD020
        {
            get
            {
                return this._pld020;
            }
            set
            {
                this._pld020 = value;
            }
        }
    }
}
