//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanStockDailyWorkEntity
    {
        
        private int _idx;
        
        private string _pdw001;
        
        private string _pdw002;
        
        private string _pdw003;
        
        private string _pdw004;
        
        private string _pdw005;
        
        private int _pdw006;
        
        private int _pdw007;
        
        private int _pdw008;
        
        private int _pdw009;
        
        private int _pdw010;
        
        private int _pdw011;
        
        private DateTime _pdw012;
        
        private DateTime _pdw013;
        
        private string _pdw014;
        
        private bool _pdw015;
        
        private string _pdw016;
        
        private string _pdw017;
        
        private string _pdw018;
        
        private string _pdw019;
        
        private string _pdw020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PDW001
        {
            get
            {
                return this._pdw001;
            }
            set
            {
                this._pdw001 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PDW002
        {
            get
            {
                return this._pdw002;
            }
            set
            {
                this._pdw002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PDW003
        {
            get
            {
                return this._pdw003;
            }
            set
            {
                this._pdw003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PDW004
        {
            get
            {
                return this._pdw004;
            }
            set
            {
                this._pdw004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PDW005
        {
            get
            {
                return this._pdw005;
            }
            set
            {
                this._pdw005 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int PDW006
        {
            get
            {
                return this._pdw006;
            }
            set
            {
                this._pdw006 = value;
            }
        }

        /// <summary>
        /// 断料数量
        /// </summary>

        public int PDW007
        {
            get
            {
                return this._pdw007;
            }
            set
            {
                this._pdw007 = value;
            }
        }

        /// <summary>
        /// 修边数量
        /// </summary>

        public int PDW008
        {
            get
            {
                return this._pdw008;
            }
            set
            {
                this._pdw008 = value;
            }
        }

        /// <summary>
        /// 齿接数量
        /// </summary>

        public int PDW009
        {
            get
            {
                return this._pdw009;
            }
            set
            {
                this._pdw009 = value;
            }
        }

        /// <summary>
        /// 拼板数量
        /// </summary>

        public int PDW010
        {
            get
            {
                return this._pdw010;
            }
            set
            {
                this._pdw010 = value;
            }
        }

        /// <summary>
        /// 刨床数量
        /// </summary>

        public int PDW011
        {
            get
            {
                return this._pdw011;
            }
            set
            {
                this._pdw011 = value;
            }
        }

        /// <summary>
        /// 报工时间
        /// </summary>

        public DateTime PDW012
        {
            get
            {
                return this._pdw012;
            }
            set
            {
                this._pdw012 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PDW013
        {
            get
            {
                return this._pdw013;
            }
            set
            {
                this._pdw013 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PDW014
        {
            get
            {
                return this._pdw014;
            }
            set
            {
                this._pdw014 = value;
            }
        }
        
        /// <summary>
        /// 是否计划报工
        /// </summary>
                 
        public bool PDW015
        {
            get
            {
                return this._pdw015;
            }
            set
            {
                this._pdw015 = value;
            }
        }

        /// <summary>
        /// 日计划单号
        /// </summary>

        public string PDW016
        {
            get
            {
                return this._pdw016;
            }
            set
            {
                this._pdw016 = value;
            }
        }
        
        /// <summary>
        /// 遗留单号
        /// </summary>
                 
        public string PDW017
        {
            get
            {
                return this._pdw017;
            }
            set
            {
                this._pdw017 = value;
            }
        }
        
        // 
        public string PDW018
        {
            get
            {
                return this._pdw018;
            }
            set
            {
                this._pdw018 = value;
            }
        }
        
        // 
        public string PDW019
        {
            get
            {
                return this._pdw019;
            }
            set
            {
                this._pdw019 = value;
            }
        }
        
        // 
        public string PDW020
        {
            get
            {
                return this._pdw020;
            }
            set
            {
                this._pdw020 = value;
            }
        }
    }
}
