//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanMachinWeekDailyWorkEntity
    {
        
        private int _idx;
        
        private string _pme001;
        
        private string _pme002;
        
        private string _pme003;
        
        private string _pme004;
        
        private string _pme005;
        
        private int _pme006;
        
        private int _pme007;
        
        private bool _pme008;
        
        private string _pme009;
        
        private int _pme010;
        
        private int _pme011;
        
        private DateTime _pme012;
        
        private DateTime _pme013;
        
        private string _pme014;
        
        private bool _pme015;
        
        private string _pme016;
        
        private string _pme017;
        
        private string _pme018;
        
        private string _pme019;
        
        private string _pme020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PME001
        {
            get
            {
                return this._pme001;
            }
            set
            {
                this._pme001 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PME002
        {
            get
            {
                return this._pme002;
            }
            set
            {
                this._pme002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PME003
        {
            get
            {
                return this._pme003;
            }
            set
            {
                this._pme003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PME004
        {
            get
            {
                return this._pme004;
            }
            set
            {
                this._pme004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PME005
        {
            get
            {
                return this._pme005;
            }
            set
            {
                this._pme005 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int PME006
        {
            get
            {
                return this._pme006;
            }
            set
            {
                this._pme006 = value;
            }
        }

        /// <summary>
        /// 报工数量
        /// </summary>

        public int PME007
        {
            get
            {
                return this._pme007;
            }
            set
            {
                this._pme007 = value;
            }
        }
        
        /// <summary>
        /// 预排报工
        /// </summary>
                 
        public bool PME008
        {
            get
            {
                return this._pme008;
            }
            set
            {
                this._pme008 = value;
            }
        }
        
        /// <summary>
        /// 周计划单号
        /// </summary>
                 
        public string PME009
        {
            get
            {
                return this._pme009;
            }
            set
            {
                this._pme009 = value;
            }
        }
        
        // 
        public int PME010
        {
            get
            {
                return this._pme010;
            }
            set
            {
                this._pme010 = value;
            }
        }
        
        // 
        public int PME011
        {
            get
            {
                return this._pme011;
            }
            set
            {
                this._pme011 = value;
            }
        }

        /// <summary>
        /// 报工时间
        /// </summary>

        public DateTime PME012
        {
            get
            {
                return this._pme012;
            }
            set
            {
                this._pme012 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PME013
        {
            get
            {
                return this._pme013;
            }
            set
            {
                this._pme013 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PME014
        {
            get
            {
                return this._pme014;
            }
            set
            {
                this._pme014 = value;
            }
        }
        
        // 
        public bool PME015
        {
            get
            {
                return this._pme015;
            }
            set
            {
                this._pme015 = value;
            }
        }
        
        // 
        public string PME016
        {
            get
            {
                return this._pme016;
            }
            set
            {
                this._pme016 = value;
            }
        }
        
        // 
        public string PME017
        {
            get
            {
                return this._pme017;
            }
            set
            {
                this._pme017 = value;
            }
        }
        
        // 
        public string PME018
        {
            get
            {
                return this._pme018;
            }
            set
            {
                this._pme018 = value;
            }
        }
        
        // 
        public string PME019
        {
            get
            {
                return this._pme019;
            }
            set
            {
                this._pme019 = value;
            }
        }
        
        // 
        public string PME020
        {
            get
            {
                return this._pme020;
            }
            set
            {
                this._pme020 = value;
            }
        }
    }
}
