//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanMachinPMCEntity
    {
        
        private int _idx;
        
        private string _pmc001;
        
        private DateTime _pmc002;
        
        private DateTime _pmc003;
        
        private DateTime _pmc004;
        
        private DateTime _pmc005;
        
        private string _pmc006;
        
        private bool _pmc007;
        
        private bool _pmc008;
        
        private string _pmc009;
        
        private string _pmc010;
        
        private string _pmc011;
        
        private string _pmc012;
        
        private string _pmc013;
        
        private string _pmc014;
        
        private string _pmc015;
        
        private string _pmc016;
        
        private string _pmc017;
        
        private string _pmc018;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PMC001
        {
            get
            {
                return this._pmc001;
            }
            set
            {
                this._pmc001 = value;
            }
        }

        /// <summary>
        /// 录入日期
        /// </summary>

        public DateTime PMC002
        {
            get
            {
                return this._pmc002;
            }
            set
            {
                this._pmc002 = value;
            }
        }

        /// <summary>
        /// 下单日期
        /// </summary>

        public DateTime PMC003
        {
            get
            {
                return this._pmc003;
            }
            set
            {
                this._pmc003 = value;
            }
        }

        /// <summary>
        /// 生产周期开始日期
        /// </summary>

        public DateTime PMC004
        {
            get
            {
                return this._pmc004;
            }
            set
            {
                this._pmc004 = value;
            }
        }

        /// <summary>
        /// 生产周期结束日期
        /// </summary>

        public DateTime PMC005
        {
            get
            {
                return this._pmc005;
            }
            set
            {
                this._pmc005 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PMC006
        {
            get
            {
                return this._pmc006;
            }
            set
            {
                this._pmc006 = value;
            }
        }

        /// <summary>
        /// 审核
        /// </summary>

        public bool PMC007
        {
            get
            {
                return this._pmc007;
            }
            set
            {
                this._pmc007 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool PMC008
        {
            get
            {
                return this._pmc008;
            }
            set
            {
                this._pmc008 = value;
            }
        }
        
        /// <summary>
        /// 周次
        /// </summary>
                 
        public string PMC009
        {
            get
            {
                return this._pmc009;
            }
            set
            {
                this._pmc009 = value;
            }
        }
        
        // 
        public string PMC010
        {
            get
            {
                return this._pmc010;
            }
            set
            {
                this._pmc010 = value;
            }
        }
        
        // 
        public string PMC011
        {
            get
            {
                return this._pmc011;
            }
            set
            {
                this._pmc011 = value;
            }
        }
        
        // 
        public string PMC012
        {
            get
            {
                return this._pmc012;
            }
            set
            {
                this._pmc012 = value;
            }
        }
        
        // 
        public string PMC013
        {
            get
            {
                return this._pmc013;
            }
            set
            {
                this._pmc013 = value;
            }
        }
        
        // 
        public string PMC014
        {
            get
            {
                return this._pmc014;
            }
            set
            {
                this._pmc014 = value;
            }
        }
        
        // 
        public string PMC015
        {
            get
            {
                return this._pmc015;
            }
            set
            {
                this._pmc015 = value;
            }
        }
        
        // 
        public string PMC016
        {
            get
            {
                return this._pmc016;
            }
            set
            {
                this._pmc016 = value;
            }
        }
        
        // 
        public string PMC017
        {
            get
            {
                return this._pmc017;
            }
            set
            {
                this._pmc017 = value;
            }
        }
        
        // 
        public string PMC018
        {
            get
            {
                return this._pmc018;
            }
            set
            {
                this._pmc018 = value;
            }
        }
    }
}
