//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanCutCUUEntity
    {
        
        private int _idx;
        
        private string _cuu001;
        
        private string _cuu002;
        
        private int _cuu003;
        
        private DateTime _cuu004;
        
        private string _cuu005;
        
        private DateTime _cuu006;
        
        private string _cuu007;
        
        private string _cuu008;
        
        private string _cuu009;
        
        private bool _cuu010;
        
        private string _cuu011;
        
        private string _cuu012;
        
        private string _cuu013;
        
        private string _cuu014;
        
        private string _cuu015;
        
        private string _cuu016;
        
        private string _cuu017;
        
        private string _cuu018;
        
        private string _cuu019;
        
        private string _cuu020;
        
        private string _cuu021;
        
        private string _cuu022;
        
        private string _cuu023;
        
        private string _cuu024;
        
        private string _cuu025;
        
        private string _cuu026;
        
        private string _cuu027;
        
        private string _cuu028;
        
        private string _cuu029;
        
        private string _cuu030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 生产批号
        /// </summary>

        public string CUU001
        {
            get
            {
                return this._cuu001;
            }
            set
            {
                this._cuu001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string CUU002
        {
            get
            {
                return this._cuu002;
            }
            set
            {
                this._cuu002 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int CUU003
        {
            get
            {
                return this._cuu003;
            }
            set
            {
                this._cuu003 = value;
            }
        }

        /// <summary>
        /// 下料计划完成时间
        /// </summary>

        public DateTime CUU004
        {
            get
            {
                return this._cuu004;
            }
            set
            {
                this._cuu004 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string CUU005
        {
            get
            {
                return this._cuu005;
            }
            set
            {
                this._cuu005 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime CUU006
        {
            get
            {
                return this._cuu006;
            }
            set
            {
                this._cuu006 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string CUU007
        {
            get
            {
                return this._cuu007;
            }
            set
            {
                this._cuu007 = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>

        public string CUU008
        {
            get
            {
                return this._cuu008;
            }
            set
            {
                this._cuu008 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string CUU009
        {
            get
            {
                return this._cuu009;
            }
            set
            {
                this._cuu009 = value;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
                 
        public bool CUU010
        {
            get
            {
                return this._cuu010;
            }
            set
            {
                this._cuu010 = value;
            }
        }
        
        // 
        public string CUU011
        {
            get
            {
                return this._cuu011;
            }
            set
            {
                this._cuu011 = value;
            }
        }
        
        // 
        public string CUU012
        {
            get
            {
                return this._cuu012;
            }
            set
            {
                this._cuu012 = value;
            }
        }
        
        // 
        public string CUU013
        {
            get
            {
                return this._cuu013;
            }
            set
            {
                this._cuu013 = value;
            }
        }
        
        // 
        public string CUU014
        {
            get
            {
                return this._cuu014;
            }
            set
            {
                this._cuu014 = value;
            }
        }
        
        // 
        public string CUU015
        {
            get
            {
                return this._cuu015;
            }
            set
            {
                this._cuu015 = value;
            }
        }
        
        // 
        public string CUU016
        {
            get
            {
                return this._cuu016;
            }
            set
            {
                this._cuu016 = value;
            }
        }
        
        // 
        public string CUU017
        {
            get
            {
                return this._cuu017;
            }
            set
            {
                this._cuu017 = value;
            }
        }
        
        // 
        public string CUU018
        {
            get
            {
                return this._cuu018;
            }
            set
            {
                this._cuu018 = value;
            }
        }
        
        // 
        public string CUU019
        {
            get
            {
                return this._cuu019;
            }
            set
            {
                this._cuu019 = value;
            }
        }
        
        // 
        public string CUU020
        {
            get
            {
                return this._cuu020;
            }
            set
            {
                this._cuu020 = value;
            }
        }
        
        // 
        public string CUU021
        {
            get
            {
                return this._cuu021;
            }
            set
            {
                this._cuu021 = value;
            }
        }
        
        // 
        public string CUU022
        {
            get
            {
                return this._cuu022;
            }
            set
            {
                this._cuu022 = value;
            }
        }
        
        // 
        public string CUU023
        {
            get
            {
                return this._cuu023;
            }
            set
            {
                this._cuu023 = value;
            }
        }
        
        // 
        public string CUU024
        {
            get
            {
                return this._cuu024;
            }
            set
            {
                this._cuu024 = value;
            }
        }
        
        // 
        public string CUU025
        {
            get
            {
                return this._cuu025;
            }
            set
            {
                this._cuu025 = value;
            }
        }
        
        // 
        public string CUU026
        {
            get
            {
                return this._cuu026;
            }
            set
            {
                this._cuu026 = value;
            }
        }
        
        // 
        public string CUU027
        {
            get
            {
                return this._cuu027;
            }
            set
            {
                this._cuu027 = value;
            }
        }
        
        // 
        public string CUU028
        {
            get
            {
                return this._cuu028;
            }
            set
            {
                this._cuu028 = value;
            }
        }
        
        // 
        public string CUU029
        {
            get
            {
                return this._cuu029;
            }
            set
            {
                this._cuu029 = value;
            }
        }
        
        // 
        public string CUU030
        {
            get
            {
                return this._cuu030;
            }
            set
            {
                this._cuu030 = value;
            }
        }
    }
}
