//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanAssemebleDayDailyEntity
    {
        
        private int _idx;
        
        private string _plf001;
        
        private string _plf002;
        
        private string _plf003;
        
        private string _plf004;
        
        private string _plf005;
        
        private int _plf006;
        
        private int _plf007;
        
        private string _plf008;
        
        private string _plf009;
        
        private string _plf010;
        
        private int _plf011;
        
        private DateTime _plf012;
        
        private DateTime _plf013;
        
        private string _plf014;
        
        private bool _plf015;
        
        private string _plf016;
        
        private string _plf017;
        
        private string _plf018;
        
        private string _plf019;
        
        private string _plf020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PLF001
        {
            get
            {
                return this._plf001;
            }
            set
            {
                this._plf001 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PLF002
        {
            get
            {
                return this._plf002;
            }
            set
            {
                this._plf002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PLF003
        {
            get
            {
                return this._plf003;
            }
            set
            {
                this._plf003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PLF004
        {
            get
            {
                return this._plf004;
            }
            set
            {
                this._plf004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PLF005
        {
            get
            {
                return this._plf005;
            }
            set
            {
                this._plf005 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int PLF006
        {
            get
            {
                return this._plf006;
            }
            set
            {
                this._plf006 = value;
            }
        }

        /// <summary>
        /// 报工数量
        /// </summary>

        public int PLF007
        {
            get
            {
                return this._plf007;
            }
            set
            {
                this._plf007 = value;
            }
        }
        
        /// <summary>
        /// 人员编号
        /// </summary>
                 
        public string PLF008
        {
            get
            {
                return this._plf008;
            }
            set
            {
                this._plf008 = value;
            }
        }
        
        /// <summary>
        /// 人员姓名
        /// </summary>
                 
        public string PLF009
        {
            get
            {
                return this._plf009;
            }
            set
            {
                this._plf009 = value;
            }
        }
        
        /// <summary>
        /// 日计划单号
        /// </summary>
                 
        public string PLF010
        {
            get
            {
                return this._plf010;
            }
            set
            {
                this._plf010 = value;
            }
        }
        
        // 
        public int PLF011
        {
            get
            {
                return this._plf011;
            }
            set
            {
                this._plf011 = value;
            }
        }

        /// <summary>
        /// 报工时间
        /// </summary>

        public DateTime PLF012
        {
            get
            {
                return this._plf012;
            }
            set
            {
                this._plf012 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PLF013
        {
            get
            {
                return this._plf013;
            }
            set
            {
                this._plf013 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PLF014
        {
            get
            {
                return this._plf014;
            }
            set
            {
                this._plf014 = value;
            }
        }

        /// <summary>
        /// 计划报工
        /// </summary>

        public bool PLF015
        {
            get
            {
                return this._plf015;
            }
            set
            {
                this._plf015 = value;
            }
        }
        
        /// <summary>
        /// 派工单号
        /// </summary>
                 
        public string PLF016
        {
            get
            {
                return this._plf016;
            }
            set
            {
                this._plf016 = value;
            }
        }
        
        /// <summary>
        /// 遗留单号
        /// </summary>
                 
        public string PLF017
        {
            get
            {
                return this._plf017;
            }
            set
            {
                this._plf017 = value;
            }
        }
        
        // 
        public string PLF018
        {
            get
            {
                return this._plf018;
            }
            set
            {
                this._plf018 = value;
            }
        }
        
        // 
        public string PLF019
        {
            get
            {
                return this._plf019;
            }
            set
            {
                this._plf019 = value;
            }
        }
        
        // 
        public string PLF020
        {
            get
            {
                return this._plf020;
            }
            set
            {
                this._plf020 = value;
            }
        }
    }
}
