//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanStockWorkPSWEntity
    {
        
        private int _idx;
        
        private string _psw001;
        
        private string _psw002;
        
        private DateTime _psw003;
        
        private DateTime _psw004;
        
        private bool _psw005;
        
        private bool _psw006;
        
        private DateTime _psw007;
        
        private string _psw008;
        
        private decimal _psw009;
        
        private DateTime? _psw010;
        
        private string _psw011;
        
        private string _psw012;
        
        private string _psw013;
        
        private string _psw014;
        
        private string _psw015;
        
        private string _psw016;
        
        private string _psw017;
        
        private string _psw018;
        
        private string _psw019;
        
        private string _psw020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PSW001
        {
            get
            {
                return this._psw001;
            }
            set
            {
                this._psw001 = value;
            }
        }

        /// <summary>
        /// 工段
        /// </summary>

        public string PSW002
        {
            get
            {
                return this._psw002;
            }
            set
            {
                this._psw002 = value;
            }
        }

        /// <summary>
        /// 计划日期
        /// </summary>

        public DateTime PSW003
        {
            get
            {
                return this._psw003;
            }
            set
            {
                this._psw003 = value;
            }
        }

        /// <summary>
        /// 下单日期
        /// </summary>

        public DateTime PSW004
        {
            get
            {
                return this._psw004;
            }
            set
            {
                this._psw004 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool PSW005
        {
            get
            {
                return this._psw005;
            }
            set
            {
                this._psw005 = value;
            }
        }

        /// <summary>
        /// 审核
        /// </summary>

        public bool PSW006
        {
            get
            {
                return this._psw006;
            }
            set
            {
                this._psw006 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PSW007
        {
            get
            {
                return this._psw007;
            }
            set
            {
                this._psw007 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PSW008
        {
            get
            {
                return this._psw008;
            }
            set
            {
                this._psw008 = value;
            }
        }
        
        /// <summary>
        /// 完成率
        /// </summary>
                 
        public decimal PSW009
        {
            get
            {
                return this._psw009;
            }
            set
            {
                this._psw009 = value;
            }
        }
        
        /// <summary>
        /// 上工作日
        /// </summary>
                 
        public DateTime? PSW010
        {
            get
            {
                return this._psw010;
            }
            set
            {
                this._psw010 = value;
            }
        }
        
        // 
        public string PSW011
        {
            get
            {
                return this._psw011;
            }
            set
            {
                this._psw011 = value;
            }
        }
        
        // 
        public string PSW012
        {
            get
            {
                return this._psw012;
            }
            set
            {
                this._psw012 = value;
            }
        }
        
        // 
        public string PSW013
        {
            get
            {
                return this._psw013;
            }
            set
            {
                this._psw013 = value;
            }
        }
        
        // 
        public string PSW014
        {
            get
            {
                return this._psw014;
            }
            set
            {
                this._psw014 = value;
            }
        }
        
        // 
        public string PSW015
        {
            get
            {
                return this._psw015;
            }
            set
            {
                this._psw015 = value;
            }
        }
        
        // 
        public string PSW016
        {
            get
            {
                return this._psw016;
            }
            set
            {
                this._psw016 = value;
            }
        }
        
        // 
        public string PSW017
        {
            get
            {
                return this._psw017;
            }
            set
            {
                this._psw017 = value;
            }
        }
        
        // 
        public string PSW018
        {
            get
            {
                return this._psw018;
            }
            set
            {
                this._psw018 = value;
            }
        }
        
        // 
        public string PSW019
        {
            get
            {
                return this._psw019;
            }
            set
            {
                this._psw019 = value;
            }
        }
        
        // 
        public string PSW020
        {
            get
            {
                return this._psw020;
            }
            set
            {
                this._psw020 = value;
            }
        }
    }
}
