//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanMachinPMDEntity
    {
        
        private int _idx;
        
        private string _pmd001;
        
        private string _pmd002;
        
        private string _pmd003;
        
        private string _pmd004;
        
        private string _pmd005;
        
        private string _pmd006;
        
        private int _pmd007;
        
        private DateTime? _pmd008;
        
        private string _pmd009;
        
        private bool _pmd010;
        
        private DateTime _pmd011;
        
        private string _pmd012;
        
        private bool _pmd013;
        
        private string _pmd014;
        
        private string _pmd015;
        
        private string _pmd016;
        
        private string _pmd017;
        
        private string _pmd018;
        
        private string _pmd019;
        
        private string _pmd020;
        
        private string _pmd021;
        
        private string _pmd022;
        
        private string _pmd023;
        
        private string _pmd024;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PMD001
        {
            get
            {
                return this._pmd001;
            }
            set
            {
                this._pmd001 = value;
            }
        }

        /// <summary>
        /// 遗留单号
        /// </summary>

        public string PMD002
        {
            get
            {
                return this._pmd002;
            }
            set
            {
                this._pmd002 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PMD003
        {
            get
            {
                return this._pmd003;
            }
            set
            {
                this._pmd003 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PMD004
        {
            get
            {
                return this._pmd004;
            }
            set
            {
                this._pmd004 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PMD005
        {
            get
            {
                return this._pmd005;
            }
            set
            {
                this._pmd005 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PMD006
        {
            get
            {
                return this._pmd006;
            }
            set
            {
                this._pmd006 = value;
            }
        }

        /// <summary>
        /// 订单量
        /// </summary>

        public int PMD007
        {
            get
            {
                return this._pmd007;
            }
            set
            {
                this._pmd007 = value;
            }
        }

        /// <summary>
        /// 倒圆计划完成时间
        /// </summary>

        public DateTime? PMD008
        {
            get
            {
                return this._pmd008;
            }
            set
            {
                this._pmd008 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PMD009
        {
            get
            {
                return this._pmd009;
            }
            set
            {
                this._pmd009 = value;
            }
        }

        /// <summary>
        /// 预排
        /// </summary>

        public bool PMD010
        {
            get
            {
                return this._pmd010;
            }
            set
            {
                this._pmd010 = value;
            }
        }

        /// <summary>
        /// 录入时间
        /// </summary>

        public DateTime PMD011
        {
            get
            {
                return this._pmd011;
            }
            set
            {
                this._pmd011 = value;
            }
        }

        /// <summary>
        /// 录入者
        /// </summary>

        public string PMD012
        {
            get
            {
                return this._pmd012;
            }
            set
            {
                this._pmd012 = value;
            }
        }
        
        /// <summary>
        /// 是否完成
        /// </summary>
                 
        public bool PMD013
        {
            get
            {
                return this._pmd013;
            }
            set
            {
                this._pmd013 = value;
            }
        }
        
        // 
        public string PMD014
        {
            get
            {
                return this._pmd014;
            }
            set
            {
                this._pmd014 = value;
            }
        }
        
        // 
        public string PMD015
        {
            get
            {
                return this._pmd015;
            }
            set
            {
                this._pmd015 = value;
            }
        }
        
        // 
        public string PMD016
        {
            get
            {
                return this._pmd016;
            }
            set
            {
                this._pmd016 = value;
            }
        }
        
        // 
        public string PMD017
        {
            get
            {
                return this._pmd017;
            }
            set
            {
                this._pmd017 = value;
            }
        }
        
        // 
        public string PMD018
        {
            get
            {
                return this._pmd018;
            }
            set
            {
                this._pmd018 = value;
            }
        }
        
        // 
        public string PMD019
        {
            get
            {
                return this._pmd019;
            }
            set
            {
                this._pmd019 = value;
            }
        }
        
        // 
        public string PMD020
        {
            get
            {
                return this._pmd020;
            }
            set
            {
                this._pmd020 = value;
            }
        }
        
        // 
        public string PMD021
        {
            get
            {
                return this._pmd021;
            }
            set
            {
                this._pmd021 = value;
            }
        }
        
        // 
        public string PMD022
        {
            get
            {
                return this._pmd022;
            }
            set
            {
                this._pmd022 = value;
            }
        }
        
        // 
        public string PMD023
        {
            get
            {
                return this._pmd023;
            }
            set
            {
                this._pmd023 = value;
            }
        }
        
        // 
        public string PMD024
        {
            get
            {
                return this._pmd024;
            }
            set
            {
                this._pmd024 = value;
            }
        }
    }
}
