//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanAssembleWeekPLBEntity
    {
        
        private int _idx;
        
        private string _plb001;
        
        private string _plb002;
        
        private string _plb003;
        
        private string _plb004;
        
        private string _plb005;
        
        private string _plb006;
        
        private int _plb007;
        
        private DateTime? _plb008;
        
        private string _plb009;
        
        private bool _plb010;
        
        private DateTime _plb011;
        
        private string _plb012;
        
        private bool _plb013;
        
        private int _plb014;
        
        private int _plb015;
        
        private DateTime? _plb016;
        
        private string _plb017;
        
        private string _plb018;
        
        private string _plb019;
        
        private string _plb020;
        
        private string _plb021;
        
        private string _plb022;
        
        private string _plb023;
        
        private string _plb024;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PLB001
        {
            get
            {
                return this._plb001;
            }
            set
            {
                this._plb001 = value;
            }
        }

        /// <summary>
        /// 遗留单号
        /// </summary>

        public string PLB002
        {
            get
            {
                return this._plb002;
            }
            set
            {
                this._plb002 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PLB003
        {
            get
            {
                return this._plb003;
            }
            set
            {
                this._plb003 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PLB004
        {
            get
            {
                return this._plb004;
            }
            set
            {
                this._plb004 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PLB005
        {
            get
            {
                return this._plb005;
            }
            set
            {
                this._plb005 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PLB006
        {
            get
            {
                return this._plb006;
            }
            set
            {
                this._plb006 = value;
            }
        }

        /// <summary>
        /// 订单量
        /// </summary>

        public int PLB007
        {
            get
            {
                return this._plb007;
            }
            set
            {
                this._plb007 = value;
            }
        }

        /// <summary>
        /// 倒圆完成时间
        /// </summary>

        public DateTime? PLB008
        {
            get
            {
                return this._plb008;
            }
            set
            {
                this._plb008 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PLB009
        {
            get
            {
                return this._plb009;
            }
            set
            {
                this._plb009 = value;
            }
        }

        /// <summary>
        /// 预排
        /// </summary>

        public bool PLB010
        {
            get
            {
                return this._plb010;
            }
            set
            {
                this._plb010 = value;
            }
        }

        /// <summary>
        /// 录入时间
        /// </summary>

        public DateTime PLB011
        {
            get
            {
                return this._plb011;
            }
            set
            {
                this._plb011 = value;
            }
        }

        /// <summary>
        /// 录入者
        /// </summary>

        public string PLB012
        {
            get
            {
                return this._plb012;
            }
            set
            {
                this._plb012 = value;
            }
        }

        /// <summary>
        /// 
        /// 是否完成
        /// </summary>
        public bool PLB013
        {
            get
            {
                return this._plb013;
            }
            set
            {
                this._plb013 = value;
            }
        }

        /// <summary>
        /// 计划生产量
        /// </summary>

        public int PLB014
        {
            get
            {
                return this._plb014;
            }
            set
            {
                this._plb014 = value;
            }
        }
        
        // 
        public int PLB015
        {
            get
            {
                return this._plb015;
            }
            set
            {
                this._plb015 = value;
            }
        }

        /// <summary>
        /// 组装计划完成时间
        /// </summary>

        public DateTime? PLB016
        {
            get
            {
                return this._plb016;
            }
            set
            {
                this._plb016 = value;
            }
        }
        
        // 
        public string PLB017
        {
            get
            {
                return this._plb017;
            }
            set
            {
                this._plb017 = value;
            }
        }
        
        // 
        public string PLB018
        {
            get
            {
                return this._plb018;
            }
            set
            {
                this._plb018 = value;
            }
        }
        
        // 
        public string PLB019
        {
            get
            {
                return this._plb019;
            }
            set
            {
                this._plb019 = value;
            }
        }
        
        // 
        public string PLB020
        {
            get
            {
                return this._plb020;
            }
            set
            {
                this._plb020 = value;
            }
        }
        
        // 
        public string PLB021
        {
            get
            {
                return this._plb021;
            }
            set
            {
                this._plb021 = value;
            }
        }
        
        // 
        public string PLB022
        {
            get
            {
                return this._plb022;
            }
            set
            {
                this._plb022 = value;
            }
        }
        
        // 
        public string PLB023
        {
            get
            {
                return this._plb023;
            }
            set
            {
                this._plb023 = value;
            }
        }
        
        // 
        public string PLB024
        {
            get
            {
                return this._plb024;
            }
            set
            {
                this._plb024 = value;
            }
        }
    }
}
