//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanMachinWorkPMXEntity
    {
        
        private int _idx;
        
        private string _pmx001;
        
        private string _pmx002;
        
        private string _pmx003;
        
        private string _pmx004;
        
        private string _pmx005;
        
        private int _pmx006;
        
        private int _pmx007;
        
        private string _pmx008;
        
        private DateTime _pmx009;
        
        private string _pmx010;
        
        private bool _pmx011;
        
        private bool _pmx012;
        
        private string _pmx013;
        
        private string _pmx014;
        
        private string _pmx015;
        
        private string _pmx016;
        
        private string _pmx017;
        
        private string _pmx018;
        
        private string _pmx019;
        
        private string _pmx020;
        
        private string _pmx021;
        
        private string _pmx022;
        
        private string _pmx023;
        
        private string _pmx024;
        
        private string _pmx025;
        
        private string _pmx026;
        
        private string _pmx027;
        
        private string _pmx028;
        
        private string _pmx029;
        
        private string _pmx030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PMX001
        {
            get
            {
                return this._pmx001;
            }
            set
            {
                this._pmx001 = value;
            }
        }

        /// <summary>
        /// 完工状态
        /// </summary>

        public string PMX002
        {
            get
            {
                return this._pmx002;
            }
            set
            {
                this._pmx002 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PMX003
        {
            get
            {
                return this._pmx003;
            }
            set
            {
                this._pmx003 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PMX004
        {
            get
            {
                return this._pmx004;
            }
            set
            {
                this._pmx004 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PMX005
        {
            get
            {
                return this._pmx005;
            }
            set
            {
                this._pmx005 = value;
            }
        }

        /// <summary>
        /// 订单数量
        /// </summary>

        public int PMX006
        {
            get
            {
                return this._pmx006;
            }
            set
            {
                this._pmx006 = value;
            }
        }

        /// <summary>
        /// 计划数量
        /// </summary>

        public int PMX007
        {
            get
            {
                return this._pmx007;
            }
            set
            {
                this._pmx007 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PMX008
        {
            get
            {
                return this._pmx008;
            }
            set
            {
                this._pmx008 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PMX009
        {
            get
            {
                return this._pmx009;
            }
            set
            {
                this._pmx009 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PMX010
        {
            get
            {
                return this._pmx010;
            }
            set
            {
                this._pmx010 = value;
            }
        }

        /// <summary>
        /// 完成标记
        /// </summary>

        public bool PMX011
        {
            get
            {
                return this._pmx011;
            }
            set
            {
                this._pmx011 = value;
            }
        }

        /// <summary>
        /// 预排
        /// </summary>

        public bool PMX012
        {
            get
            {
                return this._pmx012;
            }
            set
            {
                this._pmx012 = value;
            }
        }
        
        /// <summary>
        /// 遗留单号
        /// </summary>
                 
        public string PMX013
        {
            get
            {
                return this._pmx013;
            }
            set
            {
                this._pmx013 = value;
            }
        }
        
        // 
        public string PMX014
        {
            get
            {
                return this._pmx014;
            }
            set
            {
                this._pmx014 = value;
            }
        }
        
        // 
        public string PMX015
        {
            get
            {
                return this._pmx015;
            }
            set
            {
                this._pmx015 = value;
            }
        }
        
        // 
        public string PMX016
        {
            get
            {
                return this._pmx016;
            }
            set
            {
                this._pmx016 = value;
            }
        }
        
        // 
        public string PMX017
        {
            get
            {
                return this._pmx017;
            }
            set
            {
                this._pmx017 = value;
            }
        }
        
        // 
        public string PMX018
        {
            get
            {
                return this._pmx018;
            }
            set
            {
                this._pmx018 = value;
            }
        }
        
        // 
        public string PMX019
        {
            get
            {
                return this._pmx019;
            }
            set
            {
                this._pmx019 = value;
            }
        }
        
        // 
        public string PMX020
        {
            get
            {
                return this._pmx020;
            }
            set
            {
                this._pmx020 = value;
            }
        }
        
        // 
        public string PMX021
        {
            get
            {
                return this._pmx021;
            }
            set
            {
                this._pmx021 = value;
            }
        }
        
        // 
        public string PMX022
        {
            get
            {
                return this._pmx022;
            }
            set
            {
                this._pmx022 = value;
            }
        }
        
        // 
        public string PMX023
        {
            get
            {
                return this._pmx023;
            }
            set
            {
                this._pmx023 = value;
            }
        }
        
        // 
        public string PMX024
        {
            get
            {
                return this._pmx024;
            }
            set
            {
                this._pmx024 = value;
            }
        }
        
        // 
        public string PMX025
        {
            get
            {
                return this._pmx025;
            }
            set
            {
                this._pmx025 = value;
            }
        }
        
        // 
        public string PMX026
        {
            get
            {
                return this._pmx026;
            }
            set
            {
                this._pmx026 = value;
            }
        }
        
        // 
        public string PMX027
        {
            get
            {
                return this._pmx027;
            }
            set
            {
                this._pmx027 = value;
            }
        }
        
        // 
        public string PMX028
        {
            get
            {
                return this._pmx028;
            }
            set
            {
                this._pmx028 = value;
            }
        }
        
        // 
        public string PMX029
        {
            get
            {
                return this._pmx029;
            }
            set
            {
                this._pmx029 = value;
            }
        }
        
        // 
        public string PMX030
        {
            get
            {
                return this._pmx030;
            }
            set
            {
                this._pmx030 = value;
            }
        }
    }
}
