//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanAssembleDayPLEEntity
    {
        
        private int _idx;
        
        private string _ple001;
        
        private string _ple002;
        
        private string _ple003;
        
        private string _ple004;
        
        private string _ple005;
        
        private int _ple006;
        
        private int _ple007;
        
        private string _ple008;
        
        private DateTime _ple009;
        
        private string _ple010;
        
        private bool _ple011;
        
        private bool _ple012;
        
        private string _ple013;
        
        private string _ple014;
        
        private string _ple015;
        
        private string _ple016;
        
        private string _ple017;
        
        private string _ple018;
        
        private string _ple019;
        
        private string _ple020;
        
        private string _ple021;
        
        private string _ple022;
        
        private string _ple023;
        
        private string _ple024;
        
        private string _ple025;
        
        private string _ple026;
        
        private string _ple027;
        
        private string _ple028;
        
        private string _ple029;
        
        private string _ple030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PLE001
        {
            get
            {
                return this._ple001;
            }
            set
            {
                this._ple001 = value;
            }
        }

        /// <summary>
        /// 完工状态
        /// </summary>

        public string PLE002
        {
            get
            {
                return this._ple002;
            }
            set
            {
                this._ple002 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PLE003
        {
            get
            {
                return this._ple003;
            }
            set
            {
                this._ple003 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PLE004
        {
            get
            {
                return this._ple004;
            }
            set
            {
                this._ple004 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PLE005
        {
            get
            {
                return this._ple005;
            }
            set
            {
                this._ple005 = value;
            }
        }

        /// <summary>
        /// 订单数量
        /// </summary>

        public int PLE006
        {
            get
            {
                return this._ple006;
            }
            set
            {
                this._ple006 = value;
            }
        }

        /// <summary>
        /// 计划数量
        /// </summary>

        public int PLE007
        {
            get
            {
                return this._ple007;
            }
            set
            {
                this._ple007 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PLE008
        {
            get
            {
                return this._ple008;
            }
            set
            {
                this._ple008 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PLE009
        {
            get
            {
                return this._ple009;
            }
            set
            {
                this._ple009 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PLE010
        {
            get
            {
                return this._ple010;
            }
            set
            {
                this._ple010 = value;
            }
        }

        /// <summary>
        /// 完成标记
        /// </summary>

        public bool PLE011
        {
            get
            {
                return this._ple011;
            }
            set
            {
                this._ple011 = value;
            }
        }

        /// <summary>
        /// 预排
        /// </summary>

        public bool PLE012
        {
            get
            {
                return this._ple012;
            }
            set
            {
                this._ple012 = value;
            }
        }
        
        /// <summary>
        /// 遗留单号
        /// </summary>
                 
        public string PLE013
        {
            get
            {
                return this._ple013;
            }
            set
            {
                this._ple013 = value;
            }
        }
        
        // 
        public string PLE014
        {
            get
            {
                return this._ple014;
            }
            set
            {
                this._ple014 = value;
            }
        }
        
        // 
        public string PLE015
        {
            get
            {
                return this._ple015;
            }
            set
            {
                this._ple015 = value;
            }
        }
        
        // 
        public string PLE016
        {
            get
            {
                return this._ple016;
            }
            set
            {
                this._ple016 = value;
            }
        }
        
        // 
        public string PLE017
        {
            get
            {
                return this._ple017;
            }
            set
            {
                this._ple017 = value;
            }
        }
        
        // 
        public string PLE018
        {
            get
            {
                return this._ple018;
            }
            set
            {
                this._ple018 = value;
            }
        }
        
        // 
        public string PLE019
        {
            get
            {
                return this._ple019;
            }
            set
            {
                this._ple019 = value;
            }
        }
        
        // 
        public string PLE020
        {
            get
            {
                return this._ple020;
            }
            set
            {
                this._ple020 = value;
            }
        }
        
        // 
        public string PLE021
        {
            get
            {
                return this._ple021;
            }
            set
            {
                this._ple021 = value;
            }
        }
        
        // 
        public string PLE022
        {
            get
            {
                return this._ple022;
            }
            set
            {
                this._ple022 = value;
            }
        }
        
        // 
        public string PLE023
        {
            get
            {
                return this._ple023;
            }
            set
            {
                this._ple023 = value;
            }
        }
        
        // 
        public string PLE024
        {
            get
            {
                return this._ple024;
            }
            set
            {
                this._ple024 = value;
            }
        }
        
        // 
        public string PLE025
        {
            get
            {
                return this._ple025;
            }
            set
            {
                this._ple025 = value;
            }
        }
        
        // 
        public string PLE026
        {
            get
            {
                return this._ple026;
            }
            set
            {
                this._ple026 = value;
            }
        }
        
        // 
        public string PLE027
        {
            get
            {
                return this._ple027;
            }
            set
            {
                this._ple027 = value;
            }
        }
        
        // 
        public string PLE028
        {
            get
            {
                return this._ple028;
            }
            set
            {
                this._ple028 = value;
            }
        }
        
        // 
        public string PLE029
        {
            get
            {
                return this._ple029;
            }
            set
            {
                this._ple029 = value;
            }
        }
        
        // 
        public string PLE030
        {
            get
            {
                return this._ple030;
            }
            set
            {
                this._ple030 = value;
            }
        }
    }
}
