//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanMachinWorkPMWEntity
    {
        
        private int _idx;
        
        private string _pmw001;
        
        private string _pmw002;
        
        private DateTime _pmw003;
        
        private DateTime _pmw004;
        
        private bool _pmw005;
        
        private bool _pmw006;
        
        private DateTime _pmw007;
        
        private string _pmw008;
        
        private decimal _pmw009;
        
        private DateTime? _pmw010;
        
        private string _pmw011;
        
        private string _pmw012;
        
        private string _pmw013;
        
        private string _pmw014;
        
        private string _pmw015;
        
        private string _pmw016;
        
        private string _pmw017;
        
        private string _pmw018;
        
        private string _pmw019;
        
        private string _pmw020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PMW001
        {
            get
            {
                return this._pmw001;
            }
            set
            {
                this._pmw001 = value;
            }
        }

        /// <summary>
        /// 工段
        /// </summary>

        public string PMW002
        {
            get
            {
                return this._pmw002;
            }
            set
            {
                this._pmw002 = value;
            }
        }

        /// <summary>
        /// 计划日期
        /// </summary>

        public DateTime PMW003
        {
            get
            {
                return this._pmw003;
            }
            set
            {
                this._pmw003 = value;
            }
        }

        /// <summary>
        /// 下单日期
        /// </summary>

        public DateTime PMW004
        {
            get
            {
                return this._pmw004;
            }
            set
            {
                this._pmw004 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool PMW005
        {
            get
            {
                return this._pmw005;
            }
            set
            {
                this._pmw005 = value;
            }
        }

        /// <summary>
        /// 审核
        /// </summary>

        public bool PMW006
        {
            get
            {
                return this._pmw006;
            }
            set
            {
                this._pmw006 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PMW007
        {
            get
            {
                return this._pmw007;
            }
            set
            {
                this._pmw007 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PMW008
        {
            get
            {
                return this._pmw008;
            }
            set
            {
                this._pmw008 = value;
            }
        }

        /// <summary>
        /// 完成率
        /// </summary>

        public decimal PMW009
        {
            get
            {
                return this._pmw009;
            }
            set
            {
                this._pmw009 = value;
            }
        }

        /// <summary>
        /// 上工作日
        /// </summary>

        public DateTime? PMW010
        {
            get
            {
                return this._pmw010;
            }
            set
            {
                this._pmw010 = value;
            }
        }
        
        // 
        public string PMW011
        {
            get
            {
                return this._pmw011;
            }
            set
            {
                this._pmw011 = value;
            }
        }
        
        // 
        public string PMW012
        {
            get
            {
                return this._pmw012;
            }
            set
            {
                this._pmw012 = value;
            }
        }
        
        // 
        public string PMW013
        {
            get
            {
                return this._pmw013;
            }
            set
            {
                this._pmw013 = value;
            }
        }
        
        // 
        public string PMW014
        {
            get
            {
                return this._pmw014;
            }
            set
            {
                this._pmw014 = value;
            }
        }
        
        // 
        public string PMW015
        {
            get
            {
                return this._pmw015;
            }
            set
            {
                this._pmw015 = value;
            }
        }
        
        // 
        public string PMW016
        {
            get
            {
                return this._pmw016;
            }
            set
            {
                this._pmw016 = value;
            }
        }
        
        // 
        public string PMW017
        {
            get
            {
                return this._pmw017;
            }
            set
            {
                this._pmw017 = value;
            }
        }
        
        // 
        public string PMW018
        {
            get
            {
                return this._pmw018;
            }
            set
            {
                this._pmw018 = value;
            }
        }
        
        // 
        public string PMW019
        {
            get
            {
                return this._pmw019;
            }
            set
            {
                this._pmw019 = value;
            }
        }
        
        // 
        public string PMW020
        {
            get
            {
                return this._pmw020;
            }
            set
            {
                this._pmw020 = value;
            }
        }
    }
}
