//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanCutCUTEntity
    {
        private int _idx;
        
        private string _cut001;
        
        private DateTime _cut002;
        
        private DateTime _cut003;
        
        private DateTime _cut004;
        
        private DateTime _cut005;
        
        private string _cut006;
        
        private bool _cut007;
        
        private bool _cut008;
        
        private string _cut009;
        
        private string _cut010;
        
        private string _cut011;
        
        private string _cut012;
        
        private string _cut013;
        
        private string _cut014;
        
        private string _cut015;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 生产批号
        /// </summary>

        public string CUT001
        {
            get
            {
                return this._cut001;
            }
            set
            {
                this._cut001 = value;
            }
        }

        /// <summary>
        /// 下单日期
        /// </summary>

        public DateTime CUT002
        {
            get
            {
                return this._cut002;
            }
            set
            {
                this._cut002 = value;
            }
        }

        /// <summary>
        /// 下单生产开始日期
        /// </summary>

        public DateTime CUT003
        {
            get
            {
                return this._cut003;
            }
            set
            {
                this._cut003 = value;
            }
        }

        /// <summary>
        /// 下单生产结束日期
        /// </summary>

        public DateTime CUT004
        {
            get
            {
                return this._cut004;
            }
            set
            {
                this._cut004 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime CUT005
        {
            get
            {
                return this._cut005;
            }
            set
            {
                this._cut005 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string CUT006
        {
            get
            {
                return this._cut006;
            }
            set
            {
                this._cut006 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool CUT007
        {
            get
            {
                return this._cut007;
            }
            set
            {
                this._cut007 = value;
            }
        }
        
        /// <summary>
        /// 审核
        /// </summary>
                 
        public bool CUT008
        {
            get
            {
                return this._cut008;
            }
            set
            {
                this._cut008 = value;
            }
        }
        
        // 
        public string CUT009
        {
            get
            {
                return this._cut009;
            }
            set
            {
                this._cut009 = value;
            }
        }
        
        // 
        public string CUT010
        {
            get
            {
                return this._cut010;
            }
            set
            {
                this._cut010 = value;
            }
        }
        
        // 
        public string CUT011
        {
            get
            {
                return this._cut011;
            }
            set
            {
                this._cut011 = value;
            }
        }
        
        // 
        public string CUT012
        {
            get
            {
                return this._cut012;
            }
            set
            {
                this._cut012 = value;
            }
        }
        
        // 
        public string CUT013
        {
            get
            {
                return this._cut013;
            }
            set
            {
                this._cut013 = value;
            }
        }
        
        // 
        public string CUT014
        {
            get
            {
                return this._cut014;
            }
            set
            {
                this._cut014 = value;
            }
        }
        
        // 
        public string CUT015
        {
            get
            {
                return this._cut015;
            }
            set
            {
                this._cut015 = value;
            }
        }
    }
}
