//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanAssembleWeekDailyEntity
    {
        
        private int _idx;
        
        private string _plc001;
        
        private string _plc002;
        
        private string _plc003;
        
        private string _plc004;
        
        private string _plc005;
        
        private int _plc006;
        
        private int _plc007;
        
        private bool _plc008;
        
        private int _plc009;
        
        private int _plc010;
        
        private int _plc011;
        
        private DateTime _plc012;
        
        private DateTime _plc013;
        
        private string _plc014;
        
        private bool _plc015;
        
        private string _plc016;
        
        private string _plc017;
        
        private string _plc018;
        
        private string _plc019;
        
        private string _plc020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PLC001
        {
            get
            {
                return this._plc001;
            }
            set
            {
                this._plc001 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PLC002
        {
            get
            {
                return this._plc002;
            }
            set
            {
                this._plc002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PLC003
        {
            get
            {
                return this._plc003;
            }
            set
            {
                this._plc003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PLC004
        {
            get
            {
                return this._plc004;
            }
            set
            {
                this._plc004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PLC005
        {
            get
            {
                return this._plc005;
            }
            set
            {
                this._plc005 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int PLC006
        {
            get
            {
                return this._plc006;
            }
            set
            {
                this._plc006 = value;
            }
        }

        /// <summary>
        /// 报工数量
        /// </summary>

        public int PLC007
        {
            get
            {
                return this._plc007;
            }
            set
            {
                this._plc007 = value;
            }
        }

        /// <summary>
        /// 预排报工
        /// </summary>

        public bool PLC008
        {
            get
            {
                return this._plc008;
            }
            set
            {
                this._plc008 = value;
            }
        }
        
        // 
        public int PLC009
        {
            get
            {
                return this._plc009;
            }
            set
            {
                this._plc009 = value;
            }
        }
        
        // 
        public int PLC010
        {
            get
            {
                return this._plc010;
            }
            set
            {
                this._plc010 = value;
            }
        }
        
        // 
        public int PLC011
        {
            get
            {
                return this._plc011;
            }
            set
            {
                this._plc011 = value;
            }
        }

        /// <summary>
        /// 报工时间
        /// </summary>

        public DateTime PLC012
        {
            get
            {
                return this._plc012;
            }
            set
            {
                this._plc012 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PLC013
        {
            get
            {
                return this._plc013;
            }
            set
            {
                this._plc013 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PLC014
        {
            get
            {
                return this._plc014;
            }
            set
            {
                this._plc014 = value;
            }
        }
        
        // 
        public bool PLC015
        {
            get
            {
                return this._plc015;
            }
            set
            {
                this._plc015 = value;
            }
        }
        
        // 
        public string PLC016
        {
            get
            {
                return this._plc016;
            }
            set
            {
                this._plc016 = value;
            }
        }
        
        // 
        public string PLC017
        {
            get
            {
                return this._plc017;
            }
            set
            {
                this._plc017 = value;
            }
        }
        
        // 
        public string PLC018
        {
            get
            {
                return this._plc018;
            }
            set
            {
                this._plc018 = value;
            }
        }
        
        // 
        public string PLC019
        {
            get
            {
                return this._plc019;
            }
            set
            {
                this._plc019 = value;
            }
        }
        
        // 
        public string PLC020
        {
            get
            {
                return this._plc020;
            }
            set
            {
                this._plc020 = value;
            }
        }
    }
}
