//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanStockWorkPSXEntity
    {
        
        private int _idx;
        
        private string _psx001;
        
        private string _psx002;
        
        private string _psx003;
        
        private string _psx004;
        
        private string _psx005;
        
        private int _psx006;
        
        private int _psx007;
        
        private string _psx008;
        
        private DateTime _psx009;
        
        private string _psx010;
        
        private bool _psx011;
        
        private bool _psx012;
        
        private string _psx013;
        
        private string _psx014;
        
        private string _psx015;
        
        private string _psx016;
        
        private string _psx017;
        
        private string _psx018;
        
        private string _psx019;
        
        private string _psx020;
        
        private string _psx021;
        
        private string _psx022;
        
        private string _psx023;
        
        private string _psx024;
        
        private string _psx025;
        
        private string _psx026;
        
        private string _psx027;
        
        private string _psx028;
        
        private string _psx029;
        
        private string _psx030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PSX001
        {
            get
            {
                return this._psx001;
            }
            set
            {
                this._psx001 = value;
            }
        }

        /// <summary>
        /// 完工状态
        /// </summary>

        public string PSX002
        {
            get
            {
                return this._psx002;
            }
            set
            {
                this._psx002 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PSX003
        {
            get
            {
                return this._psx003;
            }
            set
            {
                this._psx003 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PSX004
        {
            get
            {
                return this._psx004;
            }
            set
            {
                this._psx004 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PSX005
        {
            get
            {
                return this._psx005;
            }
            set
            {
                this._psx005 = value;
            }
        }

        /// <summary>
        /// 订单数量
        /// </summary>

        public int PSX006
        {
            get
            {
                return this._psx006;
            }
            set
            {
                this._psx006 = value;
            }
        }

        /// <summary>
        /// 计划数量
        /// </summary>

        public int PSX007
        {
            get
            {
                return this._psx007;
            }
            set
            {
                this._psx007 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PSX008
        {
            get
            {
                return this._psx008;
            }
            set
            {
                this._psx008 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PSX009
        {
            get
            {
                return this._psx009;
            }
            set
            {
                this._psx009 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PSX010
        {
            get
            {
                return this._psx010;
            }
            set
            {
                this._psx010 = value;
            }
        }
        
        /// <summary>
        /// 完成标记
        /// </summary>
                 
        public bool PSX011
        {
            get
            {
                return this._psx011;
            }
            set
            {
                this._psx011 = value;
            }
        }
        
        /// <summary>
        /// 预排
        /// </summary>
                 
        public bool PSX012
        {
            get
            {
                return this._psx012;
            }
            set
            {
                this._psx012 = value;
            }
        }
        
        /// <summary>
        /// 遗留单号
        /// </summary>         
        public string PSX013
        {
            get
            {
                return this._psx013;
            }
            set
            {
                this._psx013 = value;
            }
        }
        
        // 
        public string PSX014
        {
            get
            {
                return this._psx014;
            }
            set
            {
                this._psx014 = value;
            }
        }
        
        // 
        public string PSX015
        {
            get
            {
                return this._psx015;
            }
            set
            {
                this._psx015 = value;
            }
        }
        
        // 
        public string PSX016
        {
            get
            {
                return this._psx016;
            }
            set
            {
                this._psx016 = value;
            }
        }
        
        // 
        public string PSX017
        {
            get
            {
                return this._psx017;
            }
            set
            {
                this._psx017 = value;
            }
        }
        
        // 
        public string PSX018
        {
            get
            {
                return this._psx018;
            }
            set
            {
                this._psx018 = value;
            }
        }
        
        // 
        public string PSX019
        {
            get
            {
                return this._psx019;
            }
            set
            {
                this._psx019 = value;
            }
        }
        
        // 
        public string PSX020
        {
            get
            {
                return this._psx020;
            }
            set
            {
                this._psx020 = value;
            }
        }
        
        // 
        public string PSX021
        {
            get
            {
                return this._psx021;
            }
            set
            {
                this._psx021 = value;
            }
        }
        
        // 
        public string PSX022
        {
            get
            {
                return this._psx022;
            }
            set
            {
                this._psx022 = value;
            }
        }
        
        // 
        public string PSX023
        {
            get
            {
                return this._psx023;
            }
            set
            {
                this._psx023 = value;
            }
        }
        
        // 
        public string PSX024
        {
            get
            {
                return this._psx024;
            }
            set
            {
                this._psx024 = value;
            }
        }
        
        // 
        public string PSX025
        {
            get
            {
                return this._psx025;
            }
            set
            {
                this._psx025 = value;
            }
        }
        
        // 
        public string PSX026
        {
            get
            {
                return this._psx026;
            }
            set
            {
                this._psx026 = value;
            }
        }
        
        // 
        public string PSX027
        {
            get
            {
                return this._psx027;
            }
            set
            {
                this._psx027 = value;
            }
        }
        
        // 
        public string PSX028
        {
            get
            {
                return this._psx028;
            }
            set
            {
                this._psx028 = value;
            }
        }
        
        // 
        public string PSX029
        {
            get
            {
                return this._psx029;
            }
            set
            {
                this._psx029 = value;
            }
        }
        
        // 
        public string PSX030
        {
            get
            {
                return this._psx030;
            }
            set
            {
                this._psx030 = value;
            }
        }
    }
}
