//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanStockPLSEntity
    {
        
        private int _idx;
        
        private string _pls001;
        
        private string _pls002;
        
        private DateTime _pls003;
        
        private DateTime _pls004;
        
        private DateTime _pls005;
        
        private DateTime _pls006;
        
        private string _pls007;
        
        private bool _pls008;
        
        private bool _pls009;
        
        private string _pls010;
        
        private string _pls011;
        
        private string _pls012;
        
        private string _pls013;
        
        private string _pls014;
        
        private string _pls015;
        
        private string _pls016;
        
        private string _pls017;
        
        private string _pls018;
        
        private string _pls019;
        
        private string _pls020;
        
        private string _pls021;
        
        private string _pls022;
        
        private string _pls023;
        
        private string _pls024;
        
        private string _pls025;
        
        private string _pls026;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PLS001
        {
            get
            {
                return this._pls001;
            }
            set
            {
                this._pls001 = value;
            }
        }

        /// <summary>
        /// 周次
        /// </summary>

        public string PLS002
        {
            get
            {
                return this._pls002;
            }
            set
            {
                this._pls002 = value;
            }
        }

        /// <summary>
        /// 下单日期
        /// </summary>

        public DateTime PLS003
        {
            get
            {
                return this._pls003;
            }
            set
            {
                this._pls003 = value;
            }
        }

        /// <summary>
        /// 生产开始日期
        /// </summary>

        public DateTime PLS004
        {
            get
            {
                return this._pls004;
            }
            set
            {
                this._pls004 = value;
            }
        }

        /// <summary>
        /// 生产结束日期
        /// </summary>

        public DateTime PLS005
        {
            get
            {
                return this._pls005;
            }
            set
            {
                this._pls005 = value;
            }
        }

        /// <summary>
        /// 日期
        /// </summary>

        public DateTime PLS006
        {
            get
            {
                return this._pls006;
            }
            set
            {
                this._pls006 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PLS007
        {
            get
            {
                return this._pls007;
            }
            set
            {
                this._pls007 = value;
            }
        }
        
        /// <summary>
        /// 注销
        /// </summary>
                 
        public bool PLS008
        {
            get
            {
                return this._pls008;
            }
            set
            {
                this._pls008 = value;
            }
        }
        
        /// <summary>
        /// 审核
        /// </summary>
                 
        public bool PLS009
        {
            get
            {
                return this._pls009;
            }
            set
            {
                this._pls009 = value;
            }
        }
        
        // 
        public string PLS010
        {
            get
            {
                return this._pls010;
            }
            set
            {
                this._pls010 = value;
            }
        }
        
        // 
        public string PLS011
        {
            get
            {
                return this._pls011;
            }
            set
            {
                this._pls011 = value;
            }
        }
        
        // 
        public string PLS012
        {
            get
            {
                return this._pls012;
            }
            set
            {
                this._pls012 = value;
            }
        }
        
        // 
        public string PLS013
        {
            get
            {
                return this._pls013;
            }
            set
            {
                this._pls013 = value;
            }
        }
        
        // 
        public string PLS014
        {
            get
            {
                return this._pls014;
            }
            set
            {
                this._pls014 = value;
            }
        }
        
        // 
        public string PLS015
        {
            get
            {
                return this._pls015;
            }
            set
            {
                this._pls015 = value;
            }
        }
        
        // 
        public string PLS016
        {
            get
            {
                return this._pls016;
            }
            set
            {
                this._pls016 = value;
            }
        }
        
        // 
        public string PLS017
        {
            get
            {
                return this._pls017;
            }
            set
            {
                this._pls017 = value;
            }
        }
        
        // 
        public string PLS018
        {
            get
            {
                return this._pls018;
            }
            set
            {
                this._pls018 = value;
            }
        }
        
        // 
        public string PLS019
        {
            get
            {
                return this._pls019;
            }
            set
            {
                this._pls019 = value;
            }
        }
        
        // 
        public string PLS020
        {
            get
            {
                return this._pls020;
            }
            set
            {
                this._pls020 = value;
            }
        }
        
        // 
        public string PLS021
        {
            get
            {
                return this._pls021;
            }
            set
            {
                this._pls021 = value;
            }
        }
        
        // 
        public string PLS022
        {
            get
            {
                return this._pls022;
            }
            set
            {
                this._pls022 = value;
            }
        }
        
        // 
        public string PLS023
        {
            get
            {
                return this._pls023;
            }
            set
            {
                this._pls023 = value;
            }
        }
        
        // 
        public string PLS024
        {
            get
            {
                return this._pls024;
            }
            set
            {
                this._pls024 = value;
            }
        }
        
        // 
        public string PLS025
        {
            get
            {
                return this._pls025;
            }
            set
            {
                this._pls025 = value;
            }
        }
        
        // 
        public string PLS026
        {
            get
            {
                return this._pls026;
            }
            set
            {
                this._pls026 = value;
            }
        }
    }
}
