//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanMachinDayDailyWorkEntity
    {
        
        private int _idx;
        
        private string _pmy001;
        
        private string _pmy002;
        
        private string _pmy003;
        
        private string _pmy004;
        
        private string _pmy005;
        
        private int _pmy006;
        
        private int _pmy007;
        
        private int _pmy008;
        
        private int _pmy009;
        
        private int _pmy010;
        
        private int _pmy011;
        
        private DateTime _pmy012;
        
        private DateTime _pmy013;
        
        private string _pmy014;
        
        private bool _pmy015;
        
        private string _pmy016;
        
        private string _pmy017;
        
        private string _pmy018;
        
        private string _pmy019;
        
        private string _pmy020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PMY001
        {
            get
            {
                return this._pmy001;
            }
            set
            {
                this._pmy001 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PMY002
        {
            get
            {
                return this._pmy002;
            }
            set
            {
                this._pmy002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PMY003
        {
            get
            {
                return this._pmy003;
            }
            set
            {
                this._pmy003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PMY004
        {
            get
            {
                return this._pmy004;
            }
            set
            {
                this._pmy004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PMY005
        {
            get
            {
                return this._pmy005;
            }
            set
            {
                this._pmy005 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int PMY006
        {
            get
            {
                return this._pmy006;
            }
            set
            {
                this._pmy006 = value;
            }
        }

        /// <summary>
        /// 机加工中心数量
        /// </summary>

        public int PMY007
        {
            get
            {
                return this._pmy007;
            }
            set
            {
                this._pmy007 = value;
            }
        }

        /// <summary>
        /// 开榫数量
        /// </summary>

        public int PMY008
        {
            get
            {
                return this._pmy008;
            }
            set
            {
                this._pmy008 = value;
            }
        }

        /// <summary>
        /// 倒圆数量
        /// </summary>

        public int PMY009
        {
            get
            {
                return this._pmy009;
            }
            set
            {
                this._pmy009 = value;
            }
        }
        
        // 
        public int PMY010
        {
            get
            {
                return this._pmy010;
            }
            set
            {
                this._pmy010 = value;
            }
        }
        
        // 
        public int PMY011
        {
            get
            {
                return this._pmy011;
            }
            set
            {
                this._pmy011 = value;
            }
        }

        /// <summary>
        /// 报工时间
        /// </summary>

        public DateTime PMY012
        {
            get
            {
                return this._pmy012;
            }
            set
            {
                this._pmy012 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PMY013
        {
            get
            {
                return this._pmy013;
            }
            set
            {
                this._pmy013 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PMY014
        {
            get
            {
                return this._pmy014;
            }
            set
            {
                this._pmy014 = value;
            }
        }

        /// <summary>
        /// 计划报工
        /// </summary>

        public bool PMY015
        {
            get
            {
                return this._pmy015;
            }
            set
            {
                this._pmy015 = value;
            }
        }
        
        /// <summary>
        /// 日计划单号
        /// </summary>
                 
        public string PMY016
        {
            get
            {
                return this._pmy016;
            }
            set
            {
                this._pmy016 = value;
            }
        }
        
        /// <summary>
        /// 遗留单号
        /// </summary>
                 
        public string PMY017
        {
            get
            {
                return this._pmy017;
            }
            set
            {
                this._pmy017 = value;
            }
        }
        
        // 
        public string PMY018
        {
            get
            {
                return this._pmy018;
            }
            set
            {
                this._pmy018 = value;
            }
        }
        
        // 
        public string PMY019
        {
            get
            {
                return this._pmy019;
            }
            set
            {
                this._pmy019 = value;
            }
        }
        
        // 
        public string PMY020
        {
            get
            {
                return this._pmy020;
            }
            set
            {
                this._pmy020 = value;
            }
        }
    }
}
