//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanAssembleWeekPLAEntity
    {
        
        private int _idx;
        
        private string _pla001;
        
        private DateTime _pla002;
        
        private DateTime _pla003;
        
        private DateTime _pla004;
        
        private DateTime _pla005;
        
        private string _pla006;
        
        private bool _pla007;
        
        private bool _pla008;
        
        private string _pla009;
        
        private string _pla010;
        
        private string _pla011;
        
        private string _pla012;
        
        private string _pla013;
        
        private string _pla014;
        
        private string _pla015;
        
        private string _pla016;
        
        private string _pla017;
        
        private string _pla018;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PLA001
        {
            get
            {
                return this._pla001;
            }
            set
            {
                this._pla001 = value;
            }
        }

        /// <summary>
        /// 录入日期
        /// </summary>

        public DateTime PLA002
        {
            get
            {
                return this._pla002;
            }
            set
            {
                this._pla002 = value;
            }
        }

        /// <summary>
        /// 下单日期
        /// </summary>

        public DateTime PLA003
        {
            get
            {
                return this._pla003;
            }
            set
            {
                this._pla003 = value;
            }
        }

        /// <summary>
        /// 生产周期开始日期
        /// </summary>

        public DateTime PLA004
        {
            get
            {
                return this._pla004;
            }
            set
            {
                this._pla004 = value;
            }
        }

        /// <summary>
        /// 生产周期结束日期
        /// </summary>

        public DateTime PLA005
        {
            get
            {
                return this._pla005;
            }
            set
            {
                this._pla005 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PLA006
        {
            get
            {
                return this._pla006;
            }
            set
            {
                this._pla006 = value;
            }
        }

        /// <summary>
        /// 审核
        /// </summary>

        public bool PLA007
        {
            get
            {
                return this._pla007;
            }
            set
            {
                this._pla007 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool PLA008
        {
            get
            {
                return this._pla008;
            }
            set
            {
                this._pla008 = value;
            }
        }

        /// <summary>
        /// 周次
        /// </summary>

        public string PLA009
        {
            get
            {
                return this._pla009;
            }
            set
            {
                this._pla009 = value;
            }
        }
        
        // 
        public string PLA010
        {
            get
            {
                return this._pla010;
            }
            set
            {
                this._pla010 = value;
            }
        }
        
        // 
        public string PLA011
        {
            get
            {
                return this._pla011;
            }
            set
            {
                this._pla011 = value;
            }
        }
        
        // 
        public string PLA012
        {
            get
            {
                return this._pla012;
            }
            set
            {
                this._pla012 = value;
            }
        }
        
        // 
        public string PLA013
        {
            get
            {
                return this._pla013;
            }
            set
            {
                this._pla013 = value;
            }
        }
        
        // 
        public string PLA014
        {
            get
            {
                return this._pla014;
            }
            set
            {
                this._pla014 = value;
            }
        }
        
        // 
        public string PLA015
        {
            get
            {
                return this._pla015;
            }
            set
            {
                this._pla015 = value;
            }
        }
        
        // 
        public string PLA016
        {
            get
            {
                return this._pla016;
            }
            set
            {
                this._pla016 = value;
            }
        }
        
        // 
        public string PLA017
        {
            get
            {
                return this._pla017;
            }
            set
            {
                this._pla017 = value;
            }
        }
        
        // 
        public string PLA018
        {
            get
            {
                return this._pla018;
            }
            set
            {
                this._pla018 = value;
            }
        }
    }
}
