//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanStockPLTEntity
    {
        
        private int _idx;
        
        private string _plt001;
        
        private string _plt002;
        
        private string _plt003;
        
        private string _plt004;
        
        private string _plt005;
        
        private string _plt006;
        
        private DateTime? _plt007;
        
        private string _plt008;
        
        private DateTime? _plt009;
        
        private string _plt010;
        
        private bool _plt011;
        
        private int _plt012;
        
        private bool _plt013;
        
        private string _plt014;
        
        private string _plt015;
        
        private string _plt016;
        
        private string _plt017;
        
        private string _plt018;
        
        private string _plt019;
        
        private string _plt020;
        
        private string _plt021;
        
        private string _plt022;
        
        private string _plt023;
        
        private string _plt024;
        
        private string _plt025;
        
        private string _plt026;
        
        private string _plt027;
        
        private string _plt028;
        
        private string _plt029;
        
        private string _plt030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PLT001
        {
            get
            {
                return this._plt001;
            }
            set
            {
                this._plt001 = value;
            }
        }

        /// <summary>
        /// 遗留单号
        /// </summary>

        public string PLT002
        {
            get
            {
                return this._plt002;
            }
            set
            {
                this._plt002 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PLT003
        {
            get
            {
                return this._plt003;
            }
            set
            {
                this._plt003 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PLT004
        {
            get
            {
                return this._plt004;
            }
            set
            {
                this._plt004 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PLT005
        {
            get
            {
                return this._plt005;
            }
            set
            {
                this._plt005 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PLT006
        {
            get
            {
                return this._plt006;
            }
            set
            {
                this._plt006 = value;
            }
        }

        /// <summary>
        /// 备料计划完成时间
        /// </summary>

        public DateTime? PLT007
        {
            get
            {
                return this._plt007;
            }
            set
            {
                this._plt007 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PLT008
        {
            get
            {
                return this._plt008;
            }
            set
            {
                this._plt008 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime? PLT009
        {
            get
            {
                return this._plt009;
            }
            set
            {
                this._plt009 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PLT010
        {
            get
            {
                return this._plt010;
            }
            set
            {
                this._plt010 = value;
            }
        }
        
        /// <summary>
        /// 是否完成
        /// </summary>
                 
        public bool PLT011
        {
            get
            {
                return this._plt011;
            }
            set
            {
                this._plt011 = value;
            }
        }
        
        /// <summary>
        /// 生产数量
        /// </summary>
                 
        public int PLT012
        {
            get
            {
                return this._plt012;
            }
            set
            {
                this._plt012 = value;
            }
        }
        
        /// <summary>
        /// 预排
        /// </summary>
                 
        public bool PLT013
        {
            get
            {
                return this._plt013;
            }
            set
            {
                this._plt013 = value;
            }
        }
        
        // 
        public string PLT014
        {
            get
            {
                return this._plt014;
            }
            set
            {
                this._plt014 = value;
            }
        }
        
        // 
        public string PLT015
        {
            get
            {
                return this._plt015;
            }
            set
            {
                this._plt015 = value;
            }
        }
        
        // 
        public string PLT016
        {
            get
            {
                return this._plt016;
            }
            set
            {
                this._plt016 = value;
            }
        }
        
        // 
        public string PLT017
        {
            get
            {
                return this._plt017;
            }
            set
            {
                this._plt017 = value;
            }
        }
        
        // 
        public string PLT018
        {
            get
            {
                return this._plt018;
            }
            set
            {
                this._plt018 = value;
            }
        }
        
        // 
        public string PLT019
        {
            get
            {
                return this._plt019;
            }
            set
            {
                this._plt019 = value;
            }
        }
        
        // 
        public string PLT020
        {
            get
            {
                return this._plt020;
            }
            set
            {
                this._plt020 = value;
            }
        }
        
        // 
        public string PLT021
        {
            get
            {
                return this._plt021;
            }
            set
            {
                this._plt021 = value;
            }
        }
        
        // 
        public string PLT022
        {
            get
            {
                return this._plt022;
            }
            set
            {
                this._plt022 = value;
            }
        }
        
        // 
        public string PLT023
        {
            get
            {
                return this._plt023;
            }
            set
            {
                this._plt023 = value;
            }
        }
        
        // 
        public string PLT024
        {
            get
            {
                return this._plt024;
            }
            set
            {
                this._plt024 = value;
            }
        }
        
        // 
        public string PLT025
        {
            get
            {
                return this._plt025;
            }
            set
            {
                this._plt025 = value;
            }
        }
        
        // 
        public string PLT026
        {
            get
            {
                return this._plt026;
            }
            set
            {
                this._plt026 = value;
            }
        }
        
        // 
        public string PLT027
        {
            get
            {
                return this._plt027;
            }
            set
            {
                this._plt027 = value;
            }
        }
        
        // 
        public string PLT028
        {
            get
            {
                return this._plt028;
            }
            set
            {
                this._plt028 = value;
            }
        }
        
        // 
        public string PLT029
        {
            get
            {
                return this._plt029;
            }
            set
            {
                this._plt029 = value;
            }
        }
        
        // 
        public string PLT030
        {
            get
            {
                return this._plt030;
            }
            set
            {
                this._plt030 = value;
            }
        }
    }
}
