//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class PlanStockDailyWeekEntity
    {
        
        private int _idx;
        
        private string _pdk001;
        
        private string _pdk002;
        
        private string _pdk003;
        
        private string _pdk004;
        
        private string _pdk005;
        
        private int _pdk006;
        
        private int _pdk007;
        
        private bool _pdk008;
        
        private string _pdk009;
        
        private int _pdk010;
        
        private int _pdk011;
        
        private DateTime _pdk012;
        
        private DateTime _pdk013;
        
        private string _pdk014;
        
        private string _pdk015;
        
        private string _pdk016;
        
        private string _pdk017;
        
        private string _pdk018;
        
        private string _pdk019;
        
        private string _pdk020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PDK001
        {
            get
            {
                return this._pdk001;
            }
            set
            {
                this._pdk001 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>
        
        public string PDK002
        {
            get
            {
                return this._pdk002;
            }
            set
            {
                this._pdk002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PDK003
        {
            get
            {
                return this._pdk003;
            }
            set
            {
                this._pdk003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PDK004
        {
            get
            {
                return this._pdk004;
            }
            set
            {
                this._pdk004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PDK005
        {
            get
            {
                return this._pdk005;
            }
            set
            {
                this._pdk005 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int PDK006
        {
            get
            {
                return this._pdk006;
            }
            set
            {
                this._pdk006 = value;
            }
        }

        /// <summary>
        /// 报工数量
        /// </summary>

        public int PDK007
        {
            get
            {
                return this._pdk007;
            }
            set
            {
                this._pdk007 = value;
            }
        }

        /// <summary>
        /// 计划报工
        /// </summary>

        public bool PDK008
        {
            get
            {
                return this._pdk008;
            }
            set
            {
                this._pdk008 = value;
            }
        }

        /// <summary>
        /// 周计划单号
        /// </summary>

        public string PDK009
        {
            get
            {
                return this._pdk009;
            }
            set
            {
                this._pdk009 = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>

        public int PDK010
        {
            get
            {
                return this._pdk010;
            }
            set
            {
                this._pdk010 = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>

        public int PDK011
        {
            get
            {
                return this._pdk011;
            }
            set
            {
                this._pdk011 = value;
            }
        }

        /// <summary>
        /// 报工时间
        /// </summary>

        public DateTime PDK012
        {
            get
            {
                return this._pdk012;
            }
            set
            {
                this._pdk012 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PDK013
        {
            get
            {
                return this._pdk013;
            }
            set
            {
                this._pdk013 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PDK014
        {
            get
            {
                return this._pdk014;
            }
            set
            {
                this._pdk014 = value;
            }
        }
        
        // 
        public string PDK015
        {
            get
            {
                return this._pdk015;
            }
            set
            {
                this._pdk015 = value;
            }
        }
        
        /// <summary>
        /// 周计划单号
        /// </summary>
                 
        public string PDK016
        {
            get
            {
                return this._pdk016;
            }
            set
            {
                this._pdk016 = value;
            }
        }
        
        // 
        public string PDK017
        {
            get
            {
                return this._pdk017;
            }
            set
            {
                this._pdk017 = value;
            }
        }
        
        // 
        public string PDK018
        {
            get
            {
                return this._pdk018;
            }
            set
            {
                this._pdk018 = value;
            }
        }
        
        // 
        public string PDK019
        {
            get
            {
                return this._pdk019;
            }
            set
            {
                this._pdk019 = value;
            }
        }
        
        // 
        public string PDK020
        {
            get
            {
                return this._pdk020;
            }
            set
            {
                this._pdk020 = value;
            }
        }
    }
}
