//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProductScheduleEntity
    {
        
        private int _idx;
        
        private string _prs001;
        
        private string _prs002;
        
        private string _prs003;
        
        private string _prs004;
        
        private DateTime _prs005;
        
        private DateTime _prs006;
        
        private DateTime _prs007;
        
        private DateTime _prs008;
        
        private DateTime _prs009;
        
        private DateTime _prs010;
        
        private DateTime _prs011;
        
        private int _prs012;
        
        private DateTime _prs013;
        
        private int _prs014;
        
        private DateTime _prs015;
        
        private int _prs016;
        
        private DateTime _prs017;
        
        private int _prs018;
        
        private DateTime _prs019;
        
        private int _prs020;
        
        private DateTime _prs021;
        
        private int _prs022;
        
        private DateTime _prs023;
        
        private int _prs024;
        
        private DateTime _prs025;
        
        private string _prs026;
        
        private DateTime _prs027;
        
        private string _prs028;
        
        private int _prs029;
        
        private bool _prs030;
        
        private DateTime? _prs031;
        
        private string _prs032;
        
        private string _prs033;
        
        private string _prs034;
        
        private string _prs035;
        
        private string _prs036;
        
        private string _prs037;
        
        private string _prs038;
        
        private string _prs039;
        
        private string _prs040;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PRS001
        {
            get
            {
                return this._prs001;
            }
            set
            {
                this._prs001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PRS002
        {
            get
            {
                return this._prs002;
            }
            set
            {
                this._prs002 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PRS003
        {
            get
            {
                return this._prs003;
            }
            set
            {
                this._prs003 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PRS004
        {
            get
            {
                return this._prs004;
            }
            set
            {
                this._prs004 = value;
            }
        }

        /// <summary>
        /// 排单时间
        /// </summary>

        public DateTime PRS005
        {
            get
            {
                return this._prs005;
            }
            set
            {
                this._prs005 = value;
            }
        }

        /// <summary>
        /// 上线时间
        /// </summary>

        public DateTime PRS006
        {
            get
            {
                return this._prs006;
            }
            set
            {
                this._prs006 = value;
            }
        }

        /// <summary>
        /// 备料计划完成时间
        /// </summary>

        public DateTime PRS007
        {
            get
            {
                return this._prs007;
            }
            set
            {
                this._prs007 = value;
            }
        }

        /// <summary>
        /// 备料完成时间
        /// </summary>

        public DateTime PRS008
        {
            get
            {
                return this._prs008;
            }
            set
            {
                this._prs008 = value;
            }
        }

        /// <summary>
        /// 机加工计划完成时间
        /// </summary>

        public DateTime PRS009
        {
            get
            {
                return this._prs009;
            }
            set
            {
                this._prs009 = value;
            }
        }

        /// <summary>
        /// 机加工倒员完成时间
        /// </summary>

        public DateTime PRS010
        {
            get
            {
                return this._prs010;
            }
            set
            {
                this._prs010 = value;
            }
        }

        /// <summary>
        /// 组装计划完成时间
        /// </summary>

        public DateTime PRS011
        {
            get
            {
                return this._prs011;
            }
            set
            {
                this._prs011 = value;
            }
        }

        /// <summary>
        /// 组装完成数量
        /// </summary>
        public int PRS012
        {
            get
            {
                return this._prs012;
            }
            set
            {
                this._prs012 = value;
            }
        }

        /// <summary>
        /// 组装实际完成时间
        /// </summary>

        public DateTime PRS013
        {
            get
            {
                return this._prs013;
            }
            set
            {
                this._prs013 = value;
            }
        }

        /// <summary>
        /// 白坯完成数量
        /// </summary>

        public int PRS014
        {
            get
            {
                return this._prs014;
            }
            set
            {
                this._prs014 = value;
            }
        }

        /// <summary>
        /// 白坯实际完成时间
        /// </summary>

        public DateTime PRS015
        {
            get
            {
                return this._prs015;
            }
            set
            {
                this._prs015 = value;
            }
        }

        /// <summary>
        /// 油漆底漆完成数量
        /// </summary>

        public int PRS016
        {
            get
            {
                return this._prs016;
            }
            set
            {
                this._prs016 = value;
            }
        }

        /// <summary>
        /// 油漆底漆完成日期
        /// </summary>

        public DateTime PRS017
        {
            get
            {
                return this._prs017;
            }
            set
            {
                this._prs017 = value;
            }
        }

        /// <summary>
        /// 油漆油磨完成数量
        /// </summary>

        public int PRS018
        {
            get
            {
                return this._prs018;
            }
            set
            {
                this._prs018 = value;
            }
        }

        /// <summary>
        /// 油漆油磨完成日期
        /// </summary>

        public DateTime PRS019
        {
            get
            {
                return this._prs019;
            }
            set
            {
                this._prs019 = value;
            }
        }

        /// <summary>
        /// 油漆修色完成数量
        /// </summary>

        public int PRS020
        {
            get
            {
                return this._prs020;
            }
            set
            {
                this._prs020 = value;
            }
        }

        /// <summary>
        /// 油漆修色完工日期
        /// </summary>

        public DateTime PRS021
        {
            get
            {
                return this._prs021;
            }
            set
            {
                this._prs021 = value;
            }
        }

        /// <summary>
        /// 油漆面漆完成数量
        /// </summary>

        public int PRS022
        {
            get
            {
                return this._prs022;
            }
            set
            {
                this._prs022 = value;
            }
        }

        /// <summary>
        /// 油漆面漆完成时间
        /// </summary>

        public DateTime PRS023
        {
            get
            {
                return this._prs023;
            }
            set
            {
                this._prs023 = value;
            }
        }

        /// <summary>
        /// 包装完成数量
        /// </summary>

        public int PRS024
        {
            get
            {
                return this._prs024;
            }
            set
            {
                this._prs024 = value;
            }
        }

        /// <summary>
        /// 包装完成时间
        /// </summary>

        public DateTime PRS025
        {
            get
            {
                return this._prs025;
            }
            set
            {
                this._prs025 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PRS026
        {
            get
            {
                return this._prs026;
            }
            set
            {
                this._prs026 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PRS027
        {
            get
            {
                return this._prs027;
            }
            set
            {
                this._prs027 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PRS028
        {
            get
            {
                return this._prs028;
            }
            set
            {
                this._prs028 = value;
            }
        }
        
        /// <summary>
        /// 生产数量
        /// </summary>
                 
        public int PRS029
        {
            get
            {
                return this._prs029;
            }
            set
            {
                this._prs029 = value;
            }
        }

        /// <summary>
        /// 周计划排产之后未审核之前
        /// </summary>

        public bool PRS030
        {
            get
            {
                return this._prs030;
            }
            set
            {
                this._prs030 = value;
            }
        }
        
        /// <summary>
        /// 加急日期
        /// </summary>
                 
        public DateTime? PRS031
        {
            get
            {
                return this._prs031;
            }
            set
            {
                this._prs031 = value;
            }
        }
        
        // 
        public string PRS032
        {
            get
            {
                return this._prs032;
            }
            set
            {
                this._prs032 = value;
            }
        }
        
        // 
        public string PRS033
        {
            get
            {
                return this._prs033;
            }
            set
            {
                this._prs033 = value;
            }
        }
        
        // 
        public string PRS034
        {
            get
            {
                return this._prs034;
            }
            set
            {
                this._prs034 = value;
            }
        }
        
        // 
        public string PRS035
        {
            get
            {
                return this._prs035;
            }
            set
            {
                this._prs035 = value;
            }
        }
        
        // 
        public string PRS036
        {
            get
            {
                return this._prs036;
            }
            set
            {
                this._prs036 = value;
            }
        }
        
        // 
        public string PRS037
        {
            get
            {
                return this._prs037;
            }
            set
            {
                this._prs037 = value;
            }
        }
        
        // 
        public string PRS038
        {
            get
            {
                return this._prs038;
            }
            set
            {
                this._prs038 = value;
            }
        }
        
        // 
        public string PRS039
        {
            get
            {
                return this._prs039;
            }
            set
            {
                this._prs039 = value;
            }
        }
        
        // 
        public string PRS040
        {
            get
            {
                return this._prs040;
            }
            set
            {
                this._prs040 = value;
            }
        }
    }
}
