//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProductionPaintWeekDailyEntity
    {
        
        private int _idx;
        
        private string _pwi001;
        
        private string _pwi002;
        
        private string _pwi003;
        
        private string _pwi004;
        
        private string _pwi005;
        
        private int _pwi006;
        
        private int _pwi007;
        
        private bool _pwi008;
        
        private string _pwi009;
        
        private int _pwi010;
        
        private int _pwi011;
        
        private DateTime _pwi012;
        
        private DateTime _pwi013;
        
        private string _pwi014;
        
        private bool _pwi015;
        
        private string _pwi016;
        
        private string _pwi017;
        
        private string _pwi018;
        
        private string _pwi019;
        
        private string _pwi020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PWI001
        {
            get
            {
                return this._pwi001;
            }
            set
            {
                this._pwi001 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PWI002
        {
            get
            {
                return this._pwi002;
            }
            set
            {
                this._pwi002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PWI003
        {
            get
            {
                return this._pwi003;
            }
            set
            {
                this._pwi003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PWI004
        {
            get
            {
                return this._pwi004;
            }
            set
            {
                this._pwi004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PWI005
        {
            get
            {
                return this._pwi005;
            }
            set
            {
                this._pwi005 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int PWI006
        {
            get
            {
                return this._pwi006;
            }
            set
            {
                this._pwi006 = value;
            }
        }

        /// <summary>
        /// 报工数量
        /// </summary>

        public int PWI007
        {
            get
            {
                return this._pwi007;
            }
            set
            {
                this._pwi007 = value;
            }
        }

        /// <summary>
        /// 预排报工
        /// </summary>

        public bool PWI008
        {
            get
            {
                return this._pwi008;
            }
            set
            {
                this._pwi008 = value;
            }
        }
        
        /// <summary>
        /// 周计划单号
        /// </summary>
                 
        public string PWI009
        {
            get
            {
                return this._pwi009;
            }
            set
            {
                this._pwi009 = value;
            }
        }
        
        // 
        public int PWI010
        {
            get
            {
                return this._pwi010;
            }
            set
            {
                this._pwi010 = value;
            }
        }
        
        // 
        public int PWI011
        {
            get
            {
                return this._pwi011;
            }
            set
            {
                this._pwi011 = value;
            }
        }

        /// <summary>
        /// 报工时间
        /// </summary>

        public DateTime PWI012
        {
            get
            {
                return this._pwi012;
            }
            set
            {
                this._pwi012 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PWI013
        {
            get
            {
                return this._pwi013;
            }
            set
            {
                this._pwi013 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PWI014
        {
            get
            {
                return this._pwi014;
            }
            set
            {
                this._pwi014 = value;
            }
        }
        
        // 
        public bool PWI015
        {
            get
            {
                return this._pwi015;
            }
            set
            {
                this._pwi015 = value;
            }
        }
        
        // 
        public string PWI016
        {
            get
            {
                return this._pwi016;
            }
            set
            {
                this._pwi016 = value;
            }
        }
        
        // 
        public string PWI017
        {
            get
            {
                return this._pwi017;
            }
            set
            {
                this._pwi017 = value;
            }
        }
        
        // 
        public string PWI018
        {
            get
            {
                return this._pwi018;
            }
            set
            {
                this._pwi018 = value;
            }
        }
        
        // 
        public string PWI019
        {
            get
            {
                return this._pwi019;
            }
            set
            {
                this._pwi019 = value;
            }
        }
        
        // 
        public string PWI020
        {
            get
            {
                return this._pwi020;
            }
            set
            {
                this._pwi020 = value;
            }
        }
    }
}
