//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProductionPaintDayPWEEntity
    {
        
        private int _idx;
        
        private string _pwe001;
        
        private string _pwe002;
        
        private string _pwe003;
        
        private string _pwe004;
        
        private string _pwe005;
        
        private int _pwe006;
        
        private int _pwe007;
        
        private string _pwe008;
        
        private DateTime _pwe009;
        
        private string _pwe010;
        
        private bool _pwe011;
        
        private bool _pwe012;
        
        private string _pwe013;
        
        private string _pwe014;
        
        private string _pwe015;
        
        private string _pwe016;
        
        private string _pwe017;
        
        private string _pwe018;
        
        private string _pwe019;
        
        private string _pwe020;
        
        private string _pwe021;
        
        private string _pwe022;
        
        private string _pwe023;
        
        private string _pwe024;
        
        private string _pwe025;
        
        private string _pwe026;
        
        private string _pwe027;
        
        private string _pwe028;
        
        private string _pwe029;
        
        private string _pwe030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PWE001
        {
            get
            {
                return this._pwe001;
            }
            set
            {
                this._pwe001 = value;
            }
        }

        /// <summary>
        /// 完工状态
        /// </summary>

        public string PWE002
        {
            get
            {
                return this._pwe002;
            }
            set
            {
                this._pwe002 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PWE003
        {
            get
            {
                return this._pwe003;
            }
            set
            {
                this._pwe003 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PWE004
        {
            get
            {
                return this._pwe004;
            }
            set
            {
                this._pwe004 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PWE005
        {
            get
            {
                return this._pwe005;
            }
            set
            {
                this._pwe005 = value;
            }
        }

        /// <summary>
        /// 订单数量
        /// </summary>

        public int PWE006
        {
            get
            {
                return this._pwe006;
            }
            set
            {
                this._pwe006 = value;
            }
        }

        /// <summary>
        /// 计划数量
        /// </summary>

        public int PWE007
        {
            get
            {
                return this._pwe007;
            }
            set
            {
                this._pwe007 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PWE008
        {
            get
            {
                return this._pwe008;
            }
            set
            {
                this._pwe008 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PWE009
        {
            get
            {
                return this._pwe009;
            }
            set
            {
                this._pwe009 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PWE010
        {
            get
            {
                return this._pwe010;
            }
            set
            {
                this._pwe010 = value;
            }
        }

        /// <summary>
        /// 完成标记
        /// </summary>

        public bool PWE011
        {
            get
            {
                return this._pwe011;
            }
            set
            {
                this._pwe011 = value;
            }
        }

        /// <summary>
        /// 预排
        /// </summary>

        public bool PWE012
        {
            get
            {
                return this._pwe012;
            }
            set
            {
                this._pwe012 = value;
            }
        }
        
        // 
        public string PWE013
        {
            get
            {
                return this._pwe013;
            }
            set
            {
                this._pwe013 = value;
            }
        }
        
        // 
        public string PWE014
        {
            get
            {
                return this._pwe014;
            }
            set
            {
                this._pwe014 = value;
            }
        }
        
        // 
        public string PWE015
        {
            get
            {
                return this._pwe015;
            }
            set
            {
                this._pwe015 = value;
            }
        }
        
        // 
        public string PWE016
        {
            get
            {
                return this._pwe016;
            }
            set
            {
                this._pwe016 = value;
            }
        }
        
        // 
        public string PWE017
        {
            get
            {
                return this._pwe017;
            }
            set
            {
                this._pwe017 = value;
            }
        }
        
        // 
        public string PWE018
        {
            get
            {
                return this._pwe018;
            }
            set
            {
                this._pwe018 = value;
            }
        }
        
        // 
        public string PWE019
        {
            get
            {
                return this._pwe019;
            }
            set
            {
                this._pwe019 = value;
            }
        }
        
        // 
        public string PWE020
        {
            get
            {
                return this._pwe020;
            }
            set
            {
                this._pwe020 = value;
            }
        }
        
        // 
        public string PWE021
        {
            get
            {
                return this._pwe021;
            }
            set
            {
                this._pwe021 = value;
            }
        }
        
        // 
        public string PWE022
        {
            get
            {
                return this._pwe022;
            }
            set
            {
                this._pwe022 = value;
            }
        }
        
        // 
        public string PWE023
        {
            get
            {
                return this._pwe023;
            }
            set
            {
                this._pwe023 = value;
            }
        }
        
        // 
        public string PWE024
        {
            get
            {
                return this._pwe024;
            }
            set
            {
                this._pwe024 = value;
            }
        }
        
        // 
        public string PWE025
        {
            get
            {
                return this._pwe025;
            }
            set
            {
                this._pwe025 = value;
            }
        }
        
        // 
        public string PWE026
        {
            get
            {
                return this._pwe026;
            }
            set
            {
                this._pwe026 = value;
            }
        }
        
        // 
        public string PWE027
        {
            get
            {
                return this._pwe027;
            }
            set
            {
                this._pwe027 = value;
            }
        }
        
        // 
        public string PWE028
        {
            get
            {
                return this._pwe028;
            }
            set
            {
                this._pwe028 = value;
            }
        }
        
        // 
        public string PWE029
        {
            get
            {
                return this._pwe029;
            }
            set
            {
                this._pwe029 = value;
            }
        }
        
        // 
        public string PWE030
        {
            get
            {
                return this._pwe030;
            }
            set
            {
                this._pwe030 = value;
            }
        }
    }
}
