//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProductionPaintDayDailyEntity
    {
        
        private int _idx;
        
        private string _pwf001;
        
        private string _pwf002;
        
        private string _pwf003;
        
        private string _pwf004;
        
        private string _pwf005;
        
        private int _pwf006;
        
        private int _pwf007;
        
        private int _pwf008;
        
        private int _pwf009;
        
        private int _pwf010;
        
        private int _pwf011;
        
        private DateTime? _pwf012;
        
        private DateTime _pwf013;
        
        private string _pwf014;
        
        private bool _pwf015;
        
        private int _pwf016;
        
        private string _pwf017;
        
        private string _pwf018;
        
        private string _pwf019;
        
        private string _pwf020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PWF001
        {
            get
            {
                return this._pwf001;
            }
            set
            {
                this._pwf001 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PWF002
        {
            get
            {
                return this._pwf002;
            }
            set
            {
                this._pwf002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PWF003
        {
            get
            {
                return this._pwf003;
            }
            set
            {
                this._pwf003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PWF004
        {
            get
            {
                return this._pwf004;
            }
            set
            {
                this._pwf004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PWF005
        {
            get
            {
                return this._pwf005;
            }
            set
            {
                this._pwf005 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int PWF006
        {
            get
            {
                return this._pwf006;
            }
            set
            {
                this._pwf006 = value;
            }
        }

        /// <summary>
        /// 底漆数量
        /// </summary>

        public int PWF007
        {
            get
            {
                return this._pwf007;
            }
            set
            {
                this._pwf007 = value;
            }
        }

        /// <summary>
        /// 油磨数量
        /// </summary>

        public int PWF008
        {
            get
            {
                return this._pwf008;
            }
            set
            {
                this._pwf008 = value;
            }
        }

        /// <summary>
        /// 修色数量
        /// </summary>

        public int PWF009
        {
            get
            {
                return this._pwf009;
            }
            set
            {
                this._pwf009 = value;
            }
        }

        /// <summary>
        /// 面漆数量
        /// </summary>

        public int PWF010
        {
            get
            {
                return this._pwf010;
            }
            set
            {
                this._pwf010 = value;
            }
        }

        /// <summary>
        /// 软包数量
        /// </summary>

        public int PWF011
        {
            get
            {
                return this._pwf011;
            }
            set
            {
                this._pwf011 = value;
            }
        }

        /// <summary>
        /// 报工时间
        /// </summary>

        public DateTime? PWF012
        {
            get
            {
                return this._pwf012;
            }
            set
            {
                this._pwf012 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PWF013
        {
            get
            {
                return this._pwf013;
            }
            set
            {
                this._pwf013 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PWF014
        {
            get
            {
                return this._pwf014;
            }
            set
            {
                this._pwf014 = value;
            }
        }
        
        /// <summary>
        /// 计划报工
        /// </summary>
                 
        public bool PWF015
        {
            get
            {
                return this._pwf015;
            }
            set
            {
                this._pwf015 = value;
            }
        }

        /// <summary>
        /// 包装数量
        /// </summary>

        public int PWF016
        {
            get
            {
                return this._pwf016;
            }
            set
            {
                this._pwf016 = value;
            }
        }
        
        /// <summary>
        /// 日计划单号
        /// </summary>
                 
        public string PWF017
        {
            get
            {
                return this._pwf017;
            }
            set
            {
                this._pwf017 = value;
            }
        }
        
        // 
        public string PWF018
        {
            get
            {
                return this._pwf018;
            }
            set
            {
                this._pwf018 = value;
            }
        }
        
        // 
        public string PWF019
        {
            get
            {
                return this._pwf019;
            }
            set
            {
                this._pwf019 = value;
            }
        }
        
        // 
        public string PWF020
        {
            get
            {
                return this._pwf020;
            }
            set
            {
                this._pwf020 = value;
            }
        }
    }
}
