//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class productBLWorkEntity
    {
        
        private int _idx;
        
        private string _pbw001;
        
        private string _pbw002;
        
        private string _pbw003;
        
        private int _pbw004;
        
        private string _pbw005;
        
        private int _pbw006;
        
        private int _pbw007;
        
        private string _pbw008;
        
        private DateTime _pbw009;
        
        private string _pbw010;
        
        private int _pbw011;
        
        private string _pbw012;
        
        private string _pbw013;
        
        private string _pbw014;
        
        private string _pbw015;
        
        private string _pbw016;
        
        private string _pbw017;
        
        private string _pbw018;
        
        private string _pbw019;
        
        private string _pbw020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PBW001
        {
            get
            {
                return this._pbw001;
            }
            set
            {
                this._pbw001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PBW002
        {
            get
            {
                return this._pbw002;
            }
            set
            {
                this._pbw002 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PBW003
        {
            get
            {
                return this._pbw003;
            }
            set
            {
                this._pbw003 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int PBW004
        {
            get
            {
                return this._pbw004;
            }
            set
            {
                this._pbw004 = value;
            }
        }

        /// <summary>
        /// 零件名称
        /// </summary>

        public string PBW005
        {
            get
            {
                return this._pbw005;
            }
            set
            {
                this._pbw005 = value;
            }
        }

        /// <summary>
        /// 单量
        /// </summary>

        public int PBW006
        {
            get
            {
                return this._pbw006;
            }
            set
            {
                this._pbw006 = value;
            }
        }

        /// <summary>
        /// 需要量
        /// </summary>

        public int PBW007
        {
            get
            {
                return this._pbw007;
            }
            set
            {
                this._pbw007 = value;
            }
        }

        /// <summary>
        /// 工序
        /// </summary>

        public string PBW008
        {
            get
            {
                return this._pbw008;
            }
            set
            {
                this._pbw008 = value;
            }
        }

        /// <summary>
        /// 完成时间
        /// </summary>

        public DateTime PBW009
        {
            get
            {
                return this._pbw009;
            }
            set
            {
                this._pbw009 = value;
            }
        }

        /// <summary>
        /// 工号
        /// </summary>

        public string PBW010
        {
            get
            {
                return this._pbw010;
            }
            set
            {
                this._pbw010 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public int PBW011
        {
            get
            {
                return this._pbw011;
            }
            set
            {
                this._pbw011 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PBW012
        {
            get
            {
                return this._pbw012;
            }
            set
            {
                this._pbw012 = value;
            }
        }
        
        // 
        public string PBW013
        {
            get
            {
                return this._pbw013;
            }
            set
            {
                this._pbw013 = value;
            }
        }
        
        // 
        public string PBW014
        {
            get
            {
                return this._pbw014;
            }
            set
            {
                this._pbw014 = value;
            }
        }
        
        // 
        public string PBW015
        {
            get
            {
                return this._pbw015;
            }
            set
            {
                this._pbw015 = value;
            }
        }
        
        // 
        public string PBW016
        {
            get
            {
                return this._pbw016;
            }
            set
            {
                this._pbw016 = value;
            }
        }
        
        // 
        public string PBW017
        {
            get
            {
                return this._pbw017;
            }
            set
            {
                this._pbw017 = value;
            }
        }
        
        // 
        public string PBW018
        {
            get
            {
                return this._pbw018;
            }
            set
            {
                this._pbw018 = value;
            }
        }
        
        // 
        public string PBW019
        {
            get
            {
                return this._pbw019;
            }
            set
            {
                this._pbw019 = value;
            }
        }
        
        // 
        public string PBW020
        {
            get
            {
                return this._pbw020;
            }
            set
            {
                this._pbw020 = value;
            }
        }
    }
}
