//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProductionPaintWeekPWHEntity
    {
        
        private int _idx;
        
        private string _pwh001;
        
        private string _pwh002;
        
        private string _pwh003;
        
        private string _pwh004;
        
        private string _pwh005;
        
        private string _pwh006;
        
        private int _pwh007;
        
        private DateTime _pwh008;
        
        private string _pwh009;
        
        private bool _pwh010;
        
        private DateTime _pwh011;
        
        private string _pwh012;
        
        private bool _pwh013;
        
        private int _pwh014;
        
        private int _pwh015;
        
        private DateTime? _pwh016;
        
        private string _pwh017;
        
        private string _pwh018;
        
        private string _pwh019;
        
        private string _pwh020;
        
        private string _pwh021;
        
        private string _pwh022;
        
        private string _pwh023;
        
        private string _pwh024;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PWH001
        {
            get
            {
                return this._pwh001;
            }
            set
            {
                this._pwh001 = value;
            }
        }

        /// <summary>
        /// 遗留单号
        /// </summary>

        public string PWH002
        {
            get
            {
                return this._pwh002;
            }
            set
            {
                this._pwh002 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PWH003
        {
            get
            {
                return this._pwh003;
            }
            set
            {
                this._pwh003 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PWH004
        {
            get
            {
                return this._pwh004;
            }
            set
            {
                this._pwh004 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PWH005
        {
            get
            {
                return this._pwh005;
            }
            set
            {
                this._pwh005 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PWH006
        {
            get
            {
                return this._pwh006;
            }
            set
            {
                this._pwh006 = value;
            }
        }

        /// <summary>
        /// 订单量
        /// </summary>

        public int PWH007
        {
            get
            {
                return this._pwh007;
            }
            set
            {
                this._pwh007 = value;
            }
        }
        
        // 
        public DateTime PWH008
        {
            get
            {
                return this._pwh008;
            }
            set
            {
                this._pwh008 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PWH009
        {
            get
            {
                return this._pwh009;
            }
            set
            {
                this._pwh009 = value;
            }
        }

        /// <summary>
        /// 预排
        /// </summary>

        public bool PWH010
        {
            get
            {
                return this._pwh010;
            }
            set
            {
                this._pwh010 = value;
            }
        }

        /// <summary>
        /// 录入时间
        /// </summary>

        public DateTime PWH011
        {
            get
            {
                return this._pwh011;
            }
            set
            {
                this._pwh011 = value;
            }
        }

        /// <summary>
        /// 录入者
        /// </summary>

        public string PWH012
        {
            get
            {
                return this._pwh012;
            }
            set
            {
                this._pwh012 = value;
            }
        }

        /// <summary>
        /// 是否完成
        /// </summary>

        public bool PWH013
        {
            get
            {
                return this._pwh013;
            }
            set
            {
                this._pwh013 = value;
            }
        }

        /// <summary>
        /// 计划生产量
        /// </summary>

        public int PWH014
        {
            get
            {
                return this._pwh014;
            }
            set
            {
                this._pwh014 = value;
            }
        }
        
        // 
        public int PWH015
        {
            get
            {
                return this._pwh015;
            }
            set
            {
                this._pwh015 = value;
            }
        }

        /// <summary>
        /// 油漆计划完成时间
        /// </summary>

        public DateTime? PWH016
        {
            get
            {
                return this._pwh016;
            }
            set
            {
                this._pwh016 = value;
            }
        }
        
        // 
        public string PWH017
        {
            get
            {
                return this._pwh017;
            }
            set
            {
                this._pwh017 = value;
            }
        }
        
        // 
        public string PWH018
        {
            get
            {
                return this._pwh018;
            }
            set
            {
                this._pwh018 = value;
            }
        }
        
        // 
        public string PWH019
        {
            get
            {
                return this._pwh019;
            }
            set
            {
                this._pwh019 = value;
            }
        }
        
        // 
        public string PWH020
        {
            get
            {
                return this._pwh020;
            }
            set
            {
                this._pwh020 = value;
            }
        }
        
        // 
        public string PWH021
        {
            get
            {
                return this._pwh021;
            }
            set
            {
                this._pwh021 = value;
            }
        }
        
        // 
        public string PWH022
        {
            get
            {
                return this._pwh022;
            }
            set
            {
                this._pwh022 = value;
            }
        }
        
        // 
        public string PWH023
        {
            get
            {
                return this._pwh023;
            }
            set
            {
                this._pwh023 = value;
            }
        }
        
        // 
        public string PWH024
        {
            get
            {
                return this._pwh024;
            }
            set
            {
                this._pwh024 = value;
            }
        }
    }
}
