//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProductionAssembleEntity
    {
        
        private int _idx;
        
        private string _pas001;
        
        private string _pas002;
        
        private string _pas003;
        
        private string _pas004;
        
        private DateTime _pas005;
        
        private DateTime _pas006;
        
        private string _pas029;
        
        private DateTime? _pas007;
        
        private DateTime _pas008;
        
        private string _pas009;
        
        private string _pas010;
        
        private int _pas011;
        
        private DateTime _pas012;
        
        private string _pas013;
        
        private DateTime _pas014;
        
        private string _pas015;
        
        private int _pas016;
        
        private bool _pas017;
        
        private bool _pas018;
        
        private DateTime _pas019;
        
        private DateTime _pas020;
        
        private DateTime _pas021;
        
        private DateTime _pas022;
        
        private string _pas023;
        
        private DateTime _pas024;
        
        private string _pas025;
        
        private DateTime _pas026;
        
        private string _pas027;
        
        private int _pas028;
        
        private bool _pas030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PAS001
        {
            get
            {
                return this._pas001;
            }
            set
            {
                this._pas001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PAS002
        {
            get
            {
                return this._pas002;
            }
            set
            {
                this._pas002 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PAS003
        {
            get
            {
                return this._pas003;
            }
            set
            {
                this._pas003 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PAS004
        {
            get
            {
                return this._pas004;
            }
            set
            {
                this._pas004 = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>

        public DateTime PAS005
        {
            get
            {
                return this._pas005;
            }
            set
            {
                this._pas005 = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>

        public DateTime PAS006
        {
            get
            {
                return this._pas006;
            }
            set
            {
                this._pas006 = value;
            }
        }

        /// <summary>
        /// 计划完成时间
        /// </summary>

        public string PAS029
        {
            get
            {
                return this._pas029;
            }
            set
            {
                this._pas029 = value;
            }
        }

        /// <summary>
        /// 周计划计划完成日
        /// </summary>

        public DateTime? PAS007
        {
            get
            {
                return this._pas007;
            }
            set
            {
                this._pas007 = value;
            }
        }

        /// <summary>
        /// 生产日期
        /// </summary>

        public DateTime PAS008
        {
            get
            {
                return this._pas008;
            }
            set
            {
                this._pas008 = value;
            }
        }
        
        /// <summary>
        /// 员工编号
        /// </summary>

        public string PAS009
        {
            get
            {
                return this._pas009;
            }
            set
            {
                this._pas009 = value;
            }
        }

        /// <summary>
        /// 员工姓名
        /// </summary>

        public string PAS010
        {
            get
            {
                return this._pas010;
            }
            set
            {
                this._pas010 = value;
            }
        }

        /// <summary>
        /// 完成数量
        /// </summary>

        public int PAS011
        {
            get
            {
                return this._pas011;
            }
            set
            {
                this._pas011 = value;
            }
        }

        /// <summary>
        /// 实际完成时间
        /// </summary>

        public DateTime PAS012
        {
            get
            {
                return this._pas012;
            }
            set
            {
                this._pas012 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PAS013
        {
            get
            {
                return this._pas013;
            }
            set
            {
                this._pas013 = value;
            }
        }

        /// <summary>
        /// 日期
        /// </summary>

        public DateTime PAS014
        {
            get
            {
                return this._pas014;
            }
            set
            {
                this._pas014 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PAS015
        {
            get
            {
                return this._pas015;
            }
            set
            {
                this._pas015 = value;
            }
        }

        /// <summary>
        /// 生产数量
        /// </summary>

        public int PAS016
        {
            get
            {
                return this._pas016;
            }
            set
            {
                this._pas016 = value;
            }
        }
        
        /// <summary>
        /// 组装完工标记
        /// </summary>
                 
        public bool PAS017
        {
            get
            {
                return this._pas017;
            }
            set
            {
                this._pas017 = value;
            }
        }
        
        /// <summary>
        /// 包装完工标记
        /// </summary>
                 
        public bool PAS018
        {
            get
            {
                return this._pas018;
            }
            set
            {
                this._pas018 = value;
            }
        }
        
        // 
        public DateTime PAS019
        {
            get
            {
                return this._pas019;
            }
            set
            {
                this._pas019 = value;
            }
        }
        
        // 
        public DateTime PAS020
        {
            get
            {
                return this._pas020;
            }
            set
            {
                this._pas020 = value;
            }
        }
        
        // 
        public DateTime PAS021
        {
            get
            {
                return this._pas021;
            }
            set
            {
                this._pas021 = value;
            }
        }
        
        // 
        public DateTime PAS022
        {
            get
            {
                return this._pas022;
            }
            set
            {
                this._pas022 = value;
            }
        }
        
        // 
        public string PAS023
        {
            get
            {
                return this._pas023;
            }
            set
            {
                this._pas023 = value;
            }
        }
        
        // 
        public DateTime PAS024
        {
            get
            {
                return this._pas024;
            }
            set
            {
                this._pas024 = value;
            }
        }
        
        // 
        public string PAS025
        {
            get
            {
                return this._pas025;
            }
            set
            {
                this._pas025 = value;
            }
        }
        
        // 
        public DateTime PAS026
        {
            get
            {
                return this._pas026;
            }
            set
            {
                this._pas026 = value;
            }
        }
        
        // 
        public string PAS027
        {
            get
            {
                return this._pas027;
            }
            set
            {
                this._pas027 = value;
            }
        }
        
        // 
        public int PAS028
        {
            get
            {
                return this._pas028;
            }
            set
            {
                this._pas028 = value;
            }
        }

        /// <summary>
        /// 周计划排产之后未审核之前
        /// </summary>

        public bool PAS030
        {
            get
            {
                return this._pas030;
            }
            set
            {
                this._pas030 = value;
            }
        }
    }
}
