//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProductionStockEntity
    {
        
        private int _idx;
        
        private string _pst001;
        
        private string _pst002;
        
        private string _pst003;
        
        private string _pst004;
        
        private DateTime? _pst005;
        
        private DateTime? _pst006;
        
        private DateTime? _pst007;
        
        private DateTime? _pst008;
        
        private DateTime? _pst009;
        
        private DateTime? _pst010;
        
        private DateTime? _pst011;
        
        private DateTime? _pst012;
        
        private DateTime? _pst013;
        
        private DateTime? _pst014;
        
        private string _pst015;
        
        private DateTime? _pst016;
        
        private DateTime? _pst017;
        
        private DateTime? _pst018;
        
        private DateTime? _pst019;
        
        private DateTime? _pst020;
        
        private DateTime? _pst021;
        
        private DateTime? _pst022;
        
        private string _pst023;
        
        private DateTime? _pst024;
        
        private string _pst025;
        
        private DateTime? _pst026;
        
        private string _pst027;
        
        private int _pst028;
        
        private DateTime? _pst029;
        
        private bool _pst030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PST001
        {
            get
            {
                return this._pst001;
            }
            set
            {
                this._pst001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PST002
        {
            get
            {
                return this._pst002;
            }
            set
            {
                this._pst002 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PST003
        {
            get
            {
                return this._pst003;
            }
            set
            {
                this._pst003 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PST004
        {
            get
            {
                return this._pst004;
            }
            set
            {
                this._pst004 = value;
            }
        }

        /// <summary>
        /// 下料计划完成时间
        /// </summary>

        public DateTime? PST005
        {
            get
            {
                return this._pst005;
            }
            set
            {
                this._pst005 = value;
            }
        }

        /// <summary>
        /// 断料实际完成时间
        /// </summary>

        public DateTime? PST006
        {
            get
            {
                return this._pst006;
            }
            set
            {
                this._pst006 = value;
            }
        }

        /// <summary>
        /// 修边计划完成时间
        /// </summary>

        public DateTime? PST007
        {
            get
            {
                return this._pst007;
            }
            set
            {
                this._pst007 = value;
            }
        }

        /// <summary>
        /// 修边实际完成时间
        /// </summary>

        public DateTime? PST008
        {
            get
            {
                return this._pst008;
            }
            set
            {
                this._pst008 = value;
            }
        }

        /// <summary>
        /// 齿接计划完成时间
        /// </summary>

        public DateTime? PST009
        {
            get
            {
                return this._pst009;
            }
            set
            {
                this._pst009 = value;
            }
        }

        /// <summary>
        /// 齿接实际完成时间
        /// </summary>

        public DateTime? PST010
        {
            get
            {
                return this._pst010;
            }
            set
            {
                this._pst010 = value;
            }
        }

        /// <summary>
        /// 拼板计划完成时间
        /// </summary>

        public DateTime? PST011
        {
            get
            {
                return this._pst011;
            }
            set
            {
                this._pst011 = value;
            }
        }

        /// <summary>
        /// 拼板实际完成时间
        /// </summary>

        public DateTime? PST012
        {
            get
            {
                return this._pst012;
            }
            set
            {
                this._pst012 = value;
            }
        }

        /// <summary>
        /// 刨床计划完成时间
        /// </summary>

        public DateTime? PST013
        {
            get
            {
                return this._pst013;
            }
            set
            {
                this._pst013 = value;
            }
        }

        /// <summary>
        /// 刨床实际完成时间
        /// </summary>

        public DateTime? PST014
        {
            get
            {
                return this._pst014;
            }
            set
            {
                this._pst014 = value;
            }
        }

        /// <summary>
        /// 备料计划完成时间批次周次
        /// </summary>

        public string PST015
        {
            get
            {
                return this._pst015;
            }
            set
            {
                this._pst015 = value;
            }
        }

        /// <summary>
        /// 配套报工时间
        /// </summary>

        public DateTime? PST016
        {
            get
            {
                return this._pst016;
            }
            set
            {
                this._pst016 = value;
            }
        }

        /// <summary>
        /// 机加工加工中心计划完成时间
        /// </summary>

        public DateTime? PST017
        {
            get
            {
                return this._pst017;
            }
            set
            {
                this._pst017 = value;
            }
        }

        /// <summary>
        /// 机加工加工中心实际完成时间
        /// </summary>

        public DateTime? PST018
        {
            get
            {
                return this._pst018;
            }
            set
            {
                this._pst018 = value;
            }
        }

        /// <summary>
        /// 机加工开榫计划完成时间
        /// </summary>

        public DateTime? PST019
        {
            get
            {
                return this._pst019;
            }
            set
            {
                this._pst019 = value;
            }
        }

        /// <summary>
        /// 机加工开榫实际完成时间
        /// </summary>

        public DateTime? PST020
        {
            get
            {
                return this._pst020;
            }
            set
            {
                this._pst020 = value;
            }
        }

        /// <summary>
        /// 机加工倒圆计划完成时间
        /// </summary>

        public DateTime? PST021
        {
            get
            {
                return this._pst021;
            }
            set
            {
                this._pst021 = value;
            }
        }

        /// <summary>
        /// 机加工倒圆实际完成时间
        /// </summary>

        public DateTime? PST022
        {
            get
            {
                return this._pst022;
            }
            set
            {
                this._pst022 = value;
            }
        }

        /// <summary>
        /// 机加工计划完成时间
        /// </summary>

        public string PST023
        {
            get
            {
                return this._pst023;
            }
            set
            {
                this._pst023 = value;
            }
        }

        /// <summary>
        /// 机加工完成时间
        /// </summary>

        public DateTime? PST024
        {
            get
            {
                return this._pst024;
            }
            set
            {
                this._pst024 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PST025
        {
            get
            {
                return this._pst025;
            }
            set
            {
                this._pst025 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime? PST026
        {
            get
            {
                return this._pst026;
            }
            set
            {
                this._pst026 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PST027
        {
            get
            {
                return this._pst027;
            }
            set
            {
                this._pst027 = value;
            }
        }
        
        /// <summary>
        /// 生产数量
        /// </summary>
                 
        public int PST028
        {
            get
            {
                return this._pst028;
            }
            set
            {
                this._pst028 = value;
            }
        }
        
        /// <summary>
        /// 断料计划完成时间
        /// </summary>
                 
        public DateTime? PST029
        {
            get
            {
                return this._pst029;
            }
            set
            {
                this._pst029 = value;
            }
        }

        /// <summary>
        /// 周计划排产之后未审核之前
        /// </summary>

        public bool PST030
        {
            get
            {
                return this._pst030;
            }
            set
            {
                this._pst030 = value;
            }
        }
    }
}
