//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProductionPaintDayPWDEntity
    {
        
        private int _idx;
        
        private string _pwd001;
        
        private string _pwd002;
        
        private DateTime _pwd003;
        
        private DateTime _pwd004;
        
        private bool _pwd005;
        
        private bool _pwd006;
        
        private DateTime _pwd007;
        
        private string _pwd008;
        
        private decimal _pwd009;
        
        private DateTime? _pwd010;
        
        private string _pwd011;
        
        private string _pwd012;
        
        private string _pwd013;
        
        private string _pwd014;
        
        private string _pwd015;
        
        private string _pwd016;
        
        private string _pwd017;
        
        private string _pwd018;
        
        private string _pwd019;
        
        private string _pwd020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PWD001
        {
            get
            {
                return this._pwd001;
            }
            set
            {
                this._pwd001 = value;
            }
        }

        /// <summary>
        /// 工段
        /// </summary>

        public string PWD002
        {
            get
            {
                return this._pwd002;
            }
            set
            {
                this._pwd002 = value;
            }
        }

        /// <summary>
        /// 计划日期
        /// </summary>

        public DateTime PWD003
        {
            get
            {
                return this._pwd003;
            }
            set
            {
                this._pwd003 = value;
            }
        }

        /// <summary>
        /// 下单日期
        /// </summary>

        public DateTime PWD004
        {
            get
            {
                return this._pwd004;
            }
            set
            {
                this._pwd004 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool PWD005
        {
            get
            {
                return this._pwd005;
            }
            set
            {
                this._pwd005 = value;
            }
        }

        /// <summary>
        /// 审核
        /// </summary>

        public bool PWD006
        {
            get
            {
                return this._pwd006;
            }
            set
            {
                this._pwd006 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PWD007
        {
            get
            {
                return this._pwd007;
            }
            set
            {
                this._pwd007 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PWD008
        {
            get
            {
                return this._pwd008;
            }
            set
            {
                this._pwd008 = value;
            }
        }

        /// <summary>
        /// 完成率
        /// </summary>

        public decimal PWD009
        {
            get
            {
                return this._pwd009;
            }
            set
            {
                this._pwd009 = value;
            }
        }

        /// <summary>
        /// 上工作日
        /// </summary>

        public DateTime? PWD010
        {
            get
            {
                return this._pwd010;
            }
            set
            {
                this._pwd010 = value;
            }
        }
        
        // 
        public string PWD011
        {
            get
            {
                return this._pwd011;
            }
            set
            {
                this._pwd011 = value;
            }
        }
        
        // 
        public string PWD012
        {
            get
            {
                return this._pwd012;
            }
            set
            {
                this._pwd012 = value;
            }
        }
        
        // 
        public string PWD013
        {
            get
            {
                return this._pwd013;
            }
            set
            {
                this._pwd013 = value;
            }
        }
        
        // 
        public string PWD014
        {
            get
            {
                return this._pwd014;
            }
            set
            {
                this._pwd014 = value;
            }
        }
        
        // 
        public string PWD015
        {
            get
            {
                return this._pwd015;
            }
            set
            {
                this._pwd015 = value;
            }
        }
        
        // 
        public string PWD016
        {
            get
            {
                return this._pwd016;
            }
            set
            {
                this._pwd016 = value;
            }
        }
        
        // 
        public string PWD017
        {
            get
            {
                return this._pwd017;
            }
            set
            {
                this._pwd017 = value;
            }
        }
        
        // 
        public string PWD018
        {
            get
            {
                return this._pwd018;
            }
            set
            {
                this._pwd018 = value;
            }
        }
        
        // 
        public string PWD019
        {
            get
            {
                return this._pwd019;
            }
            set
            {
                this._pwd019 = value;
            }
        }
        
        // 
        public string PWD020
        {
            get
            {
                return this._pwd020;
            }
            set
            {
                this._pwd020 = value;
            }
        }
    }
}
