//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProductionPaintWeekPWGEntity
    {
        
        private int _idx;
        
        private string _pwg001;
        
        private DateTime _pwg002;
        
        private DateTime _pwg003;
        
        private DateTime _pwg004;
        
        private DateTime _pwg005;
        
        private string _pwg006;
        
        private bool _pwg007;
        
        private bool _pwg008;
        
        private string _pwg009;
        
        private string _pwg010;
        
        private string _pwg011;
        
        private string _pwg012;
        
        private string _pwg013;
        
        private string _pwg014;
        
        private string _pwg015;
        
        private string _pwg016;
        
        private string _pwg017;
        
        private string _pwg018;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string PWG001
        {
            get
            {
                return this._pwg001;
            }
            set
            {
                this._pwg001 = value;
            }
        }

        /// <summary>
        /// 录入日期
        /// </summary>

        public DateTime PWG002
        {
            get
            {
                return this._pwg002;
            }
            set
            {
                this._pwg002 = value;
            }
        }

        /// <summary>
        /// 下单日期
        /// </summary>

        public DateTime PWG003
        {
            get
            {
                return this._pwg003;
            }
            set
            {
                this._pwg003 = value;
            }
        }

        /// <summary>
        /// 生产周期开始日期
        /// </summary>

        public DateTime PWG004
        {
            get
            {
                return this._pwg004;
            }
            set
            {
                this._pwg004 = value;
            }
        }

        /// <summary>
        /// 生产周期结束日期
        /// </summary>

        public DateTime PWG005
        {
            get
            {
                return this._pwg005;
            }
            set
            {
                this._pwg005 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PWG006
        {
            get
            {
                return this._pwg006;
            }
            set
            {
                this._pwg006 = value;
            }
        }

        /// <summary>
        /// 审核
        /// </summary>

        public bool PWG007
        {
            get
            {
                return this._pwg007;
            }
            set
            {
                this._pwg007 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool PWG008
        {
            get
            {
                return this._pwg008;
            }
            set
            {
                this._pwg008 = value;
            }
        }

        /// <summary>
        /// 周次
        /// </summary>

        public string PWG009
        {
            get
            {
                return this._pwg009;
            }
            set
            {
                this._pwg009 = value;
            }
        }
        
        // 
        public string PWG010
        {
            get
            {
                return this._pwg010;
            }
            set
            {
                this._pwg010 = value;
            }
        }
        
        // 
        public string PWG011
        {
            get
            {
                return this._pwg011;
            }
            set
            {
                this._pwg011 = value;
            }
        }
        
        // 
        public string PWG012
        {
            get
            {
                return this._pwg012;
            }
            set
            {
                this._pwg012 = value;
            }
        }
        
        // 
        public string PWG013
        {
            get
            {
                return this._pwg013;
            }
            set
            {
                this._pwg013 = value;
            }
        }
        
        // 
        public string PWG014
        {
            get
            {
                return this._pwg014;
            }
            set
            {
                this._pwg014 = value;
            }
        }
        
        // 
        public string PWG015
        {
            get
            {
                return this._pwg015;
            }
            set
            {
                this._pwg015 = value;
            }
        }
        
        // 
        public string PWG016
        {
            get
            {
                return this._pwg016;
            }
            set
            {
                this._pwg016 = value;
            }
        }
        
        // 
        public string PWG017
        {
            get
            {
                return this._pwg017;
            }
            set
            {
                this._pwg017 = value;
            }
        }
        
        // 
        public string PWG018
        {
            get
            {
                return this._pwg018;
            }
            set
            {
                this._pwg018 = value;
            }
        }
    }
}
