//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;


    public sealed class ProductDailyWorkEntity
    {

        private int _idx;

        private string _prd001;

        private string _prd002;

        private string _prd003;

        private string _prd004;

        private string _prd005;

        private string _prd006;

        private string _prd007;

        private string _prd008;

        private string _prd009;

        private string _prd010;

        private string _prd011;

        private decimal _prd012;

        private DateTime _prd013;

        private bool _prd014;

        private string _prd015;

        private string _prd016;

        private DateTime _prd017;

        private string _prd018;

        private decimal _prd019;

        private bool _prd020;

        private bool _prd021;

        private string _prd022;

        private int _prd023;

        private string _prd024;

        private decimal _prd025;

        private string _prd026;

        private string _prd027;

        private decimal _prd028;

        private decimal _prd029;

        private decimal _prd030;

        private string _prd031;

        private string _prd032;

        private string _prd033;

        private string _prd034;

        private bool _prd035;
        private string _prd036;
        private decimal _prd037;
        private string _prd038;
        private decimal _prd039;
        private string _prd040;
        private decimal _prd041;
        private int _prd042;
        private int _prd043;

        // 
        public int idx
        {
            get
            {
                return this . _idx;
            }
            set
            {
                this . _idx = value;
            }
        }

        /// <summary>
        /// 设备编号
        /// </summary>

        public string PRD001
        {
            get
            {
                return this . _prd001;
            }
            set
            {
                this . _prd001 = value;
            }
        }

        /// <summary>
        /// 设备名称
        /// </summary>

        public string PRD002
        {
            get
            {
                return this . _prd002;
            }
            set
            {
                this . _prd002 = value;
            }
        }

        /// <summary>
        /// 工艺名称
        /// </summary>

        public string PRD003
        {
            get
            {
                return this . _prd003;
            }
            set
            {
                this . _prd003 = value;
            }
        }

        /// <summary>
        /// 人员编号
        /// </summary>

        public string PRD004
        {
            get
            {
                return this . _prd004;
            }
            set
            {
                this . _prd004 = value;
            }
        }

        /// <summary>
        /// 人员姓名
        /// </summary>

        public string PRD005
        {
            get
            {
                return this . _prd005;
            }
            set
            {
                this . _prd005 = value;
            }
        }

        /// <summary>
        /// 传票编号
        /// </summary>

        public string PRD006
        {
            get
            {
                return this . _prd006;
            }
            set
            {
                this . _prd006 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PRD007
        {
            get
            {
                return this . _prd007;
            }
            set
            {
                this . _prd007 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PRD008
        {
            get
            {
                return this . _prd008;
            }
            set
            {
                this . _prd008 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PRD009
        {
            get
            {
                return this . _prd009;
            }
            set
            {
                this . _prd009 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PRD010
        {
            get
            {
                return this . _prd010;
            }
            set
            {
                this . _prd010 = value;
            }
        }

        /// <summary>
        /// 零件名称
        /// </summary>

        public string PRD011
        {
            get
            {
                return this . _prd011;
            }
            set
            {
                this . _prd011 = value;
            }
        }

        /// <summary>
        /// 零件数量
        /// </summary>

        public decimal PRD012
        {
            get
            {
                return this . _prd012;
            }
            set
            {
                this . _prd012 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PRD013
        {
            get
            {
                return this . _prd013;
            }
            set
            {
                this . _prd013 = value;
            }
        }

        /// <summary>
        /// 开始结束标记
        /// </summary>

        public bool PRD014
        {
            get
            {
                return this . _prd014;
            }
            set
            {
                this . _prd014 = value;
            }
        }

        /// <summary>
        /// 组别
        /// </summary>

        public string PRD015
        {
            get
            {
                return this . _prd015;
            }
            set
            {
                this . _prd015 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PRD016
        {
            get
            {
                return this . _prd016;
            }
            set
            {
                this . _prd016 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime PRD017
        {
            get
            {
                return this . _prd017;
            }
            set
            {
                this . _prd017 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string PRD018
        {
            get
            {
                return this . _prd018;
            }
            set
            {
                this . _prd018 = value;
            }
        }

        /// <summary>
        /// 记工数量
        /// </summary>

        public decimal PRD019
        {
            get
            {
                return this . _prd019;
            }
            set
            {
                this . _prd019 = value;
            }
        }

        /// <summary>
        /// 是否审核
        /// </summary>

        public bool PRD020
        {
            get
            {
                return this . _prd020;
            }
            set
            {
                this . _prd020 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool PRD021
        {
            get
            {
                return this . _prd021;
            }
            set
            {
                this . _prd021 = value;
            }
        }

        /// <summary>
        /// 设备备注
        /// </summary>

        public string PRD022
        {
            get
            {
                return this . _prd022;
            }
            set
            {
                this . _prd022 = value;
            }
        }

        /// <summary>
        /// 加工次数
        /// </summary>

        public int PRD023
        {
            get
            {
                return this . _prd023;
            }
            set
            {
                this . _prd023 = value;
            }
        }

        /// <summary>
        /// 区间标准(非标)
        /// </summary>

        public string PRD024
        {
            get
            {
                return this . _prd024;
            }
            set
            {
                this . _prd024 = value;
            }
        }

        /// <summary>
        /// 区间标准价格(非标)
        /// </summary>

        public decimal PRD025
        {
            get
            {
                return this . _prd025;
            }
            set
            {
                this . _prd025 = value;
            }
        }

        /// <summary>
        /// 区间标准备注(非标)
        /// </summary>

        public string PRD026
        {
            get
            {
                return this . _prd026;
            }
            set
            {
                this . _prd026 = value;
            }
        }

        /// <summary>
        /// 区间标准
        /// </summary>

        public string PRD027
        {
            get
            {
                return this . _prd027;
            }
            set
            {
                this . _prd027 = value;
            }
        }

        /// <summary>
        /// 区间头
        /// </summary>
        public decimal PRD028
        {
            get
            {
                return _prd028;
            }

            set
            {
                _prd028 = value;
            }
        }

        /// <summary>
        /// 区间尾
        /// </summary>
        public decimal PRD029
        {
            get
            {
                return _prd029;
            }

            set
            {
                _prd029 = value;
            }
        }

        /// <summary>
        /// 区间价格
        /// </summary>
        public decimal PRD030
        {
            get
            {
                return _prd030;
            }

            set
            {
                _prd030 = value;
            }
        }

        /// <summary>
        /// 区间备注
        /// </summary>
        public string PRD031
        {
            get
            {
                return _prd031;
            }

            set
            {
                _prd031 = value;
            }
        }

        /// <summary>
        /// 工艺编号
        /// </summary>
        public string PRD032
        {
            get
            {
                return _prd032;
            }

            set
            {
                _prd032 = value;
            }
        }

        /// <summary>
        /// 工资类型
        /// </summary>
        public string PRD033
        {
            get
            {
                return _prd033;
            }

            set
            {
                _prd033 = value;
            }
        }

        /// <summary>
        /// 零件规格
        /// </summary>
        public string PRD034
        {
            get
            {
                return _prd034;
            }

            set
            {
                _prd034 = value;
            }
        }

        /// <summary>
        /// 强制完工
        /// </summary>
        public bool PRD035
        {
            get
            {
                return _prd035;
            }

            set
            {
                _prd035 = value;
            }
        }
        
        /// <summary>
        /// 规格
        /// </summary>
        public string PRD036
        {
            get
            {
                return _prd036;
            }

            set
            {
                _prd036 = value;
            }
        }

        /// <summary>
        /// 记工数量
        /// </summary>
        public decimal PRD037
        {
            get
            {
                return _prd037;
            }

            set
            {
                _prd037 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>
        public string PRD038
        {
            get
            {
                return _prd038;
            }

            set
            {
                _prd038 = value;
            }
        }

        /// <summary>
        /// 记工数量
        /// </summary>
        public decimal PRD039
        {
            get
            {
                return _prd039;
            }

            set
            {
                _prd039 = value;
            }
        }

        /// <summary>
        /// 规格 
        /// </summary>
        public string PRD040
        {
            get
            {
                return _prd040;
            }

            set
            {
                _prd040 = value;
            }
        }

        /// <summary>
        /// 记工数量
        /// </summary>
        public decimal PRD041
        {
            get
            {
                return _prd041;
            }

            set
            {
                _prd041 = value;
            }
        }

        /// <summary>
        /// 产品数量
        /// </summary>
        public int PRD042
        {
            get
            {
                return _prd042;
            }

            set
            {
                _prd042 = value;
            }
        }

        /// <summary>
        /// 生产分组
        /// </summary>
        public int PRD043
        {
            get
            {
                return _prd043;
            }

            set
            {
                _prd043 = value;
            }
        }


    }
}
