//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProductionPaintEntity
    {
        
        private int _idx;
        
        private string _pdp001;
        
        private string _pdp002;
        
        private string _pdp003;
        
        private string _pdp004;
        
        private int _pdp005;
        
        private string _pdp006;
        
        private DateTime? _pdp007;
        
        private int _pdp008;
        
        private int _pdp009;
        
        private DateTime? _pdp010;
        
        private int _pdp011;
        
        private int _pdp012;
        
        private DateTime? _pdp013;
        
        private int _pdp014;
        
        private int _pdp015;
        
        private DateTime? _pdp016;
        
        private int _pdp017;
        
        private int _pdp018;
        
        private DateTime? _pdp019;
        
        private int _pdp020;
        
        private string _pdp021;
        
        private int _pdp022;
        
        private DateTime? _pdp023;
        
        private string _pdp024;
        
        private int _pdp025;
        
        private bool _pdp026;
        
        private bool _pdp027;
        
        private int _pdp028;
        
        private string _pdp029;
        
        private string _pdp030;
        
        private string _pdp031;
        
        private string _pdp032;
        
        private string _pdp033;
        
        private string _pdp034;
        
        private string _pdp035;
        
        private string _pdp036;
        
        private string _pdp037;
        
        private string _pdp038;
        
        private string _pdp039;
        
        private string _pdp040;
        
        private string _pdp041;
        
        private string _pdp042;
        
        private string _pdp043;
        
        private string _pdp044;
        
        private string _pdp045;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string PDP001
        {
            get
            {
                return this._pdp001;
            }
            set
            {
                this._pdp001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PDP002
        {
            get
            {
                return this._pdp002;
            }
            set
            {
                this._pdp002 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PDP003
        {
            get
            {
                return this._pdp003;
            }
            set
            {
                this._pdp003 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string PDP004
        {
            get
            {
                return this._pdp004;
            }
            set
            {
                this._pdp004 = value;
            }
        }

        /// <summary>
        /// 白坯完工累积量
        /// </summary>

        public int PDP005
        {
            get
            {
                return this._pdp005;
            }
            set
            {
                this._pdp005 = value;
            }
        }

        /// <summary>
        /// 白坯报工备注
        /// </summary>

        public string PDP006
        {
            get
            {
                return this._pdp006;
            }
            set
            {
                this._pdp006 = value;
            }
        }

        /// <summary>
        /// 白坯最近来货时间
        /// </summary>

        public DateTime? PDP007
        {
            get
            {
                return this._pdp007;
            }
            set
            {
                this._pdp007 = value;
            }
        }

        /// <summary>
        /// 计划未完工量(底漆)
        /// </summary>

        public int PDP008
        {
            get
            {
                return this._pdp008;
            }
            set
            {
                this._pdp008 = value;
            }
        }

        /// <summary>
        /// 累计完成量(底漆)
        /// </summary>

        public int PDP009
        {
            get
            {
                return this._pdp009;
            }
            set
            {
                this._pdp009 = value;
            }
        }

        /// <summary>
        /// 完工时间(底漆)
        /// </summary>

        public DateTime? PDP010
        {
            get
            {
                return this._pdp010;
            }
            set
            {
                this._pdp010 = value;
            }
        }

        /// <summary>
        ///  计划未完工量(油墨)
        /// </summary>
        public int PDP011
        {
            get
            {
                return this._pdp011;
            }
            set
            {
                this._pdp011 = value;
            }
        }

        /// <summary>
        /// 累计完成量(油墨)
        /// </summary>

        public int PDP012
        {
            get
            {
                return this._pdp012;
            }
            set
            {
                this._pdp012 = value;
            }
        }

        /// <summary>
        /// 完工时间(底漆)
        /// </summary>

        public DateTime? PDP013
        {
            get
            {
                return this._pdp013;
            }
            set
            {
                this._pdp013 = value;
            }
        }

        /// <summary>
        /// 计划未完工量(修色)
        /// </summary>

        public int PDP014
        {
            get
            {
                return this._pdp014;
            }
            set
            {
                this._pdp014 = value;
            }
        }

        /// <summary>
        /// 累计完成量(修色)
        /// </summary>

        public int PDP015
        {
            get
            {
                return this._pdp015;
            }
            set
            {
                this._pdp015 = value;
            }
        }

        /// <summary>
        /// 
        ///  完工时间(修色)
        /// </summary>
        public DateTime? PDP016
        {
            get
            {
                return this._pdp016;
            }
            set
            {
                this._pdp016 = value;
            }
        }

        /// <summary>
        /// 计划未完工量(面漆)
        /// </summary>

        public int PDP017
        {
            get
            {
                return this._pdp017;
            }
            set
            {
                this._pdp017 = value;
            }
        }

        /// <summary>
        /// 累计完成量(面漆)
        /// </summary>

        public int PDP018
        {
            get
            {
                return this._pdp018;
            }
            set
            {
                this._pdp018 = value;
            }
        }

        /// <summary>
        /// 完工时间(面漆)
        /// </summary>

        public DateTime? PDP019
        {
            get
            {
                return this._pdp019;
            }
            set
            {
                this._pdp019 = value;
            }
        }

        /// <summary>
        /// 完工累积量(软包)
        /// </summary>

        public int PDP020
        {
            get
            {
                return this._pdp020;
            }
            set
            {
                this._pdp020 = value;
            }
        }

        /// <summary>
        ///  报工备注(软包)
        /// </summary>
        public string PDP021
        {
            get
            {
                return this._pdp021;
            }
            set
            {
                this._pdp021 = value;
            }
        }

        /// <summary>
        /// 累计完成量(包装)
        /// </summary>

        public int PDP022
        {
            get
            {
                return this._pdp022;
            }
            set
            {
                this._pdp022 = value;
            }
        }

        /// <summary>
        /// 完成时间(包装)
        /// </summary>

        public DateTime? PDP023
        {
            get
            {
                return this._pdp023;
            }
            set
            {
                this._pdp023 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PDP024
        {
            get
            {
                return this._pdp024;
            }
            set
            {
                this._pdp024 = value;
            }
        }

        /// <summary>
        /// 订单量
        /// </summary>

        public int PDP025
        {
            get
            {
                return this._pdp025;
            }
            set
            {
                this._pdp025 = value;
            }
        }

        /// <summary>
        /// 油漆完工标记
        /// </summary>

        public bool PDP026
        {
            get
            {
                return this._pdp026;
            }
            set
            {
                this._pdp026 = value;
            }
        }
        
        /// <summary>
        /// 产品完工标记
        /// </summary>
        
        public bool PDP027
        {
            get
            {
                return this._pdp027;
            }
            set
            {
                this._pdp027 = value;
            }
        }

        /// <summary>
        /// 包装未完工计划量
        /// </summary>

        public int PDP028
        {
            get
            {
                return this._pdp028;
            }
            set
            {
                this._pdp028 = value;
            }
        }
        
        // 
        public string PDP029
        {
            get
            {
                return this._pdp029;
            }
            set
            {
                this._pdp029 = value;
            }
        }
        
        // 
        public string PDP030
        {
            get
            {
                return this._pdp030;
            }
            set
            {
                this._pdp030 = value;
            }
        }
        
        // 
        public string PDP031
        {
            get
            {
                return this._pdp031;
            }
            set
            {
                this._pdp031 = value;
            }
        }
        
        // 
        public string PDP032
        {
            get
            {
                return this._pdp032;
            }
            set
            {
                this._pdp032 = value;
            }
        }
        
        // 
        public string PDP033
        {
            get
            {
                return this._pdp033;
            }
            set
            {
                this._pdp033 = value;
            }
        }
        
        // 
        public string PDP034
        {
            get
            {
                return this._pdp034;
            }
            set
            {
                this._pdp034 = value;
            }
        }
        
        // 
        public string PDP035
        {
            get
            {
                return this._pdp035;
            }
            set
            {
                this._pdp035 = value;
            }
        }
        
        // 
        public string PDP036
        {
            get
            {
                return this._pdp036;
            }
            set
            {
                this._pdp036 = value;
            }
        }
        
        // 
        public string PDP037
        {
            get
            {
                return this._pdp037;
            }
            set
            {
                this._pdp037 = value;
            }
        }
        
        // 
        public string PDP038
        {
            get
            {
                return this._pdp038;
            }
            set
            {
                this._pdp038 = value;
            }
        }
        
        // 
        public string PDP039
        {
            get
            {
                return this._pdp039;
            }
            set
            {
                this._pdp039 = value;
            }
        }
        
        // 
        public string PDP040
        {
            get
            {
                return this._pdp040;
            }
            set
            {
                this._pdp040 = value;
            }
        }
        
        // 
        public string PDP041
        {
            get
            {
                return this._pdp041;
            }
            set
            {
                this._pdp041 = value;
            }
        }
        
        // 
        public string PDP042
        {
            get
            {
                return this._pdp042;
            }
            set
            {
                this._pdp042 = value;
            }
        }
        
        // 
        public string PDP043
        {
            get
            {
                return this._pdp043;
            }
            set
            {
                this._pdp043 = value;
            }
        }
        
        // 
        public string PDP044
        {
            get
            {
                return this._pdp044;
            }
            set
            {
                this._pdp044 = value;
            }
        }
        
        // 
        public string PDP045
        {
            get
            {
                return this._pdp045;
            }
            set
            {
                this._pdp045 = value;
            }
        }
    }
}
