//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class ProgramControlEntity
    {
        
        private int _idx;
        
        private string _for001;
        
        private string _for002;
        
        private string _for003;
        
        private string _for004;
        
        private DateTime _for005;
        
        private string _for006;
        
        private string _for007;
        
        private string _for008;
        
        private string _for009;
        
        private string _for010;
        
        private string _for011;
        
        private string _for012;
        
        private string _for013;
        
        private string _for014;
        
        private string _for015;
        
        private string _for016;
        
        private string _for017;
        
        private string _for018;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 程序名称
        /// </summary>

        public string FOR001
        {
            get
            {
                return this._for001;
            }
            set
            {
                this._for001 = value;
            }
        }

        /// <summary>
        /// 程序编号
        /// </summary>

        public string FOR002
        {
            get
            {
                return this._for002;
            }
            set
            {
                this._for002 = value;
            }
        }

        /// <summary>
        /// 程序类别
        /// </summary>

        public string FOR003
        {
            get
            {
                return this._for003;
            }
            set
            {
                this._for003 = value;
            }
        }

        /// <summary>
        /// 程序用表
        /// </summary>

        public string FOR004
        {
            get
            {
                return this._for004;
            }
            set
            {
                this._for004 = value;
            }
        }
        
        /// <summary>
        /// 日期
        /// </summary>
                 
        public DateTime FOR005
        {
            get
            {
                return this._for005;
            }
            set
            {
                this._for005 = value;
            }
        }
        
        // 
        public string FOR006
        {
            get
            {
                return this._for006;
            }
            set
            {
                this._for006 = value;
            }
        }
        
        // 
        public string FOR007
        {
            get
            {
                return this._for007;
            }
            set
            {
                this._for007 = value;
            }
        }
        
        // 
        public string FOR008
        {
            get
            {
                return this._for008;
            }
            set
            {
                this._for008 = value;
            }
        }
        
        // 
        public string FOR009
        {
            get
            {
                return this._for009;
            }
            set
            {
                this._for009 = value;
            }
        }
        
        // 
        public string FOR010
        {
            get
            {
                return this._for010;
            }
            set
            {
                this._for010 = value;
            }
        }
        
        // 
        public string FOR011
        {
            get
            {
                return this._for011;
            }
            set
            {
                this._for011 = value;
            }
        }
        
        // 
        public string FOR012
        {
            get
            {
                return this._for012;
            }
            set
            {
                this._for012 = value;
            }
        }
        
        // 
        public string FOR013
        {
            get
            {
                return this._for013;
            }
            set
            {
                this._for013 = value;
            }
        }
        
        // 
        public string FOR014
        {
            get
            {
                return this._for014;
            }
            set
            {
                this._for014 = value;
            }
        }
        
        // 
        public string FOR015
        {
            get
            {
                return this._for015;
            }
            set
            {
                this._for015 = value;
            }
        }
        
        // 
        public string FOR016
        {
            get
            {
                return this._for016;
            }
            set
            {
                this._for016 = value;
            }
        }
        
        // 
        public string FOR017
        {
            get
            {
                return this._for017;
            }
            set
            {
                this._for017 = value;
            }
        }
        
        // 
        public string FOR018
        {
            get
            {
                return this._for018;
            }
            set
            {
                this._for018 = value;
            }
        }
    }
}
