//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class RemindEntity
    {
        
        private int _idx;
        
        private string _rev001;
        
        private string _rev002;
        
        private string _rev003;
        
        private DateTime _rev004;
        
        private string _rev005;
        
        private string _rev006;
        
        private string _rev007;
        
        private string _rev008;
        
        private string _rev009;
        
        private string _rev010;
        
        private string _rev011;
        
        private string _rev012;
        
        private string _rev013;
        
        private string _rev014;
        
        private string _rev015;
        
        private string _rev016;
        
        private string _rev017;
        
        private string _rev018;
        
        private string _rev019;
        
        private string _rev020;

        private string _for001;
        private string _emp002;

        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 程序编号
        /// </summary>

        public string REV001
        {
            get
            {
                return this._rev001;
            }
            set
            {
                this._rev001 = value;
            }
        }
        /// <summary>
        /// 程序名称
        /// </summary>
        public string FOR001
        {
            get
            {
                return this . _for001;
            }
            set
            {
                this . _for001 = FOR001;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string REV002
        {
            get
            {
                return this._rev002;
            }
            set
            {
                this._rev002 = value;
            }
        }

        /// <summary>
        /// 送审人编号
        /// </summary>

        public string REV003
        {
            get
            {
                return this._rev003;
            }
            set
            {
                this._rev003 = value;
            }
        }

        /// <summary>
        /// 送审人名称
        /// </summary>
        public string EMP002
        {
            get
            {
                return this . _emp002;
            }
            set
            {
                _emp002 = value;
            }
        }

        /// <summary>
        /// 送审日期
        /// </summary>

        public DateTime REV004
        {
            get
            {
                return this._rev004;
            }
            set
            {
                this._rev004 = value;
            }
        }

        /// <summary>
        /// 送审状态
        /// </summary>

        public string REV005
        {
            get
            {
                return this._rev005;
            }
            set
            {
                this._rev005 = value;
            }
        }

        /// <summary>
        /// 送审意见
        /// </summary>

        public string REV006
        {
            get
            {
                return this._rev006;
            }
            set
            {
                this._rev006 = value;
            }
        }
        
        // 
        public string REV007
        {
            get
            {
                return this._rev007;
            }
            set
            {
                this._rev007 = value;
            }
        }
        
        // 
        public string REV008
        {
            get
            {
                return this._rev008;
            }
            set
            {
                this._rev008 = value;
            }
        }
        
        // 
        public string REV009
        {
            get
            {
                return this._rev009;
            }
            set
            {
                this._rev009 = value;
            }
        }
        
        // 
        public string REV010
        {
            get
            {
                return this._rev010;
            }
            set
            {
                this._rev010 = value;
            }
        }
        
        // 
        public string REV011
        {
            get
            {
                return this._rev011;
            }
            set
            {
                this._rev011 = value;
            }
        }
        
        // 
        public string REV012
        {
            get
            {
                return this._rev012;
            }
            set
            {
                this._rev012 = value;
            }
        }
        
        // 
        public string REV013
        {
            get
            {
                return this._rev013;
            }
            set
            {
                this._rev013 = value;
            }
        }
        
        // 
        public string REV014
        {
            get
            {
                return this._rev014;
            }
            set
            {
                this._rev014 = value;
            }
        }
        
        // 
        public string REV015
        {
            get
            {
                return this._rev015;
            }
            set
            {
                this._rev015 = value;
            }
        }
        
        // 
        public string REV016
        {
            get
            {
                return this._rev016;
            }
            set
            {
                this._rev016 = value;
            }
        }
        
        // 
        public string REV017
        {
            get
            {
                return this._rev017;
            }
            set
            {
                this._rev017 = value;
            }
        }
        
        // 
        public string REV018
        {
            get
            {
                return this._rev018;
            }
            set
            {
                this._rev018 = value;
            }
        }
        
        // 
        public string REV019
        {
            get
            {
                return this._rev019;
            }
            set
            {
                this._rev019 = value;
            }
        }
        
        // 
        public string REV020
        {
            get
            {
                return this._rev020;
            }
            set
            {
                this._rev020 = value;
            }
        }
    }
}
