//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class SetReviewEntity
    {
        
        private int _idx;
        
        private string _sre001;
        
        private string _sre002;
        
        private string _sre003;
        
        private string _sre004;
        
        private DateTime _sre005;
        
        private string _sre006;
        
        private string _sre007;
        
        private string _sre008;
        
        private string _sre009;
        
        private string _sre010;
        
        private string _sre011;
        
        private string _sre012;
        
        private string _sre013;
        
        private string _sre014;
        
        private string _sre015;
        
        private string _sre016;
        
        private string _sre017;
        
        private string _sre018;
        
        private string _sre019;
        
        private string _sre020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 序号
        /// </summary>

        public string SRE001
        {
            get
            {
                return this._sre001;
            }
            set
            {
                this._sre001 = value;
            }
        }

        /// <summary>
        /// 程序编号
        /// </summary>

        public string SRE002
        {
            get
            {
                return this._sre002;
            }
            set
            {
                this._sre002 = value;
            }
        }

        /// <summary>
        /// 人员编号
        /// </summary>

        public string SRE003
        {
            get
            {
                return this._sre003;
            }
            set
            {
                this._sre003 = value;
            }
        }

        /// <summary>
        /// 送审级别
        /// </summary>

        public string SRE004
        {
            get
            {
                return this._sre004;
            }
            set
            {
                this._sre004 = value;
            }
        }

        /// <summary>
        /// 日期
        /// </summary>

        public DateTime SRE005
        {
            get
            {
                return this._sre005;
            }
            set
            {
                this._sre005 = value;
            }
        }

        /// <summary>
        /// 设置人
        /// </summary>

        public string SRE006
        {
            get
            {
                return this._sre006;
            }
            set
            {
                this._sre006 = value;
            }
        }
        
        // 
        public string SRE007
        {
            get
            {
                return this._sre007;
            }
            set
            {
                this._sre007 = value;
            }
        }
        
        // 
        public string SRE008
        {
            get
            {
                return this._sre008;
            }
            set
            {
                this._sre008 = value;
            }
        }
        
        // 
        public string SRE009
        {
            get
            {
                return this._sre009;
            }
            set
            {
                this._sre009 = value;
            }
        }
        
        // 
        public string SRE010
        {
            get
            {
                return this._sre010;
            }
            set
            {
                this._sre010 = value;
            }
        }
        
        // 
        public string SRE011
        {
            get
            {
                return this._sre011;
            }
            set
            {
                this._sre011 = value;
            }
        }
        
        // 
        public string SRE012
        {
            get
            {
                return this._sre012;
            }
            set
            {
                this._sre012 = value;
            }
        }
        
        // 
        public string SRE013
        {
            get
            {
                return this._sre013;
            }
            set
            {
                this._sre013 = value;
            }
        }
        
        // 
        public string SRE014
        {
            get
            {
                return this._sre014;
            }
            set
            {
                this._sre014 = value;
            }
        }
        
        // 
        public string SRE015
        {
            get
            {
                return this._sre015;
            }
            set
            {
                this._sre015 = value;
            }
        }
        
        // 
        public string SRE016
        {
            get
            {
                return this._sre016;
            }
            set
            {
                this._sre016 = value;
            }
        }
        
        // 
        public string SRE017
        {
            get
            {
                return this._sre017;
            }
            set
            {
                this._sre017 = value;
            }
        }
        
        // 
        public string SRE018
        {
            get
            {
                return this._sre018;
            }
            set
            {
                this._sre018 = value;
            }
        }
        
        // 
        public string SRE019
        {
            get
            {
                return this._sre019;
            }
            set
            {
                this._sre019 = value;
            }
        }
        
        // 
        public string SRE020
        {
            get
            {
                return this._sre020;
            }
            set
            {
                this._sre020 = value;
            }
        }
    }
}
