//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class SetTransmitEntity
    {
        
        private int _idx;
        
        private string _str001;
        
        private string _str002;
        
        private string _str003;
        
        private string _str004;
        
        private DateTime _str005;
        
        private string _str006;
        
        private string _str007;
        
        private string _str008;
        
        private string _str009;
        
        private string _str010;
        
        private string _str011;
        
        private string _str012;
        
        private string _str013;
        
        private string _str014;
        
        private string _str015;
        
        private string _str016;
        
        private string _str017;
        
        private string _str018;
        
        private string _str019;
        
        private string _str020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单据编号
        /// </summary>

        public string STR001
        {
            get
            {
                return this._str001;
            }
            set
            {
                this._str001 = value;
            }
        }

        /// <summary>
        /// 单据类别
        /// </summary>

        public string STR002
        {
            get
            {
                return this._str002;
            }
            set
            {
                this._str002 = value;
            }
        }

        /// <summary>
        /// 人员编号
        /// </summary>

        public string STR003
        {
            get
            {
                return this._str003;
            }
            set
            {
                this._str003 = value;
            }
        }

        /// <summary>
        /// 人员姓名
        /// </summary>

        public string STR004
        {
            get
            {
                return this._str004;
            }
            set
            {
                this._str004 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime STR005
        {
            get
            {
                return this._str005;
            }
            set
            {
                this._str005 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string STR006
        {
            get
            {
                return this._str006;
            }
            set
            {
                this._str006 = value;
            }
        }
        
        // 
        public string STR007
        {
            get
            {
                return this._str007;
            }
            set
            {
                this._str007 = value;
            }
        }
        
        // 
        public string STR008
        {
            get
            {
                return this._str008;
            }
            set
            {
                this._str008 = value;
            }
        }
        
        // 
        public string STR009
        {
            get
            {
                return this._str009;
            }
            set
            {
                this._str009 = value;
            }
        }
        
        // 
        public string STR010
        {
            get
            {
                return this._str010;
            }
            set
            {
                this._str010 = value;
            }
        }
        
        // 
        public string STR011
        {
            get
            {
                return this._str011;
            }
            set
            {
                this._str011 = value;
            }
        }
        
        // 
        public string STR012
        {
            get
            {
                return this._str012;
            }
            set
            {
                this._str012 = value;
            }
        }
        
        // 
        public string STR013
        {
            get
            {
                return this._str013;
            }
            set
            {
                this._str013 = value;
            }
        }
        
        // 
        public string STR014
        {
            get
            {
                return this._str014;
            }
            set
            {
                this._str014 = value;
            }
        }
        
        // 
        public string STR015
        {
            get
            {
                return this._str015;
            }
            set
            {
                this._str015 = value;
            }
        }
        
        // 
        public string STR016
        {
            get
            {
                return this._str016;
            }
            set
            {
                this._str016 = value;
            }
        }
        
        // 
        public string STR017
        {
            get
            {
                return this._str017;
            }
            set
            {
                this._str017 = value;
            }
        }
        
        // 
        public string STR018
        {
            get
            {
                return this._str018;
            }
            set
            {
                this._str018 = value;
            }
        }
        
        // 
        public string STR019
        {
            get
            {
                return this._str019;
            }
            set
            {
                this._str019 = value;
            }
        }
        
        // 
        public string STR020
        {
            get
            {
                return this._str020;
            }
            set
            {
                this._str020 = value;
            }
        }
    }
}
