//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class TransmitEntity
    {
        
        private int _idx;
        
        private string _tra001;
        
        private string _tra002;
        
        private DateTime _tra003;
        
        private string _tra004;
        
        private string _tra005;
        
        private string _tra006;
        
        private string _tra007;
        
        private string _tra008;
        
        private string _tra009;
        
        private string _tra010;
        
        private string _tra011;
        
        private string _tra012;
        
        private string _tra013;
        
        private string _tra014;
        
        private string _tra015;
        
        private string _tra016;
        
        private string _tra017;
        
        private string _tra018;
        
        private string _tra019;
        
        private string _tra020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单据编号
        /// </summary>

        public string TRA001
        {
            get
            {
                return this._tra001;
            }
            set
            {
                this._tra001 = value;
            }
        }

        /// <summary>
        /// 单据类别
        /// </summary>

        public string TRA002
        {
            get
            {
                return this._tra002;
            }
            set
            {
                this._tra002 = value;
            }
        }

        /// <summary>
        /// 时间
        /// </summary>

        public DateTime TRA003
        {
            get
            {
                return this._tra003;
            }
            set
            {
                this._tra003 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string TRA004
        {
            get
            {
                return this._tra004;
            }
            set
            {
                this._tra004 = value;
            }
        }
        
        // 
        public string TRA005
        {
            get
            {
                return this._tra005;
            }
            set
            {
                this._tra005 = value;
            }
        }
        
        // 
        public string TRA006
        {
            get
            {
                return this._tra006;
            }
            set
            {
                this._tra006 = value;
            }
        }
        
        // 
        public string TRA007
        {
            get
            {
                return this._tra007;
            }
            set
            {
                this._tra007 = value;
            }
        }
        
        // 
        public string TRA008
        {
            get
            {
                return this._tra008;
            }
            set
            {
                this._tra008 = value;
            }
        }
        
        // 
        public string TRA009
        {
            get
            {
                return this._tra009;
            }
            set
            {
                this._tra009 = value;
            }
        }
        
        // 
        public string TRA010
        {
            get
            {
                return this._tra010;
            }
            set
            {
                this._tra010 = value;
            }
        }
        
        // 
        public string TRA011
        {
            get
            {
                return this._tra011;
            }
            set
            {
                this._tra011 = value;
            }
        }
        
        // 
        public string TRA012
        {
            get
            {
                return this._tra012;
            }
            set
            {
                this._tra012 = value;
            }
        }
        
        // 
        public string TRA013
        {
            get
            {
                return this._tra013;
            }
            set
            {
                this._tra013 = value;
            }
        }
        
        // 
        public string TRA014
        {
            get
            {
                return this._tra014;
            }
            set
            {
                this._tra014 = value;
            }
        }
        
        // 
        public string TRA015
        {
            get
            {
                return this._tra015;
            }
            set
            {
                this._tra015 = value;
            }
        }
        
        // 
        public string TRA016
        {
            get
            {
                return this._tra016;
            }
            set
            {
                this._tra016 = value;
            }
        }
        
        // 
        public string TRA017
        {
            get
            {
                return this._tra017;
            }
            set
            {
                this._tra017 = value;
            }
        }
        
        // 
        public string TRA018
        {
            get
            {
                return this._tra018;
            }
            set
            {
                this._tra018 = value;
            }
        }
        
        // 
        public string TRA019
        {
            get
            {
                return this._tra019;
            }
            set
            {
                this._tra019 = value;
            }
        }
        
        // 
        public string TRA020
        {
            get
            {
                return this._tra020;
            }
            set
            {
                this._tra020 = value;
            }
        }
    }
}
