//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpenterEntity
{
    using System;
    
    
    public sealed class WOODEntity
    {
        
        private int _idx;
        
        private string _wod001;
        
        private string _wod002;
        
        private string _wod003;
        
        private string _wod004;
        
        private string _wod005;
        
        private string _wod006;
        
        private string _wod007;
        
        private decimal _wod008;
        
        private DateTime _wod009;
        
        private string _wod010;
        
        private bool _wod011;
        
        private string _wod012;
        
        private string _wod013;
        
        private string _wod014;
        
        private string _wod015;
        
        private string _wod016;
        
        private string _wod017;
        
        private string _wod018;
        
        private string _wod019;
        
        private string _wod020;
        
        private string _wod021;
        
        private string _wod022;
        
        private string _wod023;
        
        private string _wod024;
        
        private string _wod025;
        
        private string _wod026;
        
        private string _wod027;
        
        private string _wod028;
        
        private string _wod029;
        
        private string _wod030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string WOD001
        {
            get
            {
                return this._wod001;
            }
            set
            {
                this._wod001 = value;
            }
        }

        /// <summary>
        /// 序号
        /// </summary>

        public string WOD002
        {
            get
            {
                return this._wod002;
            }
            set
            {
                this._wod002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string WOD003
        {
            get
            {
                return this._wod003;
            }
            set
            {
                this._wod003 = value;
            }
        }

        /// <summary>
        /// 木材编码
        /// </summary>

        public string WOD004
        {
            get
            {
                return this._wod004;
            }
            set
            {
                this._wod004 = value;
            }
        }

        /// <summary>
        /// 木材名称
        /// </summary>

        public string WOD005
        {
            get
            {
                return this._wod005;
            }
            set
            {
                this._wod005 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string WOD006
        {
            get
            {
                return this._wod006;
            }
            set
            {
                this._wod006 = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>

        public string WOD007
        {
            get
            {
                return this._wod007;
            }
            set
            {
                this._wod007 = value;
            }
        }

        /// <summary>
        /// 用量
        /// </summary>

        public decimal WOD008
        {
            get
            {
                return this._wod008;
            }
            set
            {
                this._wod008 = value;
            }
        }

        /// <summary>
        /// 日期
        /// </summary>

        public DateTime WOD009
        {
            get
            {
                return this._wod009;
            }
            set
            {
                this._wod009 = value;
            }
        }

        /// <summary>
        /// 操作者
        /// </summary>

        public string WOD010
        {
            get
            {
                return this._wod010;
            }
            set
            {
                this._wod010 = value;
            }
        }
        
        /// <summary>
        /// 注销
        /// </summary>
                 
        public bool WOD011
        {
            get
            {
                return this._wod011;
            }
            set
            {
                this._wod011 = value;
            }
        }
        
        // 
        public string WOD012
        {
            get
            {
                return this._wod012;
            }
            set
            {
                this._wod012 = value;
            }
        }
        
        // 
        public string WOD013
        {
            get
            {
                return this._wod013;
            }
            set
            {
                this._wod013 = value;
            }
        }
        
        // 
        public string WOD014
        {
            get
            {
                return this._wod014;
            }
            set
            {
                this._wod014 = value;
            }
        }
        
        // 
        public string WOD015
        {
            get
            {
                return this._wod015;
            }
            set
            {
                this._wod015 = value;
            }
        }
        
        // 
        public string WOD016
        {
            get
            {
                return this._wod016;
            }
            set
            {
                this._wod016 = value;
            }
        }
        
        // 
        public string WOD017
        {
            get
            {
                return this._wod017;
            }
            set
            {
                this._wod017 = value;
            }
        }
        
        // 
        public string WOD018
        {
            get
            {
                return this._wod018;
            }
            set
            {
                this._wod018 = value;
            }
        }
        
        // 
        public string WOD019
        {
            get
            {
                return this._wod019;
            }
            set
            {
                this._wod019 = value;
            }
        }
        
        // 
        public string WOD020
        {
            get
            {
                return this._wod020;
            }
            set
            {
                this._wod020 = value;
            }
        }
        
        // 
        public string WOD021
        {
            get
            {
                return this._wod021;
            }
            set
            {
                this._wod021 = value;
            }
        }
        
        // 
        public string WOD022
        {
            get
            {
                return this._wod022;
            }
            set
            {
                this._wod022 = value;
            }
        }
        
        // 
        public string WOD023
        {
            get
            {
                return this._wod023;
            }
            set
            {
                this._wod023 = value;
            }
        }
        
        // 
        public string WOD024
        {
            get
            {
                return this._wod024;
            }
            set
            {
                this._wod024 = value;
            }
        }
        
        // 
        public string WOD025
        {
            get
            {
                return this._wod025;
            }
            set
            {
                this._wod025 = value;
            }
        }
        
        // 
        public string WOD026
        {
            get
            {
                return this._wod026;
            }
            set
            {
                this._wod026 = value;
            }
        }
        
        // 
        public string WOD027
        {
            get
            {
                return this._wod027;
            }
            set
            {
                this._wod027 = value;
            }
        }
        
        // 
        public string WOD028
        {
            get
            {
                return this._wod028;
            }
            set
            {
                this._wod028 = value;
            }
        }
        
        // 
        public string WOD029
        {
            get
            {
                return this._wod029;
            }
            set
            {
                this._wod029 = value;
            }
        }
        
        // 
        public string WOD030
        {
            get
            {
                return this._wod030;
            }
            set
            {
                this._wod030 = value;
            }
        }
    }
}
